// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

use std::sync::Arc;
use tokio_util::sync::CancellationToken;
use serde_json;
use serde_json::Value;

use crate::ai_config::{CompletionRequest, CompletionResponse, ContentBlock, ToolCall, ToolDefinition, Usage};
use crate::error::{LlmError};
use crate::sse::SseParser;
use crate::provider::{AiProvider, StreamDelta};
/// Anthropic Claude provider.
/// 
/// Auto port of crates/auto-ai-daemon/src/provider/anthropic.rs (non-streaming
/// parts). Uses the Anthropic Messages API (`/v1/messages`).
/// 
/// See openai.at for the HTTP/STREAM/JSON notes (same conventions apply: global
/// `http` module for non-streaming, complete_stream delegated to provider_glue,
/// serde_json::Map hand-built instead of json! macro).
/// One Anthropic provider instance.
#[allow(dead_code)]
pub struct AnthropicProvider {
    pub name: String,
    pub base_url: String,
    pub api_key: String,
    pub models_list: Vec<String>,
}

#[async_trait::async_trait]
impl AiProvider for AnthropicProvider {
    fn name(&self) -> String {
        return self.name.clone();
    }
    fn models(&self) -> Vec<String> {
        return self.models_list.clone();
    }
    async fn complete(&self, req: &CompletionRequest) -> Result<CompletionResponse, LlmError> {
        let body = self.build_body(req.clone());
        let url = self.url();

        let resp = a2r_std::http::request("POST", url.as_str()).header("x-api-key", &self.api_key).header("anthropic-version", "2023-06-01").header("Content-Type", "application/json").body(a2r_std::json::to_string(&body)).send_async().await;

        let status = resp.status_code();
        if status < 200 || status >= 300 {
            let text = bytes_to_str(resp.body_bytes());
            return Err(LlmError::from_upstream_status(reqwest::StatusCode::from_u16(status as u16).unwrap_or(reqwest::StatusCode::BAD_GATEWAY), &text));
        }

        let text = bytes_to_str(resp.body_bytes());
        let v = a2r_std::json::parse(text.as_str());


        let mut content: String = "".to_string();
        let mut tool_calls: Vec<ToolCall> = vec![];
        let blocks = a2r_std::json::get(&v, "content");
        if blocks.is_null() == false {
            for b in a2r_std::json::as_array(&blocks) {
                let btype = a2r_std::json::get_str(&b, "type");
                match btype.as_str() {
                    "text" => content = format!("{}{}", content, a2r_std::json::get_str(&b, "text")),
                    "tool_use" => {
                        let id = a2r_std::json::get_str(&b, "id");
                        let tc_name = a2r_std::json::get_str(&b, "name");
                        let input = a2r_std::json::get(&b, "input");
                        tool_calls.push(ToolCall { id: id, name: tc_name, input: input });
                    },
                    _ => {},
                };
            }
        }

        let stop_reason = opt_str_field(v.clone(), "stop_reason");
        let usage = parse_usage_anthropic(v.clone());
        let model_field = a2r_std::json::get_str(&v, "model");
        let model = match model_field.is_empty() { true => req.model.clone(), false => model_field, };

        return Ok(CompletionResponse { content: content, tool_calls: tool_calls, stop_reason: stop_reason, usage: usage, model: model, error: None });
    }
    async fn complete_stream(&self, req: &CompletionRequest, on_delta: Arc<dyn Fn(StreamDelta) + Send + Sync>, cancel: CancellationToken) -> Result<CompletionResponse, LlmError> {
        return crate::provider_glue::anthropic_complete_stream(self, req, on_delta, cancel).await;
    }
}

impl AnthropicProvider {
    pub fn new(name: String, base_url: String, api_key: String, models: Vec<String>) -> AnthropicProvider {
        return AnthropicProvider { name: name.to_string(), base_url: base_url.to_string(), api_key: api_key.to_string(), models_list: models };
    }
    pub fn url(&self) -> String {
        let base = self.base_url.trim_end_matches("/");
        return format!("{}/v1/messages", base);
    }
    pub fn build_body(&self, req: CompletionRequest) -> Value {
        let mut messages: Vec<Value> = vec![];



        if req.messages.is_empty() == false {
            if req.messages[0].clone().role.to_string() != "user" {
                let mut anchor = serde_json::Map::new();
                anchor.insert("role".to_string(), Value::String("user".to_string()));
                let mut anchor_block = serde_json::Map::new();
                anchor_block.insert("type".to_string(), Value::String("text".to_string()));
                anchor_block.insert("text".to_string(), Value::String("(continued)".to_string()));
                let mut anchor_blocks: Vec<Value> = vec![];
                anchor_blocks.push(Value::Object(anchor_block));
                anchor.insert("content".to_string(), Value::Array(anchor_blocks));
                messages.push(Value::Object(anchor));
            }        }
        for m in &req.messages {
            let mut obj = serde_json::Map::new();
            obj.insert("role".to_string(), Value::String(m.role.clone()));
            obj.insert("content".to_string(), content_blocks_to_anthropic(&m.content));
            messages.push(Value::Object(obj));
        }

        let mut body = serde_json::Map::new();
        body.insert("model".to_string(), Value::String(req.model));


        if req.max_tokens.is_some() {
            let n = req.max_tokens.unwrap();
            body.insert("max_tokens".to_string(), Value::Number(serde_json::Number::from(n)));
        } else {
            body.insert("max_tokens".to_string(), Value::Number(serde_json::Number::from(4096)));
        }

        body.insert("messages".to_string(), Value::Array(messages));

        if req.system_prompt.is_some() {
            let sys = req.system_prompt.unwrap();
            body.insert("system".to_string(), Value::String(sys));
        }
        if req.temperature.is_some() {
            let t = req.temperature.unwrap();
            body.insert("temperature".to_string(), Value::Number(serde_json::Number::from_f64(t).unwrap_or(serde_json::Number::from(0))));
        }

        if req.tools.is_empty() == false {
            let mut tools_arr: Vec<Value> = vec![];
            for t in &req.tools {
                tools_arr.push(tool_to_anthropic(t));
            }
            body.insert("tools".to_string(), Value::Array(tools_arr));
        }

        return Value::Object(body);
    }
}

/// Non-streaming completion. POSTs to /v1/messages, parses the response.
/// Streaming completion. Delegates to provider_glue (tokio::select! loop).
/// Construct an Anthropic provider.
/// The `/v1/messages` endpoint URL.
/// Build the Anthropic Messages API request body.
/// Translate our content blocks into Anthropic's content block array.
fn content_blocks_to_anthropic(blocks: &Vec<ContentBlock>) -> Value {
    let mut out: Vec<Value> = vec![];
    for b in blocks {
        match b {
            ContentBlock::Text { text } => {
                let mut obj = serde_json::Map::new();
                obj.insert("type".to_string(), Value::String("text".to_string()));
                obj.insert("text".to_string(), Value::String(text.to_string()));
                out.push(Value::Object(obj));
            },
            ContentBlock::ToolUse { id, name, input } => {
                let mut obj = serde_json::Map::new();
                obj.insert("type".to_string(), Value::String("tool_use".to_string()));
                obj.insert("id".to_string(), Value::String(id.to_string()));
                obj.insert("name".to_string(), Value::String(name.to_string()));
                obj.insert("input".to_string(), input.clone());
                out.push(Value::Object(obj));
            },
            ContentBlock::ToolResult { tool_use_id, content, is_error } => {
                let mut obj = serde_json::Map::new();
                obj.insert("type".to_string(), Value::String("tool_result".to_string()));
                obj.insert("tool_use_id".to_string(), Value::String(tool_use_id.to_string()));
                obj.insert("content".to_string(), Value::String(content.to_string()));
                obj.insert("is_error".to_string(), Value::Bool(*is_error));
                out.push(Value::Object(obj));
            },
        };
    }
    return Value::Array(out);
}

/// Translate our ToolDefinition to Anthropic's tool object.
fn tool_to_anthropic(t: &ToolDefinition) -> Value {
    let mut obj = serde_json::Map::new();
    obj.insert("name".to_string(), Value::String(t.name.clone()));
    obj.insert("description".to_string(), Value::String(t.description.clone()));
    obj.insert("input_schema".to_string(), t.parameters.clone());
    return Value::Object(obj);
}

fn bytes_to_str(bytes: Vec<u8>) -> String {
    return a2r_std::str::from_bytes(bytes);
}

fn opt_str_field(value: Value, key: &str) -> Option<String> {
    let s = a2r_std::json::get_str(&value, key);
    if s.is_empty() {
        return None;
    }
    return Some(s);
}

/// Parse usage (Anthropic shape: input_tokens/output_tokens), or None.
fn parse_usage_anthropic(value: Value) -> Option<Usage> {
    let u = a2r_std::json::get(&value, "usage");
    if u.is_null() {
        return None;
    }
    return Some(Usage { input_tokens: a2r_std::json::as_int(&a2r_std::json::get(&u, "input_tokens")) as u32, output_tokens: a2r_std::json::as_int(&a2r_std::json::get(&u, "output_tokens")) as u32 });
}
