// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

use std::path::PathBuf;
use std::process;
use crate::ai_config;
use crate::ai_config::DaemonConfig;
const DEFAULT_CONCURRENCY: usize = 4;

pub fn load() -> DaemonConfig {
    match load_from_file() {
        Some(cfg) => return cfg,
        None => {},
    };
    return load_from_env();
}

/// Daemon configuration — delegates parsing to `ai-config`.
/// 
/// Auto port of crates/auto-ai-daemon/src/config.rs. The `DaemonConfig` struct
/// and `.at` parsing live in the shared `ai-config` crate so client and daemon
/// agree on the provider layout. This module just adds the daemon-specific load
/// entry points (file discovery + env fallback) on top of it.
/// 
/// TYPE NOTE: the daemon crate links the **rust-ref** `ai-config` (Cargo.toml
/// `[lib] path = "rust-ref/src/lib.rs"`), so the field shapes here mirror
/// rust-ref's DaemonConfig (no `provider_names` field; `idle_timeout_min: u64`;
/// `max_concurrency: Option<usize>`), not the in-progress ai-config `.at`
/// transpilation. The runtime path runs under cargo.
/// 
/// a2r-FIRST NOTE: `dirs::home_dir()` / `std::fs::read_to_string` bridge to the
/// Rust `dirs`/`std` crates (same pattern as auto-ai-agent/src/validate.at); the
/// parser itself (`parse_daemon_config`) is a2r-first (ai-config/loader.at).
/// Load daemon config from `~/.config/autoos/ai-daemon.at`, else from env.
/// 
/// Mirrors rust-ref config.rs:load(). Falls back to env-var providers when the
/// config file is absent/unreadable. Exits the process if no provider can be
/// built (a daemon with zero providers would fail every request at runtime).
/// Read & parse `~/.config/autoos/ai-daemon.at`. None if the file is absent or
/// unreadable/unparseable (so `load()` can fall back to env).
fn load_from_file() -> Option<DaemonConfig> {
    match home_dir() {
        Some(home) => {
            let path = home.join(".config/autoos/ai-daemon.at");
            let path_str = path.to_str().unwrap();
            if a2r_std::fs::exists(path_str) == false {
                return None;
            }
            let content = read_file_text(path_str);
            if content.is_empty() {
                return None;
            }
            match ai_config::parse_daemon_config(content.as_str()) {
                Ok(cfg) => return Some(cfg),
                Err(_) => return None,
            };
        },
        None => return None,
    };
    return None;
}

/// Env-var fallback (Forge-compatible): ZHIPU_API_KEY / ANTHROPIC_API_KEY /
/// OPENAI_API_KEY, each with a default concurrency cap of 4.
/// 
/// Exits the process if no provider can be built — a daemon with zero providers
/// would just fail every request with NoProvider at runtime, so failing fast at
/// startup is clearer (startup-time exit is acceptable per our conventions).
fn load_from_env() -> DaemonConfig {
    let mut providers: std::collections::HashMap<String, ai_config::ProviderConfig> = std::collections::HashMap::new();


    let zhipu_key = a2r_std::env::get("ZHIPU_API_KEY");
    if zhipu_key.is_empty() == false {
        let models = vec![ai_config::ModelDefinition::new("glm-4.6", ai_config::ModelTier::Mid), ai_config::ModelDefinition::new("glm-4-flash", ai_config::ModelTier::Min)];
        providers.insert("zhipu".to_string(), provider_env("openai", "https://open.bigmodel.cn/api/paas/v4", zhipu_key.as_str(), models));
    }


    let anthropic_key = a2r_std::env::get("ANTHROPIC_API_KEY");
    let anthropic_token = a2r_std::env::get("ANTHROPIC_AUTH_TOKEN");
    let anthropic_base = a2r_std::env::get("ANTHROPIC_BASE_URL");
    let key = first_non_empty(anthropic_key.as_str(), anthropic_token.as_str());
    if key.is_empty() == false {
        let base = first_non_empty(anthropic_base.as_str(), "https://api.anthropic.com");
        let models = vec![ai_config::ModelDefinition::new("claude-3-5-sonnet-20241022", ai_config::ModelTier::Mid)];
        providers.insert("anthropic".to_string(), provider_env("anthropic", base.as_str(), key.as_str(), models));
    }


    let openai_key = a2r_std::env::get("OPENAI_API_KEY");
    let openai_base = a2r_std::env::get("OPENAI_BASE_URL");
    if openai_key.is_empty() == false {
        let base = first_non_empty(openai_base.as_str(), "https://api.openai.com/v1");
        let models = vec![ai_config::ModelDefinition::new("gpt-4o", ai_config::ModelTier::Mid)];
        providers.insert("openai".to_string(), provider_env("openai", base.as_str(), openai_key.as_str(), models));
    }

    if providers.is_empty() {
        fatal_no_provider();
    }




    let mut default_provider = pick_default(providers.clone());
    let mut default_model = default_model_id(providers.clone(), default_provider.as_str());






    let mut cfg = ai_config::DaemonConfig::default();
    cfg.providers = providers;
    cfg.default_provider = default_provider;
    cfg.default_model = default_model;
    return cfg;
}

/// Build a ProviderConfig from env-style params (the daemon-side constructor).
fn provider_env(kind: &str, base_url: &str, key: &str, models: Vec<ai_config::ModelDefinition>) -> ai_config::ProviderConfig {
    return ai_config::ProviderConfig { kind: kind.to_string(), base_url: base_url.to_string(), api_key: Some(key.to_string()), key_env: None, models: models, max_concurrency: Some(DEFAULT_CONCURRENCY), auth_required: true };
}

/// Default-provider priority: zhipu > anthropic > openai; else first sorted name.
/// (Mirrors config.rs:84-92. Walks a fixed priority list rather than relying on
/// HashMap iteration order — .at Map has no iteration API.)
fn pick_default(providers: std::collections::HashMap<String, ai_config::ProviderConfig>) -> String {
    for candidate in vec!["zhipu".to_string(), "anthropic".to_string(), "openai".to_string()] {
        if providers.contains_key(&candidate) {
            return candidate;
        }
    }




    return first_key(providers.clone());
}

/// The first key in the map by probe order (zhipu, anthropic, openai), else "".
/// (Deterministic stand-in for `providers.keys().min()` — the rust-ref sorts the
/// collected keys; .at Map has no keys iterator so we probe the known set.)
fn first_key(providers: std::collections::HashMap<String, ai_config::ProviderConfig>) -> String {
    for k in vec!["zhipu".to_string(), "anthropic".to_string(), "openai".to_string()] {
        if providers.contains_key(&k) {
            return k;
        }
    }
    return "".to_string();
}

/// The id of the default provider's first model, or "" if none.
fn default_model_id(providers: std::collections::HashMap<String, ai_config::ProviderConfig>, default_provider: &str) -> String {
    match providers.get(default_provider) {
        Some(p) => {
            if p.models.is_empty() {
                return "".to_string();
            }
            return p.models[0].clone().id;
        },
        None => return "".to_string(),
    };
    return "".to_string();
}

/// The first argument if non-empty, else the second.
fn first_non_empty(a: &str, b: &str) -> String {
    if a.is_empty() == false {
        return a.to_string();
    }
    return b.to_string();
}

/// The user's home directory, or None if it can't be determined.
fn home_dir() -> Option<PathBuf> {
    return dirs::home_dir();
}

/// Read a file's full contents as text ("" if unreadable — a2r-std parity).
fn read_file_text(path: &str) -> String {
    return a2r_std::fs::read_to_string(path);
}

/// Abort startup with a diagnostic: no provider could be configured. Exits the
/// process (mirrors rust-ref's panic! at startup; .at has no panic primitive,
/// so we bridge to std::process::exit).
fn fatal_no_provider() {
    process::exit(1);
}
