// Auto-generated by a2r transpiler

use reqwest::StatusCode;
/// Error from an LLM API call (used by the provider layer).
/// 
/// Auto port of the `LlmError` enum + helpers from crates/auto-ai-daemon/src/
/// lib.rs (extracted into its own module so lib.rs stays the assembled crate
/// root). The structured variants (`RateLimited` / `Timeout` / `Upstream`) let
/// the tier router decide whether to fall back to the next provider candidate:
/// rate limits, timeouts, and 5xx are retryable on another provider; 4xx (other
/// than 429) indicate a request-shape problem that fallback won't fix.
/// 
/// DISPLAY/FROM NOTE: a2r can't emit `impl Display` (uses the `write!` macro) or
/// `impl From<reqwest::Error>` (Auto has no impl From). So the human-readable
/// form is a `.message()` method (same pattern as agent/error.at +
/// client/error.at), and the reqwest conversion is a factory
/// `.from_reqwest_error()`. retranspile.sh then sed-injects the real
/// `impl Display` / `impl std::error::Error` / `impl From<reqwest::Error>` so
/// the provider layer's `?` / `.into()` (Phase 4) keep working.
/// Error from an LLM API call.
#[derive(Debug)]
pub enum LlmError {
    Http(String),
    RateLimited,
    Timeout(String),
    Upstream { status: u32, message: String, retryable: bool },
    Api(String),
    NoProvider,
    NoApiKey(String),
}


impl LlmError {
    pub fn is_retryable(&self) -> bool {
        match self {
            LlmError::RateLimited => return true,
            LlmError::Timeout(_) => return true,
            LlmError::Upstream { status, message, retryable } => return *retryable,
            LlmError::Http(_) => return true,
            LlmError::Api(_) => return false,
            LlmError::NoProvider => return false,
            LlmError::NoApiKey(_) => return false,
        };
        return false;
    }
    pub fn is_quota_exhausted(&self) -> bool {
        match self {
            LlmError::Upstream { status, message, retryable: _retryable } => {
                if *status == 402 {
                    return true;
                }
                let lower = message.to_lowercase();
                if lower.contains("insufficient_quota") {
                    return true;
                }
                if lower.contains("quota_exceeded") {
                    return true;
                }
                if lower.contains("billing") {
                    return true;
                }
                if lower.contains("exceeded your current quota") {
                    return true;
                }
                return false;
            },
            _ => return false,
        }
    }
    pub fn from_upstream_status(status: StatusCode, body: &str) -> LlmError {
        let code = status.as_u16();
        if code == 429 {
            return LlmError::RateLimited;
        }
        return LlmError::Upstream { status: code as u32, message: body.to_string(), retryable: status.is_server_error() };
    }
    pub fn message(&self) -> String {
        match self {
            LlmError::Http(e) => return format!("HTTP error: {}", e),
            LlmError::RateLimited => return "rate limited (HTTP 429)".to_string(),
            LlmError::Timeout(e) => return format!("timeout: {}", e),
            LlmError::Upstream { status, message, retryable } => return format!("upstream error ({}): {}", status, message),
            LlmError::Api(e) => return format!("API error: {}", e),
            LlmError::NoProvider => return "no provider configured".to_string(),
            LlmError::NoApiKey(p) => return format!("no API key for provider '{}'", p),
        };
        return "".to_string();
    }
    pub fn from_reqwest_error(e: reqwest::Error) -> LlmError {
        if e.is_timeout() {
            return LlmError::Timeout(e.to_string());
        }
        return LlmError::Http(e.to_string());
    }
}
impl std::fmt::Display for LlmError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.message())
    }
}
impl std::error::Error for LlmError {}

// Injected by retranspile.sh: impl From<reqwest::Error> (a2r can't emit impl
// From; mirrors the from_reqwest_error() factory. Classifies timeouts so the
// tier router treats them as retryable.)
impl From<reqwest::Error> for LlmError {
    fn from(e: reqwest::Error) -> Self {
        if e.is_timeout() {
            return Self::Timeout(e.to_string());
        }
        Self::Http(e.to_string())
    }
}
