// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

use serde_json;
use serde_json::Value;

use crate::ai_config;
use crate::ai_config::{ContentBlock, ToolDefinition, ToolCall};
/// Shared OpenAI chat-completions wire-format translation.
/// 
/// Auto port of crates/auto-ai-daemon/src/format.rs. The daemon's OpenAiProvider
/// speaks OpenAI's `/v1/chat/completions` format; this module centralizes the
/// translation of our provider-agnostic ContentBlocks into OpenAI message shapes
/// (plain text, assistant tool_calls, and role:"tool" results).
/// 
/// TYPE NOTE: links the rust-ref ai-config. ContentBlock variants use named
/// fields there (Text{text}, ToolUse{id,name,input}, ToolResult{tool_use_id,
/// content, is_error}); a2r's `is block { ContentBlock.X(...) -> }` renders the
/// matching `match` arms correctly.
/// 
/// JSON-BUILD NOTE: `serde_json::json!({...})` is a macro a2r can't emit, so the
/// two object constructions (tool_call, tool_to_openai) build serde_json::Map +
/// Value::Object by hand — a verified-clean a2r pattern.
/// One tool result extracted from a message's content blocks, ready to become
/// an OpenAI `role:"tool"` message.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct OpenAiToolResult {
    pub tool_call_id: String,
    pub content: String,
}

/// Classifies a message's content blocks into one of OpenAI's three shapes.
#[derive(Clone, Debug, PartialEq)]
pub enum OpenAiMsg {
    Text(String, String),
    AssistantWithTools(String, Vec<Value>),
    ToolResults(Vec<OpenAiToolResult>),
}


pub fn openai_content(role: &str, mut blocks: Vec<ContentBlock>) -> OpenAiMsg {

    if blocks.is_empty() == false && all_tool_results(&blocks) {
        let mut results: Vec<OpenAiToolResult> = vec![];
        for b in &blocks {
            match b {
                ContentBlock::ToolResult { tool_use_id, content, is_error } => results.push(OpenAiToolResult { tool_call_id: tool_use_id.to_string(), content: content.to_string() }),
                ContentBlock::Text { text } => {},
                ContentBlock::ToolUse { id, name, input } => {},
            };
        }
        return OpenAiMsg::ToolResults(results);
    }


    if has_tool_use(&blocks) {
        let mut text_parts: Vec<String> = vec![];
        let mut tool_calls: Vec<Value> = vec![];
        for b in &blocks {
            match b {
                ContentBlock::Text { text } => text_parts.push(text.clone()),
                ContentBlock::ToolUse { id, name, input } => tool_calls.push(tool_call_obj(id.as_str(), name.as_str(), input.clone())),
                ContentBlock::ToolResult { tool_use_id, content, is_error } => {},
            };
        }
        let text = text_parts.join("");
        return OpenAiMsg::AssistantWithTools(text, tool_calls);
    }


    let mut text_parts: Vec<String> = vec![];
    for b in &blocks {
        match b {
            ContentBlock::Text { text } => text_parts.push(text.clone()),
            ContentBlock::ToolUse { id, name, input } => {},
            ContentBlock::ToolResult { tool_use_id, content, is_error } => {},
        };
    }
    let content = text_parts.join("");
    return OpenAiMsg::Text(role.to_string(), content);
}

pub fn tool_to_openai(t: &ToolDefinition) -> Value {
    let mut func = serde_json::Map::new();
    func.insert("name".to_string(), Value::String(t.name.clone()));
    func.insert("description".to_string(), Value::String(t.description.clone()));
    func.insert("parameters".to_string(), t.parameters.clone());
    let mut outer = serde_json::Map::new();
    outer.insert("type".to_string(), Value::String("function".to_string()));
    outer.insert("function".to_string(), Value::Object(func));
    return Value::Object(outer);
}

pub fn parse_openai_tool_calls(arr: Vec<Value>) -> Vec<ToolCall> {
    let mut out: Vec<ToolCall> = vec![];
    for tc in &arr {
        let fn_obj = a2r_std::json::get(&tc, "function");
        let name = a2r_std::json::get_str(&fn_obj, "name");
        if name.is_empty() {
            continue;
        }
        let args_str = a2r_std::json::get_str(&fn_obj, "arguments");
        let input = a2r_std::json::parse(args_str.as_str());
        let id = a2r_std::json::get_str(&tc, "id");
        out.push(ToolCall { id: id, name: name, input: input });
    }
    return out;
}

/// Translate our content blocks into the OpenAI message shape, given the
/// message's `role`. Tool-use always yields an assistant message; tool results
/// always split into one or more role:"tool" messages; everything else is a
/// plain text message in the caller's role.
/// Translate our ToolDefinition to OpenAI's tool object.
/// Parse OpenAI's `tool_calls` array into our ToolCall list.
/// True if every block is a ToolResult.
fn all_tool_results(blocks: &Vec<ContentBlock>) -> bool {
    for b in blocks {
        match b {
            ContentBlock::ToolResult { tool_use_id, content, is_error } => {},
            ContentBlock::Text { text } => return false,
            ContentBlock::ToolUse { id, name, input } => return false,
        };
    }
    return true;
}

/// True if any block is a ToolUse.
fn has_tool_use(blocks: &Vec<ContentBlock>) -> bool {
    for b in blocks {
        match b {
            ContentBlock::ToolUse { id, name, input } => return true,
            ContentBlock::Text { text } => {},
            ContentBlock::ToolResult { tool_use_id, content, is_error } => {},
        };
    }
    return false;
}

/// Build one OpenAI tool_call object: {id, type:"function", function:{name, arguments}}.
/// (Replaces `serde_json::json!({...})` — hand-built Map+Value, a2r-native.)
fn tool_call_obj(id: &str, name: &str, input: Value) -> Value {
    let mut fn_obj = serde_json::Map::new();
    fn_obj.insert("name".to_string(), Value::String(name.to_string()));
    fn_obj.insert("arguments".to_string(), Value::String(a2r_std::json::to_string(&input)));
    let mut outer = serde_json::Map::new();
    outer.insert("id".to_string(), Value::String(id.to_string()));
    outer.insert("type".to_string(), Value::String("function".to_string()));
    outer.insert("function".to_string(), Value::Object(fn_obj));
    return Value::Object(outer);
}
