// Auto-generated by a2r transpiler

use std::sync::Arc;
use tokio_util::sync::CancellationToken;
use crate::ai_config::{CompletionRequest, CompletionResponse};
use crate::error::{LlmError};
use crate::openai::{OpenAiProvider};
use crate::provider::{AiProvider, StreamDelta};
/// Ollama provider — delegates everything to an OpenAiProvider pointed at the
/// Ollama OpenAI-compatible endpoint.
#[allow(dead_code)]
pub struct OllamaProvider {
    pub inner: OpenAiProvider,
}

#[async_trait::async_trait]
impl AiProvider for OllamaProvider {
    fn name(&self) -> String {
        return self.inner.name();
    }
    fn models(&self) -> Vec<String> {
        return self.inner.models();
    }
    async fn complete(&self, req: &CompletionRequest) -> Result<CompletionResponse, LlmError> {
        return self.inner.complete(&req).await;
    }
    async fn complete_stream(&self, req: &CompletionRequest, on_delta: Arc<dyn Fn(StreamDelta) + Send + Sync>, cancel: CancellationToken) -> Result<CompletionResponse, LlmError> {
        return self.inner.complete_stream(&req, on_delta, cancel).await;
    }
}

impl OllamaProvider {
    pub fn new(name: String, base_url: String, models: Vec<String>) -> OllamaProvider {
        return OllamaProvider { inner: OpenAiProvider::new(name, base_url, "no-key-needed".to_string(), models) };
    }
}
