// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

use std::sync::Arc;
use tokio_util::sync::CancellationToken;
use serde_json;
use serde_json::Value;

use crate::ai_config::{CompletionRequest, CompletionResponse, ToolCall, Usage};
use crate::error::{LlmError};
use crate::sse::SseParser;
use crate::format::{openai_content, OpenAiMsg, parse_openai_tool_calls, tool_to_openai};
use crate::provider::{AiProvider, StreamDelta};
/// OpenAI-compatible provider (works with OpenAI, Zhipu GLM, Moonshot, etc.).
/// 
/// Auto port of crates/auto-ai-daemon/src/provider/openai.rs (non-streaming
/// parts). Uses the standard OpenAI `/v1/chat/completions` API format.
/// 
/// HTTP NOTE: the Rust original holds a `reqwest::Client` and uses
/// `client.post().json().send().await`. Auto's port uses the global `http`
/// module's `http.request("POST", url)...send_async()` chain instead — the
/// project's established pattern (auto-ai-client/src/lib.at:84-113). The
/// `reqwest::Client` field is dropped (http is internally connection-pooled).
/// 
/// STREAM NOTE: `complete_stream` (which uses `tokio::select!` for cancel +
/// idle-timeout racing) is NOT transpiled — it lives in provider_glue.rs as
/// hand-written Rust (select! has no .at syntax). This type's complete_stream
/// method delegates to `crate::provider_glue::openai_complete_stream`.
/// 
/// JSON NOTE: `serde_json::json!({...})` is a macro a2r can't emit, so
/// build_body uses `serde_json.Map.new()` + `.insert()` + `Value.Object(...)`
/// construction (same pattern as format.at / server.at). Response parsing uses
/// a2r-std's `json.get / get_at / get_str / as_int` (auto-ai-client/lib.at mode).
/// One OpenAI-compatible provider instance. `client` is dropped vs rust-ref —
/// we use the global `http` module instead of a per-instance reqwest::Client.
#[allow(dead_code)]
pub struct OpenAiProvider {
    pub name: String,
    pub base_url: String,
    pub api_key: String,
    pub models_list: Vec<String>,
}

#[async_trait::async_trait]
impl AiProvider for OpenAiProvider {
    fn name(&self) -> String {
        return self.name.clone();
    }
    fn models(&self) -> Vec<String> {
        return self.models_list.clone();
    }
    async fn complete(&self, req: &CompletionRequest) -> Result<CompletionResponse, LlmError> {
        let body = self.build_body(req.clone());
        let url = self.url();


        let resp = a2r_std::http::request("POST", url.as_str()).header("Authorization", &format!("Bearer {}", self.api_key)).header("Content-Type", "application/json").body(a2r_std::json::to_string(&body)).send_async().await;

        let status = resp.status_code();
        if status < 200 || status >= 300 {
            let text = bytes_to_str(resp.body_bytes());
            return Err(LlmError::from_upstream_status(reqwest::StatusCode::from_u16(status as u16).unwrap_or(reqwest::StatusCode::BAD_GATEWAY), &text));
        }

        let text = bytes_to_str(resp.body_bytes());
        let v = a2r_std::json::parse(text.as_str());


        let choices = a2r_std::json::get(&v, "choices");
        let choice = a2r_std::json::get_at(&choices, 0 as usize);
        let message = a2r_std::json::get(&choice, "message");
        let content = a2r_std::json::get_str(&message, "content");


        let raw_tool_calls = a2r_std::json::get(&message, "tool_calls");
        let mut tool_calls: Vec<ToolCall> = vec![];
        if raw_tool_calls.is_null() == false {
            tool_calls = parse_openai_tool_calls(a2r_std::json::as_array(&raw_tool_calls));
        }


        let stop_reason = opt_str_field(choice.clone(), "finish_reason");


        let usage = parse_usage_openai(v.clone());


        let model_field = a2r_std::json::get_str(&v, "model");
        let model = match model_field.is_empty() { true => req.model.clone(), false => model_field, };

        return Ok(CompletionResponse { content: content, tool_calls: tool_calls, stop_reason: stop_reason, usage: usage, model: model, error: None });
    }
    async fn complete_stream(&self, req: &CompletionRequest, on_delta: Arc<dyn Fn(StreamDelta) + Send + Sync>, cancel: CancellationToken) -> Result<CompletionResponse, LlmError> {
        return crate::provider_glue::openai_complete_stream(self, req, on_delta, cancel).await;
    }
}

impl OpenAiProvider {
    pub fn new(name: String, base_url: String, api_key: String, models: Vec<String>) -> OpenAiProvider {
        return OpenAiProvider { name: name.to_string(), base_url: base_url.to_string(), api_key: api_key.to_string(), models_list: models };
    }
    pub fn url(&self) -> String {
        let base = self.base_url.trim_end_matches("/");
        return format!("{}/chat/completions", base);
    }
    pub fn build_body(&self, req: CompletionRequest) -> Value {

        let mut messages: Vec<Value> = vec![];
        for m in &req.messages {
            match openai_content(m.role.as_str(), m.content.clone()) {
                OpenAiMsg::Text(role, content) => {
                    let mut obj = serde_json::Map::new();
                    obj.insert("role".to_string(), Value::String(role));
                    obj.insert("content".to_string(), Value::String(content.to_string()));
                    messages.push(Value::Object(obj));
                },
                OpenAiMsg::AssistantWithTools(text, tool_calls) => {
                    let mut obj = serde_json::Map::new();
                    obj.insert("role".to_string(), Value::String("assistant".to_string()));
                    if text.is_empty() == false {
                        obj.insert("content".to_string(), Value::String(text));
                    }
                    obj.insert("tool_calls".to_string(), Value::Array(tool_calls));
                    messages.push(Value::Object(obj));
                },
                OpenAiMsg::ToolResults(results) => {
                    for r in &results {
                        let mut obj = serde_json::Map::new();
                        obj.insert("role".to_string(), Value::String("tool".to_string()));
                        obj.insert("tool_call_id".to_string(), Value::String(r.tool_call_id.to_string()));
                        obj.insert("content".to_string(), Value::String(r.content.to_string()));
                        messages.push(Value::Object(obj));
                    }
                },
            };
        }

        let mut body = serde_json::Map::new();
        body.insert("model".to_string(), Value::String(req.model));
        body.insert("stream".to_string(), Value::Bool(false));



        if req.system_prompt.is_some() {
            let sys = req.system_prompt.unwrap();
            let mut all_msgs: Vec<Value> = vec![];
            let mut sys_obj = serde_json::Map::new();
            sys_obj.insert("role".to_string(), Value::String("system".to_string()));
            sys_obj.insert("content".to_string(), Value::String(sys));
            all_msgs.push(Value::Object(sys_obj));
            for m in &messages {
                all_msgs.push(m.clone());
            }
            body.insert("messages".to_string(), Value::Array(all_msgs));
        } else {
            body.insert("messages".to_string(), Value::Array(messages));
        }



        if req.tools.is_empty() == false {
            let mut tools_arr: Vec<Value> = vec![];
            for t in &req.tools {
                tools_arr.push(tool_to_openai(t));
            }
            body.insert("tools".to_string(), Value::Array(tools_arr));
        }




        if req.max_tokens.is_some() {
            let n = req.max_tokens.unwrap();
            body.insert("max_tokens".to_string(), Value::Number(serde_json::Number::from(n)));
        }
        if req.temperature.is_some() {
            let t = req.temperature.unwrap();
            body.insert("temperature".to_string(), Value::Number(serde_json::Number::from_f64(t).unwrap_or(serde_json::Number::from(0))));
        }

        return Value::Object(body);
    }
}

/// Non-streaming completion. Builds the OpenAI request body, POSTs it,
/// parses the JSON response into a canonical CompletionResponse.
/// Streaming completion. Delegates to provider_glue (tokio::select! loop —
/// no .at syntax). See openai.rs:174-374 for the rust-ref original.
/// Construct an OpenAI-compatible provider.
/// The `/chat/completions` endpoint URL (base_url normalized, no trailing /).
/// Build the OpenAI `/v1/chat/completions` request body from a canonical
/// CompletionRequest. (Replaces rust-ref's `serde_json::json!({...})` with
/// hand-built serde_json::Map + Value — a2r-native, format.at pattern.)
/// Decode response body bytes to a UTF-8 string (lossy). Mirrors
/// auto-ai-client/lib.at:321.
fn bytes_to_str(bytes: Vec<u8>) -> String {
    return a2r_std::str::from_bytes(bytes);
}

/// An optional string field, or None if absent/empty.
fn opt_str_field(value: Value, key: &str) -> Option<String> {
    let s = a2r_std::json::get_str(&value, key);
    if s.is_empty() {
        return None;
    }
    return Some(s);
}

/// Parse the `usage` object (OpenAI shape: prompt_tokens/completion_tokens),
/// or None if absent.
fn parse_usage_openai(value: Value) -> Option<Usage> {
    let u = a2r_std::json::get(&value, "usage");
    if u.is_null() {
        return None;
    }
    return Some(Usage { input_tokens: a2r_std::json::as_int(&a2r_std::json::get(&u, "prompt_tokens")) as u32, output_tokens: a2r_std::json::as_int(&a2r_std::json::get(&u, "completion_tokens")) as u32 });
}
