// Auto-generated by a2r transpiler

use std::collections::HashMap;
use std::sync::Arc;
use std::time::Duration;
use tokio::sync::Semaphore;
use tokio::sync::OwnedSemaphorePermit;
use tokio::time::timeout;
use crate::ai_config::{DaemonConfig};
/// Concurrency management — per-provider/per-model Semaphore pools.
/// 
/// Auto port of crates/auto-ai-daemon/src/pool.rs (production code only; the
/// #[cfg(test)] block stays in rust-ref — a2r .at doesn't transpile tests).
/// 
/// Each provider has a `Semaphore(max_concurrency)`. Acquiring a permit blocks
/// until a slot is free. Guards release on drop (the OwnedSemaphorePermit is
/// returned to the caller, who owns its lifetime).
/// 
/// ITER NOTE: .at's Map has no iteration API, so `status()` walks a
/// hand-maintained `names` list (same convention as ai-config's provider_names
/// and tracker's names). `from_config` materializes keys via
/// `.keys().cloned().collect()` (a verified-clean a2r pattern).
/// 
/// TYPE NOTE: links the rust-ref ai-config (DaemonConfig.providers is a
/// HashMap<String, ProviderConfig>). tokio::sync::Semaphore / Arc /
/// OwnedSemaphorePermit bridge via use.rust (cargo runtime).
/// Manages concurrency limits per provider. Each provider has a
/// Semaphore(max_concurrency). Acquiring a permit blocks until a slot is free.
#[derive(Debug)]
pub struct ConcurrencyManager {
    pub pools: HashMap<String, Arc<Semaphore>>,
    pub limits: HashMap<String, usize>,
    pub names: Vec<String>,
}

impl ConcurrencyManager {
    pub fn from_config(&self, config: DaemonConfig) -> ConcurrencyManager {
        let mut pools = HashMap::new();
        let mut limits = HashMap::new();
        let mut names: Vec<String> = vec![];
        for name in config.providers.keys().cloned().collect::<Vec<String>>() {
            match config.providers.get(name.as_str()) {
                Some(provider) => {
                    

                    let limit = provider.max_concurrency.unwrap_or(4);
                    pools.insert(name.clone(), Arc::new(Semaphore::new(limit)));
                    limits.insert(name.clone(), limit.clone());
                    names.push(name.clone());
                },
                None => {},
            };
        }
        return ConcurrencyManager { pools: pools, limits: limits, names: names };
    }
    pub async fn acquire(&self, provider: &str) -> Option<OwnedSemaphorePermit> {
        match self.pools.get(provider) {
            Some(sem) => {
                let owned = sem.clone();
                match owned.acquire_owned().await {
                    Ok(permit) => return Some(permit),
                    Err(_) => return None,
                };
                return None;
            },
            None => return None,
        };
        return None;
    }
    pub async fn acquire_with_timeout(&self, provider: &str, t: Duration) -> Option<OwnedSemaphorePermit> {
        match self.pools.get(provider) {
            Some(sem) => {
                let owned = sem.clone();
                match timeout(t, owned.acquire_owned()).await {
                    Ok(result) => {
                        match result {
                            Ok(permit) => return Some(permit),
                            Err(_) => return None,
                        };
                        return None;
                    },
                    Err(_) => {
                        


                        return None;
                    },
                };
                return None;
            },
            None => return None,
        };
        return None;
    }
    pub fn in_use(&self, provider: &str) -> Option<usize> {
        match self.pools.get(provider) {
            Some(sem) => {
                let limit = self.limits.get(provider).copied().unwrap_or(0);
                return Some(limit - sem.available_permits());
            },
            None => return None,
        };
        return None;
    }
    pub fn limit(&self, provider: &str) -> usize {
        return self.limits.get(provider).copied().unwrap_or(0);
    }
    pub fn status(&self) -> Vec<(String, usize, usize)> {
        let mut out: Vec<(String, usize, usize)> = vec![];
        for name in &self.names {
            match self.pools.get(name.as_str()) {
                Some(sem) => {
                    let max = self.limits.get(name.as_str()).copied().unwrap_or(0);
                    out.push((name.clone(), sem.available_permits(), max));
                },
                None => {},
            };
        }
        return out;
    }
}
