// Auto-generated by a2r transpiler

use std::collections::HashMap;
use std::sync::Arc;
use async_trait;
use tokio_util::sync::CancellationToken;
use crate::ai_config::{CompletionRequest, CompletionResponse, DaemonConfig, ProviderConfig};
use crate::error::{LlmError};
/// Provider trait + registry + concrete provider implementations.
/// 
/// Auto port of crates/auto-ai-daemon/src/provider/mod.rs (the trait, the
/// StreamDelta enum, and the ProviderRegistry). The concrete providers
/// (openai/anthropic/ollama) are Phase 4; their construction lives in the
/// hand-written provider_glue.rs until then (mirrors tier_router_glue.rs).
/// 
/// Providers translate canonical CompletionRequests to their wire format and
/// parse responses back into canonical CompletionResponses.
/// 
/// TRAIT NOTE: the agent's tool.at already proved a2r renders `pub spec X:
/// Send + Sync { ... }` → `#[async_trait] pub trait X: Send + Sync { ... }`,
/// and `~Result<...>` method signatures → `async fn ... -> Result<...>`. The
/// `Arc<dyn Fn(StreamDelta) + Send + Sync>` callback param is a verified a2r
/// pattern (Plan 397 golden 009).
/// 
/// ITER NOTE: .at's Map has no iteration API, so provider_names() walks a
/// hand-maintained `names` list (same convention as pool/tracker).
/// One streamed chunk from a provider. `Text` is the model's visible answer;
/// `Reasoning` is the chain-of-thought (emitted by reasoning-capable models
/// *before* the answer). Consumers route the two to separate UI regions.
#[derive(Clone, Debug)]
pub enum StreamDelta {
    Text(String),
    Reasoning(String),
}


#[async_trait::async_trait]
pub trait AiProvider: Send + Sync {
    fn name(&self) -> String;
    fn models(&self) -> Vec<String>;
    async fn complete(&self, req: &CompletionRequest) -> Result<CompletionResponse, LlmError>;
    async fn complete_stream(&self, req: &CompletionRequest, on_delta: Arc<dyn Fn(StreamDelta) + Send + Sync>, cancel: CancellationToken) -> Result<CompletionResponse, LlmError>;
}


/// Trait that every LLM provider implements.
/// Provider name (e.g. "zhipu", "anthropic").
/// Available models.
/// Non-streaming completion.
/// Streaming completion. Calls `on_delta` for each chunk (visible text or
/// reasoning) so the caller can route them independently.
/// 
/// `cancel` lets the caller (e.g. SSE client disconnect) abort the upstream
/// fetch early, so a dropped connection doesn't keep pulling tokens (and
/// spending quota). Honored at each SSE chunk boundary.
/// Registry of configured providers.
#[allow(dead_code)]
pub struct ProviderRegistry {
    pub providers: HashMap<String, Arc<dyn AiProvider>>,
    pub default_name: String,
    pub names: Vec<String>,
}

impl ProviderRegistry {
    pub fn from_daemon_config(config: &DaemonConfig) -> Result<ProviderRegistry, LlmError> {
        return crate::provider_glue::build_registry(&config);
    }
    pub fn default_provider(&self) -> Result<Arc<dyn AiProvider>, LlmError> {
        match self.providers.get(&self.default_name.clone()) {
            Some(p) => return Ok(p.clone()),
            None => return Err(LlmError::NoProvider),
        };
        return Err(LlmError::NoProvider);
    }
    pub fn get(&self, name: &str) -> Option<Arc<dyn AiProvider>> {
        match self.providers.get(name) {
            Some(p) => return Some(p.clone()),
            None => return None,
        };
        return None;
    }
    pub fn provider_names(&self) -> Vec<String> {
        return self.names.clone();
    }
    pub fn models_for(&self, provider: &str) -> Vec<String> {
        match self.providers.get(provider) {
            Some(p) => return p.models(),
            None => return vec![],
        };
        return vec![];
    }
}
