// Auto-generated by a2r transpiler

use std::collections::HashMap;
use std::sync::Arc;
use async_trait;
use tokio_util::sync::CancellationToken;
use crate::provider_glue;
use crate::ai_config::{CompletionRequest, CompletionResponse, DaemonConfig, ProviderConfig};
use crate::error::{LlmError};
/// Provider trait + registry + concrete provider implementations.
/// 
/// Auto port of crates/auto-ai-daemon/src/provider/mod.rs (the trait, the
/// StreamDelta enum, and the ProviderRegistry). The concrete providers
/// (openai/anthropic/ollama) are Phase 4; their construction lives in the
/// hand-written provider_glue.rs until then (mirrors tier_router_glue.rs).
/// 
/// Providers translate canonical CompletionRequests to their wire format and
/// parse responses back into canonical CompletionResponses.
/// 
/// TRAIT NOTE: the agent's tool.at already proved a2r renders `pub spec X:
/// Send + Sync { ... }` → `#[async_trait] pub trait X: Send + Sync { ... }`,
/// and `~Result<...>` method signatures → `async fn ... -> Result<...>`. The
/// `Arc<dyn Fn(StreamDelta) + Send + Sync>` callback param is a verified a2r
/// pattern (Plan 397 golden 009).
/// 
/// ITER NOTE: .at's Map has no iteration API, so provider_names() walks a
/// hand-maintained `names` list (same convention as pool/tracker).
/// One streamed chunk from a provider. `Text` is the model's visible answer;
/// `Reasoning` is the chain-of-thought (emitted by reasoning-capable models
/// *before* the answer). Consumers route the two to separate UI regions.
#[derive(Clone, Debug)]
pub enum StreamDelta {
    Text(String),
    Reasoning(String),
}


/// PLAN-064: thinking effort level, parsed from
/// [`ai_config::CompletionRequest::thinking_level`]. The daemon maps levels
/// to per-dialect wire params (anthropic `thinking` block, openai
/// `reasoning_effort`); unknown strings parse to None — callers skip
/// injection rather than failing the request.
#[derive(Clone, Debug)]
pub enum ThinkingLevel {
    Off = 0,
    Low = 1,
    High = 2,
    Max = 3,
}

impl std::fmt::Display for ThinkingLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            ThinkingLevel::Off => write!(f, "Off"),
            ThinkingLevel::Low => write!(f, "Low"),
            ThinkingLevel::High => write!(f, "High"),
            ThinkingLevel::Max => write!(f, "Max"),
        }
    }
}
impl ThinkingLevel {
    pub fn from_id(id: &str) -> Self {
        match id {
            "Off" | "off" => ThinkingLevel::Off,
            "Low" | "low" => ThinkingLevel::Low,
            "High" | "high" => ThinkingLevel::High,
            "Max" | "max" => ThinkingLevel::Max,
            _ => ThinkingLevel::Off
        }
    }
}

impl ThinkingLevel {
    pub fn budget_tokens(&self) -> usize {
        match self {
            ThinkingLevel::Off => return 0 as usize,
            ThinkingLevel::Low => return 2048 as usize,
            ThinkingLevel::High => return 8192 as usize,
            ThinkingLevel::Max => return 32768 as usize,
        }
    }
}

pub fn parse_thinking_level(raw: &str) -> Option<ThinkingLevel> {
    let lower = raw.trim().to_string().to_ascii_lowercase();
    match lower.as_str() {
        "off" => Some(ThinkingLevel::Off),
        "low" => Some(ThinkingLevel::Low),
        "high" => Some(ThinkingLevel::High),
        "max" => Some(ThinkingLevel::Max),
        _ => None,
    }
}

#[async_trait::async_trait]
pub trait AiProvider: Send + Sync {
    fn name(&self) -> String;
    fn models(&self) -> Vec<String>;
    async fn complete(&self, req: &CompletionRequest) -> Result<CompletionResponse, LlmError>;
    async fn complete_stream(&self, req: &CompletionRequest, on_delta: Arc<dyn Fn(StreamDelta) + Send + Sync>, cancel: CancellationToken) -> Result<CompletionResponse, LlmError>;
}


/// Thinking-token budget for the anthropic-compat `thinking` block.
/// Presets are ours — GLM official's exact 低/高/最高 mapping is
/// unpublished; tune here, wire contract unchanged (PLAN-064).
/// Returns usize (rust-ref: u32 + `as usize` at the call site; usize here
/// matches ai-config's max_tokens without a cast).
/// Parse the wire string (`"off"` | `"low"` | `"high"` | `"max"`,
/// case-insensitive, trimmed). `None` = unrecognized.
/// Trait that every LLM provider implements.
/// Provider name (e.g. "zhipu", "anthropic").
/// Available models.
/// Non-streaming completion.
/// Streaming completion. Calls `on_delta` for each chunk (visible text or
/// reasoning) so the caller can route them independently.
/// 
/// `cancel` lets the caller (e.g. SSE client disconnect) abort the upstream
/// fetch early, so a dropped connection doesn't keep pulling tokens (and
/// spending quota). Honored at each SSE chunk boundary.
/// Registry of configured providers.
#[allow(dead_code)]
pub struct ProviderRegistry {
    pub providers: HashMap<String, Arc<dyn AiProvider>>,
    pub default_name: String,
    pub names: Vec<String>,
}

impl ProviderRegistry {
    pub fn from_daemon_config(config: &DaemonConfig) -> Result<ProviderRegistry, LlmError> {
        return provider_glue::build_registry(&config);
    }
    pub fn from_entries(entries: Vec<(String, Arc<dyn AiProvider>)>, default_name: &str) -> ProviderRegistry {
        let mut providers = HashMap::new();
        let mut names: Vec<String> = vec![];
        for entry in &entries {
            let name = entry.0.clone();
            let provider = entry.1.clone();
            providers.insert(name.clone(), provider.clone());
            names.push(name.clone());
        }
        return ProviderRegistry { providers: providers, default_name: default_name.to_string(), names: names };
    }
    pub fn default_provider(&self) -> Result<Arc<dyn AiProvider>, LlmError> {
        match self.providers.get(&self.default_name.clone()) {
            Some(p) => return Ok(p.clone()),
            None => return Err(LlmError::NoProvider),
        };
        return Err(LlmError::NoProvider);
    }
    pub fn get(&self, name: &str) -> Option<Arc<dyn AiProvider>> {
        match self.providers.get(name) {
            Some(p) => return Some(p.clone()),
            None => return None,
        };
        return None;
    }
    pub fn provider_names(&self) -> Vec<String> {
        return self.names.clone();
    }
    pub fn models_for(&self, provider: &str) -> Vec<String> {
        match self.providers.get(provider) {
            Some(p) => return p.models(),
            None => return vec![],
        };
        return vec![];
    }
}
