// Auto-generated by a2r transpiler

use std::sync::Arc;
use std::time::Duration;
use parking_lot::{Mutex, RwLock, RwLockReadGuard};
use axum::extract::State;
use axum::http::{HeaderMap, StatusCode};
use axum::response::{IntoResponse, Response};
use axum::Json;
use serde_json;
use serde_json::Value;

use crate::ai_config::{DaemonConfig, CompletionRequest, CompletionResponse, ModelTier};
use crate::pool::{ConcurrencyManager};
use crate::provider::{ProviderRegistry, AiProvider};
use crate::tracker::{UsageTracker};
use crate::tier_router::{TierRouter};
/// HTTP server (axum) — the daemon's public API. Auto-transpiled.
/// 
/// Auto port of crates/auto-ai-daemon/src/server.rs. Endpoints:
/// - `POST /v1/chat/completions` — receive a canonical CompletionRequest,
/// resolve a provider, call upstream, return a canonical CompletionResponse.
/// - `GET /v1/status` / `/v1/models` / `/v1/usage` — observability.
/// 
/// ARCHITECTURE: AppState (shared state) + router() + handlers. The router's
/// framework glue (ServeDir for frontend-dist, CorsLayer, CARGO_MANIFEST_DIR,
/// route mounting) lives in the hand-written server_glue.rs::build_router —
/// those constructs can't be expressed in .at (compile-time macro +
/// tower_http layering). This module owns AppState + the handlers it can
/// express; server_glue owns route wiring + the bits that can't be transpiled.
/// 
/// EXTRACTOR NOTE: golden 016_extractor_destructure proves `State(s):
/// State<Arc<T>>` and `Json(d): Json<T>` render correctly in param position.
/// RETURN NOTE: golden 015_impl_trait_return proves `~IntoResponse` →
/// `async fn -> impl IntoResponse`.
/// 
/// JSON NOTE: rust-ref uses the `json!` macro heavily; a2r can't emit macros.
/// All json!({...}) calls become `serde_json.Map.new()` + `.insert()` +
/// `Value.Object(...)` construction (same pattern as format.at). Integers need
/// `serde_json.Number.from(n)` wrapping (json! does this implicitly; we do it
/// by hand) — see retranspile.sh for the Value.Number → Value::Number fixup.
/// 
/// LOG NOTE: rust-ref's `tracing::info!`/`warn!` become println!/eprintln!
/// (a2r can't emit macros — Phase 0 spike #4).
/// Shared application state, wrapped in `Arc` and passed to handlers via axum's
/// `State` extractor. Mirrors rust-ref server.rs:24-31.
#[allow(dead_code)]
pub struct AppState {
    pub config: Arc<RwLock<DaemonConfig>>,
    pub registry: ProviderRegistry,
    pub pool: ConcurrencyManager,
    pub tracker: UsageTracker,
    pub current_model: Mutex<String>,
    pub tier_router: TierRouter,
}

impl AppState {
    pub fn new(config: DaemonConfig) -> AppState {
        let registry = ProviderRegistry::from_daemon_config(&config).unwrap();
        let pool = ConcurrencyManager::from_config(&config);
        let current_model = config.default_model.clone();
        let tier_router = TierRouter::from_config(&config);
        return AppState { config: Arc::new(RwLock::new(config)), registry: registry, pool: pool, tracker: UsageTracker::new(), current_model: Mutex::new(current_model), tier_router: tier_router };
    }
    pub fn cfg(&self) -> RwLockReadGuard<DaemonConfig> {
        return self.config.read();
    }
}

pub fn router(state: Arc<AppState>) -> axum::Router {
    return crate::server_glue::build_router(state);
}

pub async fn status(State(state): State<Arc<AppState>>) -> impl IntoResponse {



    let mut pools: Vec<Value> = vec![];
    for entry in state.pool.status() {
        let name = entry.0;
        let available = entry.1;
        let max = entry.2;
        let mut m = serde_json::Map::new();
        m.insert("provider".to_string(), Value::String(name));
        m.insert("available_permits".to_string(), Value::Number(serde_json::Number::from(available)));
        m.insert("max_concurrency".to_string(), Value::Number(serde_json::Number::from(max)));
        m.insert("in_use".to_string(), Value::Number(serde_json::Number::from(max - available)));
        pools.push(Value::Object(m));
    }

    let current_model = state.current_model.lock().clone();
    let mut root = serde_json::Map::new();
    root.insert("status".to_string(), Value::String("running".to_string()));
    root.insert("current_model".to_string(), Value::String(current_model));
    root.insert("pools".to_string(), Value::Array(pools));
    return Json(Value::Object(root));
}

pub async fn models(State(state): State<Arc<AppState>>) -> impl IntoResponse {
    let cfg = state.cfg();
    let mut out: Vec<Value> = vec![];
    for (name, models) in crate::server_glue::config_provider_models(&cfg) {
        for m in &models {
            let mut entry = serde_json::Map::new();
            entry.insert("provider".to_string(), Value::String(name.clone()));
            entry.insert("model".to_string(), Value::String(m.id.to_string()));
            


            if m.context_window.is_some() {
                entry.insert("context_window".to_string(), Value::Number(serde_json::Number::from(m.context_window.clone().unwrap())));
            }
            if m.max_output_tokens.is_some() {
                entry.insert("max_output_tokens".to_string(), Value::Number(serde_json::Number::from(m.max_output_tokens.clone().unwrap())));
            }
            if m.cost_per_mtok.is_some() {
                let c = m.cost_per_mtok.clone().unwrap();
                let mut cost = serde_json::Map::new();
                cost.insert("input".to_string(), Value::Number(serde_json::Number::from(c.input)));
                cost.insert("output".to_string(), Value::Number(serde_json::Number::from(c.output)));
                cost.insert("cache_read".to_string(), Value::Number(serde_json::Number::from(c.cache_read)));
                entry.insert("cost_per_mtok".to_string(), Value::Object(cost));
            }
            if m.capabilities.is_some() {
                let c = m.capabilities.clone().unwrap();
                let mut caps = serde_json::Map::new();
                caps.insert("vision".to_string(), Value::Bool(c.vision));
                caps.insert("thinking".to_string(), Value::Bool(c.thinking));
                entry.insert("capabilities".to_string(), Value::Object(caps));
            }
            out.push(Value::Object(entry));
        }
    }
    let mut root = serde_json::Map::new();
    root.insert("models".to_string(), Value::Array(out));
    return Json(Value::Object(root));
}

pub async fn usage(State(state): State<Arc<AppState>>) -> impl IntoResponse {
    let mut apps: Vec<Value> = vec![];
    for (name, u) in state.tracker.all() {
        let mut entry = serde_json::Map::new();
        entry.insert("app".to_string(), Value::String(name.clone()));
        entry.insert("input_tokens".to_string(), Value::Number(serde_json::Number::from(u.total_input_tokens)));
        entry.insert("output_tokens".to_string(), Value::Number(serde_json::Number::from(u.total_output_tokens)));
        entry.insert("total_tokens".to_string(), Value::Number(serde_json::Number::from(u.total_tokens())));
        entry.insert("requests".to_string(), Value::Number(serde_json::Number::from(u.request_count)));
        
        entry.insert("cache_read_tokens".to_string(), Value::Number(serde_json::Number::from(u.total_cache_read_tokens)));
        entry.insert("cache_write_tokens".to_string(), Value::Number(serde_json::Number::from(u.total_cache_write_tokens)));
        apps.push(Value::Object(entry));
    }
    let mut root = serde_json::Map::new();
    root.insert("usage".to_string(), Value::Array(apps));
    return Json(Value::Object(root));
}

/// Construct from a loaded config: builds the provider registry, concurrency
/// pool, and tier router. The registry build currently returns NoProvider
/// (provider_glue Phase-4 stub); router/handlers still compile and the
/// status endpoint works — Phase 4 wires real providers.
/// Read-locked access to the config (for GET handlers). The guard type is
/// imported via use.rust (a2r renders the bare name cleanly).
/// Build the axum Router. Delegates the framework-glue wiring (ServeDir,
/// CorsLayer, CARGO_MANIFEST_DIR, route mounting) to server_glue::build_router
/// — those constructs can't be expressed in .at. This fn is the .at-visible
/// entry point the bin (main.at) calls.
/// `GET /v1/status` — daemon liveness + per-provider pool snapshot.
/// `GET /v1/models` — all (provider, model) pairs the daemon can serve.
/// Uses server_glue::config_provider_models because .at's Map has no iteration
/// API (DaemonConfig.providers is a HashMap).
/// `GET /v1/usage` — per-app token accounting.
/// Resolve a `tier:<name>` token to a concrete model id via the default
/// provider's model list (legacy fallback when TierRouter has no candidates).
/// Returns None if the tier is unknown or the default provider has no matching
/// model. (Mirrors rust-ref server.rs:419-425.)
fn resolve_tier_model(token: &str, config: &DaemonConfig) -> Option<String> {

    if token.starts_with("tier:") == false {
        return None;
    }
    let tier_name_raw = token[5..].to_string();
    let tier_name = tier_name_raw.trim().to_string().to_ascii_lowercase();
    match ai_config::ModelTier::parse_name(tier_name.as_str()) {
        Some(tier) => {
            match config.providers.get(&config.default_provider) {
                Some(provider) => {
                    let models = provider.models.clone();
                    match ai_config::resolve_model_id(tier, &models) {
                        Some(m) => return Some(m),
                        None => return None,
                    };
                    return None;
                },
                None => return None,
            };
            return None;
        },
        None => return None,
    };
    return None;
}

pub async fn chat_completions(State(state): State<Arc<AppState>>, headers: HeaderMap, Json(req): Json<CompletionRequest>) -> impl IntoResponse {

    let app_name = header_or(headers.clone(), "x-app-name", "unknown");

    let mut req = req;
    let is_tier_request = req.model.starts_with("tier:");


    let mut candidates: Vec<(String, String)> = vec![];
    if is_tier_request {
        let tier_name_raw = req.model[5..].to_string();
        let tier_name = tier_name_raw.trim().to_string().to_ascii_lowercase();
        match ModelTier::parse_name(tier_name.as_str()) {
            Some(tier) => {
                let chain = state.tier_router.candidates_preferred(tier, req.preferred_provider.clone());
                for c in &chain {
                    candidates.push((c.provider.clone(), c.model.clone()));
                }
                if candidates.is_empty() {
                    

                    let cfg = state.cfg();
                    match resolve_tier_model(&req.model, &*cfg) {
                        Some(resolved) => candidates.push((cfg.default_provider.clone(), resolved)),
                        None => return error_response(StatusCode::BAD_REQUEST, format!("{}{}", format!("{}{}", "could not resolve tier '", req.model), "' — no candidates").as_str()),
                    };
                }
            },
            None => return error_response(StatusCode::BAD_REQUEST, format!("{}{}", format!("{}{}", "unknown tier '", tier_name), "'").as_str()),
        };
    } else {
        

        let cfg = state.cfg();
        let mut found = cfg.default_provider.clone();
        for (name, models) in crate::server_glue::config_provider_models(&cfg) {
            for m in &models {
                if m.id == req.model {
                    found = name.clone();
                }
            }
        }
        candidates.push((found, req.model));
    }



    let mut last_error: Option<String> = None;
    for entry in &candidates {
        let provider_name = entry.0.clone();
        let model_id = entry.1.clone();
        req.model = model_id;
        

        match state.pool.acquire_with_timeout(provider_name.as_str(), Duration::from_secs(30)).await {
            Some(permit) => {
                match state.registry.get(provider_name.as_str()) {
                    Some(provider) => {
                        

                        if req.stream {
                            return crate::server_glue::streaming_response(state, app_name, provider, req, permit).await;
                        }
                        

                        match provider.complete(&req).await {
                            Ok(resp) => {
                                match &resp.usage {
                                    Some(u) => state.tracker.record_full(app_name.as_str(), u.input_tokens, u.output_tokens, u.cache_read_tokens, u.cache_write_tokens),
                                    None => {},
                                };
                                return ok_response(resp);
                            },
                            Err(e) => {
                                



                                if e.is_quota_exhausted() {
                                    return error_response(StatusCode::PAYMENT_REQUIRED, format!("{}{}", "quota/billing exhausted: ", e.message()).as_str());
                                }
                                let retryable = e.is_retryable();
                                last_error = Some(e.message());
                                if retryable {
                                    

                                } else {
                                    return error_response(StatusCode::BAD_GATEWAY, format!("{}{}", "upstream error: ", e.message()).as_str());
                                }

                            },
                        };
                    },
                    None => last_error = Some(format!("{}{}", format!("{}{}", "provider '", provider_name), "' not in registry")),
                };
            },
            None => last_error = Some(format!("{}{}", format!("{}{}", "provider '", provider_name), "' concurrency pool unavailable")),
        };
    }


    let msg = match last_error { Some(e) => e, None => "unknown".to_string(), };
    return error_response(StatusCode::BAD_GATEWAY, format!("{}{}", "all providers failed; last error: ", msg).as_str());
}

/// `POST /v1/chat/completions` — receive a canonical request, resolve a
/// provider (with tier fallback across the candidate chain), call upstream,
/// return a canonical response.
/// 
/// STREAMING NOTE: the streaming branch (`req.stream == true`) is wired to
/// server_glue::streaming_response (Phase 3.6) — the SSE bridge uses bare
/// tokio::spawn + mpsc channel + async_stream::stream!, which have no .at
/// precedent, so the whole streaming fn lives in glue. The non-streaming path
/// (candidate chain + fallback + provider.complete) is fully transpiled here.
/// Build a JSON error response `(status, Json({"error":{"message":...}}))`.
/// (Replaces rust-ref's `(StatusCode, Json(json!(...))).into_response()` — we
/// hand-build the Value and let the IntoResponse impl for tuples do the rest.)
fn error_response(status: StatusCode, message: &str) -> Response {
    let mut err = serde_json::Map::new();
    err.insert("message".to_string(), Value::String(message.to_string()));
    let mut root = serde_json::Map::new();
    root.insert("error".to_string(), Value::Object(err));
    return (status, Json(Value::Object(root))).into_response();
}

/// Build a JSON success response from a CompletionResponse.
fn ok_response(resp: CompletionResponse) -> Response {
    let body = serde_json::to_value(&resp).unwrap_or(Value::Null);
    return (StatusCode::OK, Json(body)).into_response();
}

/// Read a header value as a string, or return the default. (Headers are ASCII;
/// non-UTF8 falls back to default.)
fn header_or(headers: HeaderMap, name: &str, default: &str) -> String {
    match headers.get(name) {
        Some(v) => {
            match v.to_str() {
                Ok(s) => return s.to_string(),
                Err(_) => return default.to_string(),
            };
            return default.to_string();
        },
        None => return default.to_string(),
    };
    return default.to_string();
}
