// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

/// SSE (Server-Sent Events) incremental parser — Auto source.
/// 
/// Ported from the daemon's native `sse.rs` (rust-ref). Parses the
/// `text/event-stream` format used by LLM streaming APIs. Operates on `str`
/// chunks (like auto-ai-client's SseBuffer) — SSE is text, and str slice/find
/// operations are a2r-native. The transpiled Rust links into the daemon's
/// provider streaming path.
/// 
/// Feed raw text via `push()`, get complete `data:` payloads back.
/// 
/// Codegen note: this file deliberately uses `.slice()` / `.find()` / `.trim()`
/// (the proven auto-ai-client SseBuffer pattern) rather than `.substring()` or
/// custom find/split_once/trim_start helpers. The former transpile cleanly with
/// a single `str_find(&self.buf, ...)` sed borrow-fix; the latter triggered 5
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct SseParser {
    pub buf: String,
}

impl SseParser {
    pub fn new() -> SseParser {
        return SseParser { buf: "".to_string() };
    }
    pub fn push(&mut self, chunk: &str) -> Vec<String> {
        self.buf = format!("{}{}", self.buf, chunk);
        return self.drain_data();
    }
    pub fn finish(&mut self) -> Vec<String> {
        self.buf = format!("{}{}", self.buf, "\n\n");
        return self.drain_data();
    }
    pub fn drain_data(&mut self) -> Vec<String> {
        let mut events: Vec<String> = vec![];
        loop {
            let frame = self.next_frame();
            if frame.is_empty() {
                break;
            }
            let data = extract_data(frame.as_str());
            if data.is_empty() == false {
                events.push(data.to_string());
            }
        }
        return events;
    }
    pub fn next_frame(&mut self) -> String {

        let crlf = a2r_std::str_find(&self.buf, "\r\n\r\n");
        if crlf >= 0 {
            let frame = self.buf[0..(crlf) as usize].to_string();
            self.buf = self.buf[(crlf + 4) as usize..].to_string();
            return frame;
        }
        let lf = a2r_std::str_find(&self.buf, "\n\n");
        if lf >= 0 {
            let frame = self.buf[0..(lf) as usize].to_string();
            self.buf = self.buf[(lf + 2) as usize..].to_string();
            return frame;
        }
        return "".to_string();
    }
}

/// Feed a chunk of text. Returns complete SSE data fields parsed so far.
/// Flush remaining buffer (call when stream ends).
/// Extract the `data:` field from an SSE frame.
/// Returns "" for non-data events (ping, comments) and for the [DONE] signal.
/// (Empty string = "no data field"; callers distinguish via the original
/// `is_empty()` check that the rust-ref expressed as `Option::None`.)
fn extract_data(frame: &str) -> String {
    let mut parts: Vec<String> = vec![];
    for line in frame.split("\n").collect::<Vec<_>>() {
        if line.is_empty() {
            continue;
        }
        if line.starts_with(":") {
            continue;
        }
        let data = data_field(line);
        if data.is_empty() == false {
            parts.push(data.to_string());
        }
    }
    if parts.is_empty() {
        return "".to_string();
    }
    let data = parts.join("\n");
    if data == "[DONE]" {
        return "".to_string();
    }
    return data;
}

/// If `line` is a `data: value` (or `data:value`) SSE field, return the value
/// with one leading space stripped (SSE spec: a single leading space after the
/// colon is part of the separator, not the value). Else return "".
/// 
/// Inlines str::split_once semantics via find+slice (a2r-native; avoids the
/// `.first()/.last()`-on-Option defect that the split_once helper hit).
fn data_field(line: &str) -> String {
    let colon = a2r_std::str_find(line, ":");
    if colon < 0 {
        return "".to_string();
    }
    let key = line[0..(colon) as usize].to_string();
    if key.trim().to_string() != "data" {
        return "".to_string();
    }
    let value = line[(colon + 1) as usize..].to_string();

    if value.starts_with(" ") {
        return value[1..].to_string();
    }
    return value;
}
