// Auto-generated by a2r transpiler

use std::collections::HashMap;
use crate::ai_config;
use crate::ai_config::{ModelTier, DaemonConfig};
use ai_config::loader::{TierRouting, TierRouteCandidate};
use crate::tier_router_glue;
/// Tier Router — multi-provider model routing with fallback.
/// 
/// Auto port of crates/auto-ai-daemon/src/tier_router.rs (production code only;
/// the #[cfg(test)] block stays in rust-ref — a2r .at doesn't transpile tests).
/// 
/// Replaces single-default-provider tier resolution with a configurable
/// tier→candidate-chain mapping. Each tier can have multiple candidates across
/// providers (primary → fallback 1 → fallback 2…). The router tries them in
/// order, falling back on 429/timeout.
/// 
/// Backward compatible: if no `tier_routing` is configured, auto-derives from
/// providers (default_provider's models first, others as fallbacks).
/// 
/// ITER NOTE: .at's Map has no iteration API, so HashMap traversal uses
/// `.keys().cloned().collect()` (a verified-clean a2r pattern) + per-key
/// `get()`, rather than `for (k, v) in &map`. This mirrors the role-registry
/// parallel-list convention but avoids maintaining a separate list: the keys
/// are materialized on demand inside `from_config`.
/// 
/// TYPE NOTE: links the rust-ref ai-config (DaemonConfig has no `provider_names`
/// field; TierRouting has `routes: HashMap<String, Vec<TierRouteCandidate>>`).
/// A single candidate in a tier's routing chain.
#[derive(Debug, Clone)]
pub struct TierCandidate {
    pub provider: String,
    pub model: String,
}

impl TierCandidate {
    pub fn new(provider: &str, model: &str) -> TierCandidate {
        return TierCandidate { provider: provider.to_string(), model: model.to_string() };
    }
}

/// The tier router — resolves a tier to an ordered list of candidates.
#[derive(Debug, Clone)]
pub struct TierRouter {
    pub routing: HashMap<ModelTier, Vec<TierCandidate>>,
}

impl TierRouter {
    pub fn default() -> TierRouter {
        return TierRouter { routing: HashMap::new() };
    }
    pub fn from_config(&self, config: DaemonConfig) -> TierRouter {

        if config.tier_routing.is_empty() == false {
            let mut routing: HashMap<ModelTier, Vec<TierCandidate>> = HashMap::new();
            




            for pair in tier_router_glue::tier_route_entries(&config.tier_routing) {
                let tier_name = pair.0.clone();
                let cands = pair.1.clone();
                match ModelTier::parse_name(tier_name.as_str()) {
                    Some(tier) => {
                        let mut tc: Vec<TierCandidate> = vec![];
                        for c in &cands {
                            tc.push(TierCandidate::new(c.provider.as_str(), c.model.as_str()));
                        }
                        routing.insert(tier, tc);
                    },
                    None => {
                        



                    },
                };
            }
            

            return TierRouter { routing: routing };
        }


        let mut routing: HashMap<ModelTier, Vec<TierCandidate>> = HashMap::new();


        match config.providers.get(&config.default_provider) {
            Some(default) => {
                for m in &default.models {
                    ensure_candidate(routing.clone(), m.tier, TierCandidate::new(config.default_provider.as_str(), m.id.as_str()));
                }
            },
            None => {},
        };


        for name in config.providers.keys().cloned().collect::<Vec<String>>() {
            if name == config.default_provider {
                continue;
            }
            match config.providers.get(name.as_str()) {
                Some(pc) => {
                    for m in &pc.models {
                        
                        if has_provider_for_tier(routing.clone(), m.tier, name.as_str()) == false {
                            ensure_candidate(routing.clone(), m.tier, TierCandidate::new(name.as_str(), m.id.as_str()));
                        }
                    }
                },
                None => {},
            };
        }
        return TierRouter { routing: routing };
    }
    pub fn candidates(&self, tier: ModelTier) -> Vec<TierCandidate> {
        match self.routing.get(&tier) {
            Some(v) => return v.clone(),
            None => return vec![],
        };
        return vec![];
    }
    pub fn candidates_preferred(&self, tier: ModelTier, preferred_provider: Option<String>) -> Vec<TierCandidate> {
        let base = self.candidates(tier);
        match preferred_provider {
            None => return base,
            Some(pref) => {
                

                let mut chain = base.clone();
                let idx = index_of_provider(chain.clone(), pref.as_str());
                if idx >= 0 {
                    let preferred = chain.remove(idx as usize);
                    

                    let mut reordered: Vec<TierCandidate> = vec![preferred];
                    for c in &chain {
                        reordered.push(c.clone());
                    }
                    return reordered;
                }
                

                return base;
            },
        };
        return base;
    }
    pub fn resolve(&self, tier: ModelTier, preferred_provider: Option<String>) -> Option<TierCandidate> {
        let cands = self.candidates(tier);
        if cands.is_empty() {
            return None;
        }

        match preferred_provider {
            Some(pref) => {
                for c in &cands {
                    if c.provider == pref {
                        return Some(c.clone());
                    }
                }
            },
            None => {},
        };

        return Some(cands[0].clone());
    }
}

/// Build a router from the daemon config. If `tier_routing` is explicitly
/// configured, use it. Otherwise auto-derive from providers
/// (default_provider's models first, others as fallbacks).
/// Resolve a tier to its candidate chain (primary first). Owned Vec so the
/// server can reorder it. Empty = no candidates configured.
/// Resolve a tier to a candidate chain, honoring an optional provider
/// preference. When `preferred_provider` matches a candidate, that candidate
/// moves to the front while the rest keep their order as fallbacks.
/// Resolve a tier to its first candidate, considering an optional provider
/// preference. The caller handles fallback by iterating `candidates()`.
/// Append `tc` to the candidate list for `tier`, creating the list if absent.
/// (Stands in for `routing.entry(tier).or_default().push(tc)`, which a2r can't
/// express cleanly — entry-API chains don't transpile.)
fn ensure_candidate(mut routing: HashMap<ModelTier, Vec<TierCandidate>>, tier: ModelTier, tc: TierCandidate) {
    match routing.get(&tier) {
        Some(list) => {
            let mut updated = list.clone();
            updated.push(tc.clone());
            routing.insert(tier, updated);
        },
        None => { routing.insert(tier, vec![tc]); },
    };
}

/// Does `routing[tier]` already contain a candidate for `provider`?
fn has_provider_for_tier(routing: HashMap<ModelTier, Vec<TierCandidate>>, tier: ModelTier, provider: &str) -> bool {
    match routing.get(&tier) {
        Some(cands) => {
            for c in cands {
                if c.provider == provider {
                    return true;
                }
            }
            return false;
        },
        None => return false,
    };
    return false;
}

/// Index of the first candidate whose provider == `provider`, or -1 if none.
fn index_of_provider(cands: Vec<TierCandidate>, provider: &str) -> i32 {
    let mut i: i32 = 0;
    for c in &cands {
        if c.provider == provider {
            return i;
        }
        i = i + 1;
    }
    return -1;
}
