// Auto-generated by a2r transpiler

use parking_lot::Mutex;
/// Usage tracker — per-app token/cost accounting.
/// 
/// Auto port of crates/auto-ai-daemon/src/tracker.rs. Thread-safe usage tracker
/// recording per-app token consumption. The Rust original uses a
/// `parking_lot::Mutex<HashMap<String, AppUsage>>`; this .at version mirrors it
/// directly via `use.rust parking_lot`.
/// 
/// TYPE NOTE: links the rust-ref ai-config + parking_lot 0.12 (Cargo.toml dep).
/// 
/// MAP-ITER NOTE: .at's Map has no iteration API (same constraint as ai-config's
/// `provider_names` parallel list), so `all()` walks a hand-maintained `names`
/// list rather than `iter()`. The list stays in insertion order; duplicates are
/// suppressed on insert.
/// Per-app accumulated usage (tokens + request count).
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct AppUsage {
    pub total_input_tokens: u32,
    pub total_output_tokens: u32,
    pub request_count: u32,
}

impl AppUsage {
    pub fn new() -> AppUsage {
        return AppUsage { total_input_tokens: 0, total_output_tokens: 0, request_count: 0 };
    }
    pub fn total_tokens(&self) -> u32 {
        return self.total_input_tokens + self.total_output_tokens;
    }
}

/// Total tokens consumed (input + output).
/// Thread-safe usage tracker. Records per-app token consumption.
#[derive(Debug)]
pub struct UsageTracker {
    pub apps: Mutex<std::collections::HashMap<String, AppUsage>>,
    pub names: Mutex<Vec<String>>,
}

impl UsageTracker {
    pub fn new() -> UsageTracker {
        return UsageTracker { apps: Mutex::new(std::collections::HashMap::new()), names: Mutex::new(vec![]) };
    }
    pub fn record(&self, app: &str, input: u32, output: u32) {
        let mut guard = self.apps.lock();
        match guard.get(app) {
            Some(entry) => {
                



                let mut updated = AppUsage::new();
                updated.total_input_tokens = entry.total_input_tokens + input;
                updated.total_output_tokens = entry.total_output_tokens + output;
                updated.request_count = entry.request_count + 1;
                guard.insert(app.to_string(), updated);
            },
            None => {
                let mut e = AppUsage::new();
                e.total_input_tokens = input;
                e.total_output_tokens = output;
                e.request_count = 1;
                guard.insert(app.to_string(), e);
                self.names.lock().push(app.to_string());
            },
        };
    }
    pub fn get(&self, app: &str) -> AppUsage {
        let guard = self.apps.lock();
        match guard.get(app) {
            Some(entry) => return entry.clone(),
            None => return AppUsage::new(),
        };
        return AppUsage::new();
    }
    pub fn all(&self) -> Vec<(String, AppUsage)> {
        let guard = self.apps.lock();
        let names = self.names.lock();
        let mut out: Vec<(String, AppUsage)> = vec![];
        for name in names.iter() {
            match guard.get(name) {
                Some(u) => out.push((name.clone(), u.clone())),
                None => {},
            };
        }
        return out;
    }
}
