// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;
use crate::error::ToolError;

use std::sync::Arc;
use parking_lot::Mutex;
use std::sync::atomic::AtomicBool;
use std::sync::atomic::Ordering;
use std::future::Future;
use std::pin::Pin;
use async_trait;
use serde_json;
use serde_json::Value;
use crate::auto_ai_client::{ClientError, CompletionRequest, CompletionResponse, Message};
use crate::error::{AgentError};
use crate::memory::{Memory};
use crate::compaction::{CompactionSettings, default_compaction_settings, should_compact, estimate_tokens, compact, is_context_overflow};
use crate::role_def::{Role};
use crate::skill::{SkillTool};
use crate::ai_config::{ModelTier, Usage};
use crate::tool::{ToolRegistry, tool_to_definition, Tool, ToolOutput};
use crate::wire::{ContentBlock, JsonValue, ToolDefinition};
/// The autonomous agent (Layer 3 core).
/// 
/// An Agent binds a Role (personality), a ToolRegistry (capabilities), a Memory
/// (conversation), and a Client (LLM transport) into a single ReAct loop in
/// Agent.run.
/// 
/// The LLM transport is abstracted behind the Client spec so the loop can be
/// driven by the real auto_ai_client.AiClient in production OR a deterministic
/// mock in tests.
/// 
/// Auto port of crates/auto-ai-agent/src/agent.rs (auto-ai v0.4.0).
/// 
/// STATUS — ReAct loop ported; streaming via Auto actor sink (Plan 021 缺口 1,
/// 2026-08-05): This file ports the full type surface (Client spec, StreamEvent,
/// AgentResult, ToolCallRecord, the Agent struct, truncate_tool_result, public
/// accessors) AND the ReAct loop (run / run_stream / run_inner / build_request).
/// 
/// ARCHITECTURE (streaming — Plan 022 follow-up, auto-lang Plan 397): the loop
/// now mirrors rust-ref: `run_inner` calls `Client.complete_stream(req, cb)`
/// where `cb` is an `Arc<Fn(JsonValue)>` (Plan 397 confirmed this works as a spec
/// method parameter). The cb forwards each SSE text delta to the EventSink actor
/// as `StreamEvent.Delta` (per-token streaming). The Client spec's
/// `complete_stream` has a default impl that falls back to non-streaming
/// `complete` + one synthetic delta, so test mocks stay simple.
/// 
/// Event delivery uses an **Auto actor sink** (auto-lang Plan 387 §16/17):
/// `run_stream` takes a `TaskRef<StreamEvent>` handle (spawned from `EventSink`,
/// defined below) and every event point does `sink.send(...)`. `run` spawns a
/// throwaway sink so the loop body is sink-only (mirrors rust-ref's "on_event is
/// always a sink", review-003 M4). The sink handler forwards each event to `cb` —
/// a `Box<dyn Fn(StreamEvent)>` closure (Plan 390 §15.10) injected at spawn.
/// Tool execution stays async (`execute ~Result<str,ToolError>`).
/// 
/// Other Auto-side adaptations (none affect behavior):
/// - generic `fn new<P: Role>(role P, ...)` → `new_shared(role Role, ...)` with
/// a spec-typed field (Auto `spec` is auto-dyn, equivalent to Arc<dyn Role>).
/// 
/// VARIANT NOTE: StreamEvent's struct-style variants are modeled as tuple
/// variants (plan 013 gotcha B3). Field order:
/// - StreamEvent.TurnStart(turn)                       (Plan 026)
/// - StreamEvent.TurnEnd(turn, usage, tool_count)      (Plan 026)
/// - StreamEvent.Delta(text)
/// - StreamEvent.Thinking(text)                        (Plan 026, was degraded to Delta)
/// - StreamEvent.ToolStart(tool, args)
/// - StreamEvent.Warning(text)
/// - StreamEvent.Tool(tool, args, result)
/// - StreamEvent.Done(result)
/// - StreamEvent.Cancelled(result)
/// - StreamEvent.Error(message)
/// After how many identical (tool, args) repeats the loop bails out as a cycle.
fn loop_detect_threshold() -> u32 {
    return 3;
}

/// Maximum chars of a tool result stored in memory (~5k tokens). Tool outputs
/// longer than this are truncated (with a notice) so a single read_file of a
/// huge file can't blow out the context window for the rest of the run.
fn max_tool_result_chars() -> u32 {
    return 20000;
}

pub fn truncate_tool_result(s: &str) -> String {
    let cap = max_tool_result_chars();
    let count: u32 = ((s.len() as i64) as u32);
    if count <= cap {
        return s.to_string();
    }
    let kept = &s[0 as usize..cap as usize];
    let dropped: u32 = count - cap;
    return format!("{}
…[truncated {} more chars]", kept, dropped);
}

#[async_trait::async_trait]
pub trait Client: Send + Sync {
    async fn complete(&self, req: CompletionRequest) -> Result<CompletionResponse, ClientError>;
    async fn complete_stream(&self, req: CompletionRequest, on_event: Arc<dyn Fn(JsonValue) + Send + Sync>) -> Result<CompletionResponse, ClientError>;
}


/// Truncate a tool result to max_tool_result_chars(), appending a notice when
/// truncation happened. Returns the (possibly truncated) string.
/// The LLM transport an Agent talks to.
/// 
/// Abstracts auto_ai_client.AiClient so the ReAct loop can be unit-tested with
/// a deterministic mock.
/// 
/// complete_stream (Plan 022 follow-up, auto-lang Plan 397): takes an
/// `Arc<Fn(JsonValue)>` callback invoked per SSE event the daemon emits. The
/// real AiClient adapter (client_impl.rs) overrides it with true SSE streaming;
/// test mocks implement it via the `default_complete_stream` helper (a free fn
/// in client_impl.rs) since spec default bodies can't call self methods
/// (a2r DIV-TRAIT-A2R-3 known gap).
/// One non-streaming completion request.
/// Streaming completion. Calls `on_event` for each SSE event the daemon
/// emits (a JsonValue like {"type":"delta","text":"…"}). Returns the
/// accumulated full response on success.
/// Events emitted by Agent.run_stream as the ReAct loop progresses.
/// Tuple variants (plan 013 gotcha B3) — see file header for field order.
/// A ReAct turn is starting (one LLM call plus its tool batch, if any).
/// 1-based, matching AgentResult.turns. (turn) — Plan 026 pi parity.
/// A ReAct turn completed normally (tool batch recorded, or final answer /
/// follow-up revival). NOT emitted on cancel/error. (turn, usage,
/// tool_count) — Plan 026.
/// A chunk of the model's text output. (text)
/// A chunk of the model's reasoning/thinking output (reasoning-capable
/// models, typically before the Delta answer). (text) — Plan 026: the .at
/// track previously degraded reasoning to Delta; now a first-class variant
/// matching rust-ref.
/// A tool is about to be executed. (tool, args)
/// A non-fatal advisory message (e.g. the near-turn-cap warning). (text)
/// A tool was called and produced a result. result is the content fed
/// back to the model; details is the structured UI payload (Plan 027) —
/// never enters the LLM context. (tool, args, result, details)
/// The loop finished successfully (carries the full result). (result)
/// The run was cancelled by the user. (result)
/// The loop failed. (message)
#[derive(Clone, Debug, PartialEq)]
pub enum StreamEvent {
    TurnStart(u32),
    TurnEnd(u32, Option<Usage>, u32),
    Delta(String),
    Thinking(String),
    ToolStart(String, JsonValue),
    Warning(String),
    Tool(String, JsonValue, String, Option<JsonValue>),
    Done(AgentResult),
    Cancelled(AgentResult),
    Error(String),
}


struct EventSink {
    log: String,
    cb: Box<dyn Fn(StreamEvent) + Send + Sync>,
}

impl EventSink {
    pub fn new() -> Self {
        Self {
            log: format!(""),
            cb: Box::new(move |e: StreamEvent| { }),
        }
    }

    pub async fn start(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        Ok(())
    }

    pub async fn stop(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        Ok(())
    }

    pub async fn handle_msg(&mut self, msg: StreamEvent, reply_tx: a2r_std::task::NopReply) -> Result<(), Box<dyn std::error::Error>> {
        match msg {
            ev => {
                




                (self.cb)(ev.clone());
                match ev {
                    StreamEvent::TurnStart(turn) => self.log = format!("{}TURNS:{};", self.log, turn),
                    StreamEvent::TurnEnd(turn, _usage, _tools) => self.log = format!("{}TURNE:{};", self.log, turn),
                    StreamEvent::Delta(text) => self.log = format!("{}D:{};", self.log, text),
                    StreamEvent::Thinking(text) => self.log = format!("{}TH:{};", self.log, text),
                    StreamEvent::ToolStart(tool, _args) => self.log = format!("{}TS:{};", self.log, tool),
                    StreamEvent::Warning(text) => self.log = format!("{}W:{};", self.log, text),
                    StreamEvent::Tool(tool, _args, _result, _details) => self.log = format!("{}T:{};", self.log, tool),
                    StreamEvent::Done(result) => self.log = format!("{}DONE:{};", self.log, result.output),
                    StreamEvent::Cancelled(result) => self.log = format!("{}CANCEL:{};", self.log, result.output),
                    StreamEvent::Error(message) => self.log = format!("{}E:{};", self.log, message),
                };
            }
            _ => {
                let _ = msg;
            }
        };
        Ok(())
    }
}

pub fn spawn_event_sink_with(log: String, cb: Box<dyn Fn(StreamEvent) + Send + Sync>) -> a2r_std::task::TaskRef<StreamEvent> {
    let (taskref, mut rx) = a2r_std::task::channel::<StreamEvent>();
    let join = tokio::spawn(async move {
        let mut actor = EventSink { log: log, cb: cb };
        let _ = actor.start().await;
        while let Some(msg) = rx.recv().await {
            let reply_tx = a2r_std::task::NopReply;
            let _ = actor.handle_msg(msg, reply_tx).await;
            rx.mark_processed();
        }
    });
    a2r_std::task::track_join(join);
    taskref
}

pub fn spawn_event_sink() -> a2r_std::task::TaskRef<StreamEvent> {
    let (taskref, mut rx) = a2r_std::task::channel::<StreamEvent>();
    let join = tokio::spawn(async move {
        let mut actor = EventSink::new();
        let _ = actor.start().await;
        while let Some(msg) = rx.recv().await {
            let reply_tx = a2r_std::task::NopReply;
            let _ = actor.handle_msg(msg, reply_tx).await;
            rx.mark_processed();
        }
    });
    a2r_std::task::track_join(join);
    taskref
}


/// A sink actor that consumes `StreamEvent`s sent by `Agent.run_stream`.
/// 
/// Callers spawn it with a forwarding callback and pass the handle to `run_stream`:
/// let sink = Task.spawn("EventSink", 64, Box((ev) => forward(ev)))
/// let result = agent.run_stream(task, cancel, sink).await.?
/// The callback (a `Box<dyn Fn(StreamEvent)>` — Plan 390 §15.10) is injected at
/// spawn via the `_with` init arg (a closure capturing the app's event handler);
/// `run` (non-streaming) spawns with all-default args so the no-op closure
/// default consumes events without forwarding.
/// 
/// The handler destructures every event variant, accumulates a compact text log
/// in its state, AND forwards the whole event to `cb` (Plan 390 §6.7 — the cb
/// injection mechanism, unblocking sink→app forwarding). The default cb is an
/// empty closure literal (Plan 390 §15.10 transpiles it to
/// `Box::new(move |..| { .. })` — a `Box<dyn Fn>` field).
/// A record of one tool call made during a run (for diagnostics/results).
#[derive(Clone, Debug, PartialEq)]
pub struct ToolCallRecord {
    pub tool: String,
    pub args: JsonValue,
    pub result: String,
}

/// The outcome of Agent.run.
#[derive(Clone, Debug, PartialEq)]
pub struct AgentResult {
    pub output: String,
    pub turns: u32,
    pub tool_calls: Vec<ToolCallRecord>,
    pub total_tokens: u32,
}

impl AgentResult {
    pub fn default() -> AgentResult {
        return AgentResult { output: "".to_string(), turns: 0 as u32, tool_calls: vec![], total_tokens: 0 as u32 };
    }
    pub fn content(&self) -> String {
        return self.output.clone();
    }
}

/// The agent's final textual answer.
/// How many ReAct turns the loop ran.
/// Every tool call the agent made, in order.
/// Total tokens consumed (if the transport reports usage).
/// The accumulated text content (alias used by the driver for handoff
/// summaries). Mirrors the Rust driver's `collected` buffer.
/// An autonomous agent that drives an LLM toward a goal via a ReAct loop.
/// 
/// NOTE: `role` and `client` are spec-typed fields (Auto `spec` is dynamically
/// dispatched, equivalent to Rust's `Arc<dyn Role>` / `Arc<dyn Client>`). The
/// Rust `new<P: Role + 'static>(role P, ...)` generic constructor is not
/// portable to Auto (generic methods are a parse error) — construction goes
/// through Agent.new_shared (takes spec values) instead.
#[allow(dead_code)]
pub struct Agent {
    pub role: Box<dyn Role>,
    pub tools: ToolRegistry,
    pub memory: Memory,
    pub client: Box<dyn Client>,
    pub skills_block: Option<String>,
    pub context_block: Option<String>,
    pub steering: Arc<Mutex<Vec<String>>>,
    pub follow_ups: Arc<Mutex<Vec<String>>>,
    pub last_usage: Option<Usage>,
    pub compaction: CompactionSettings,
    pub compaction_on: bool,
    pub compaction_window_pinned: bool,
    pub last_summary: Option<String>,
}

impl Agent {
    pub fn new_shared(mut role: Box<dyn Role>, client: Box<dyn Client>) -> Agent {
        let limit = role.memory_limit();
        return Agent { role: role, tools: ToolRegistry::new(), memory: Memory::new(limit), client: client, skills_block: None, context_block: None, steering: Arc::new(Mutex::new(vec![])), follow_ups: Arc::new(Mutex::new(vec![])), last_usage: None, compaction: default_compaction_settings(), compaction_on: true, compaction_window_pinned: false, last_summary: None };
    }
    pub fn with_context(&mut self, context: &str) {
        let ctx = context.trim().to_string();
        if ctx.is_empty() == false {
            self.context_block = Some(context.to_string());
        }
    }
    pub fn register_shared(&mut self, tool: Arc<dyn Tool>) {
        self.tools.register_shared(tool);
    }
    pub fn register_tool(&mut self, tool: Box<dyn Tool>) {
        self.tools.register(tool);
    }
    pub fn register_skill_tool(&mut self, mut tool: SkillTool) {
        let block = tool.available_skills_block();
        match (block.len() as i64) == 0 {
            true => self.skills_block = None,
            false => self.skills_block = Some(block),
        };



        self.register_tool(Box::new(tool));
    }
    pub fn memory_messages(&self) -> Vec<Message> {
        return self.memory.messages();
    }
    pub fn history(&self) -> Vec<Message> {
        return self.memory.messages();
    }
    pub async fn run(&mut self, task_msg: &str) -> Result<AgentResult, AgentError> {

        let discard = spawn_event_sink();
        return self.run_inner(task_msg, None, discard).await;
    }
    pub fn steer(&self, msg: &str) {
        let mut guard = self.steering.lock();
        guard.push(msg.to_string());
    }
    pub fn follow_up(&self, msg: &str) {
        let mut guard = self.follow_ups.lock();
        guard.push(msg.to_string());
    }
    pub fn steering_queue(&self) -> Arc<Mutex<Vec<String>>> {
        return self.steering.clone();
    }
    pub fn follow_up_queue(&self) -> Arc<Mutex<Vec<String>>> {
        return self.follow_ups.clone();
    }
    pub fn drop_steering_on_cancel(&self, sink: a2r_std::task::TaskRef<StreamEvent>) {
        let mut n: u32 = 0 as u32;
        let mut draining: bool = true;
        while draining {
            match pop_front(self.steering.clone()) {
                Some(_m) => n = n + 1,
                None => draining = false,
            };
        }
        if n > 0 {
            let w = StreamEvent::Warning(format!("cancelled: {} steering messages dropped", n));
            sink.send(w);
        }
    }
    pub async fn run_stream(&mut self, task_msg: &str, cancel: Arc<AtomicBool>, sink: a2r_std::task::TaskRef<StreamEvent>) -> Result<AgentResult, AgentError> {
        return self.run_inner(task_msg, Some(cancel), sink).await;
    }
    pub fn set_compaction_settings(&mut self, mut settings: CompactionSettings) {
        self.compaction = settings.clone();
        self.compaction_window_pinned = true;
    }
    pub fn compaction_settings(&self) -> CompactionSettings {
        return self.compaction.clone();
    }
    pub async fn try_compact(&mut self, sink: a2r_std::task::TaskRef<StreamEvent>, reason: &str) -> bool {
        let model = build_model_id(self.role.model().as_str(), self.role.model_tier());
        let est = estimate_tokens(self.memory.messages(), self.last_usage.clone());
        match compact(self.memory.clone(), &self.client, model.as_str(), self.compaction.clone(), self.last_summary.clone()).await {
            Ok(pair) => {
                self.memory = pair.0;
                self.last_summary = Some(pair.1);
                let mut text: String = format!("context compacted (estimated {} tokens)", est);
                if reason == "overflow" {
                    text = format!("context overflow recovered, compacted and retried (was ~{} tokens)", est);
                }
                let w = StreamEvent::Warning(text);
                sink.send(w);
                return true;
            },
            Err(e) => {
                let w = StreamEvent::Warning(format!("compaction skipped: {}", e.message()));
                sink.send(w);
                return false;
            },
        };
        return false;
    }
    pub async fn request_with_recovery(&mut self, sink: a2r_std::task::TaskRef<StreamEvent>) -> Result<CompletionResponse, AgentError> {
        let mut req = self.build_request();
        let mut retried: bool = false;
        let mut settled: bool = false;
        while settled == false {
            let sink_cb = sink.clone();
            match self.client.complete_stream(req.clone(), Arc::new(move |ev| forward_sse_delta(ev.clone(), &sink_cb))).await {
                Err(e) => {
                    let mut handled: bool = false;
                    if retried == false {
                        if self.compaction_on {
                            if is_context_overflow(&e.message()) {
                                let ok = self.try_compact(sink.clone(), "overflow").await;
                                if ok {
                                    retried = true;
                                    req = self.build_request();
                                    handled = true;
                                }                            }                        }                    }
                    if handled == false {
                        return Err(AgentError::Client(e));
                    }
                },
                Ok(resp) => {
                    match resp.error {
                        Some(err) => {
                            let mut handled2: bool = false;
                            if retried == false {
                                if self.compaction_on {
                                    if is_context_overflow(&err) {
                                        let ok = self.try_compact(sink.clone(), "overflow").await;
                                        if ok {
                                            retried = true;
                                            req = self.build_request();
                                            handled2 = true;
                                        }                                    }                                }                            }
                            if handled2 == false {
                                let ev = StreamEvent::Error(err.clone());
                                sink.send(ev);
                                return Err(AgentError::Config(err));
                            }
                        },
                        None => {
                            



                            match &resp.model_meta {
                                Some(meta) => {
                                    if self.compaction_window_pinned == false {
                                        self.compaction.context_window = meta.context_window;
                                    }
                                },
                                None => {},
                            };
                            settled = true;
                            return Ok(resp);
                        },
                    };
                },
            };
        }
        return Err(AgentError::Config("request_with_recovery: unreachable".to_string()));
    }
    pub async fn run_inner(&mut self, task_msg: &str, mut cancel: Option<Arc<AtomicBool>>, sink: a2r_std::task::TaskRef<StreamEvent>) -> Result<AgentResult, AgentError> {


        if self.compaction_on {
            let est = estimate_tokens(self.memory.messages(), self.last_usage.clone());
            if should_compact(est, self.compaction.clone()) {
                let ok = self.try_compact(sink.clone(), "threshold").await;
                if ok == false {
                    

                }            }        }
        self.memory.add("user", task_msg);
        let soft_limit = self.role.max_turns();
        let hard_limit: u32 = soft_limit * 5;
        let mut result = AgentResult::default();

        let mut seen: std::collections::HashMap<String, u32> = std::collections::HashMap::new();
        let mut seen_names: Vec<String> = vec![];

        let mut turn: u32 = 0 as u32;
        while turn < hard_limit {
            
            if is_cancelled(cancel.clone()) {
                self.drop_steering_on_cancel(sink.clone());
                let ce = cancelled_event(result.clone());
                sink.send(ce);
                return Ok(result);
            }
            





            let mut injected: bool = true;
            while injected {
                injected = false;
                match pop_front(self.steering.clone()) {
                    Some(msg) => {
                        self.memory.add("user", msg.as_str());
                        injected = true;
                    },
                    None => {},
                };
            }
            
            turn = turn + 1;
            result.turns = turn;
            let ts = StreamEvent::TurnStart(turn);
            sink.send(ts);
            

            let remaining: u32 = hard_limit - turn;
            if remaining <= 5 {
                if remaining > 1 {
                    let w = StreamEvent::Warning(format!("{} turns until the hard stop — wrap up now.", remaining - 1));
                    sink.send(w);
                }            }
            





            let resp = self.request_with_recovery(sink.clone()).await?;
            

            if is_cancelled(cancel.clone()) {
                result.total_tokens = record_usage(result.clone(), resp.clone());
                self.drop_steering_on_cancel(sink.clone());
                let ce = cancelled_event(result.clone());
                sink.send(ce);
                return Ok(result);
            }
            
            result.total_tokens = record_usage(result.clone(), resp.clone());
            self.last_usage = resp.usage.clone();
            
            if resp.wants_tool() {
                

                if is_cancelled(cancel.clone()) {
                    self.drop_steering_on_cancel(sink.clone());
                    let ce = cancelled_event(result.clone());
                    sink.send(ce);
                    return Ok(result);
                }                



                let mut blocks: Vec<ContentBlock> = vec![];
                if resp.content.is_empty() == false {
                    let tb = ContentBlock::Text { text: resp.content };
                    blocks.push(tb.clone());
                }                let mut tc_idx: u32 = 0 as u32;
                

                for tc in resp.tool_calls.clone() {
                    let ub = ContentBlock::ToolUse { id: tc.id, name: tc.name, input: tc.input };
                    blocks.push(ub.clone());
                    tc_idx = tc_idx + 1;
                }
                if blocks.is_empty() == false {
                    let am = Message { role: "assistant".to_string(), content: blocks };
                    self.memory.add_message(am);
                }                








                let mut tcs = resp.tool_calls.clone();
                let mut idx: u32 = 0 as u32;
                while idx < tcs.len() as u32 {
                    if is_cancelled(cancel.clone()) {
                        let mut j: u32 = idx;
                        while j < tcs.len() as u32 {
                            let un = tcs[(j) as usize].clone();
                            let pr = Message::tool_result(un.id, "[cancelled by user]");
                            self.memory.add_message(pr);
                            j = j + 1;
                        }
                        self.drop_steering_on_cancel(sink.clone());
                        let ce = cancelled_event(result.clone());
                        sink.send(ce);
                        return Ok(result);
                    }
                    

                    let tc = tcs[(idx) as usize].clone();
                    let key: String = format!("{}::{}", tc.name, tc.input);
                    let count = bump_seen(seen.clone(), seen_names.clone(), key.as_str());
                    if count >= loop_detect_threshold() {
                        let ev = StreamEvent::Error(format!("loop detected on '{}'", tc.name));
                        sink.send(ev);
                        return Err(AgentError::LoopDetected(tc.name));
                    }
                    
                    let tse = StreamEvent::ToolStart(tc.name.clone(), tc.input.clone());
                    sink.send(tse);
                    
                    let outcome = self.tools.exec_or_msg(tc.name.as_str(), tc.input.clone()).await;
                    let rec = ToolCallRecord { tool: tc.name.clone().to_string(), args: tc.input.clone(), result: outcome.content.clone().to_string() };
                    result.tool_calls.push(rec.clone());
                    

                    let tev = StreamEvent::Tool(tc.name, tc.input, outcome.content.clone(), outcome.details.clone());
                    sink.send(tev);
                    

                    let tr = Message::tool_result(tc.id, truncate_tool_result(outcome.content.as_str()));
                    self.memory.add_message(tr);
                    idx = idx + 1;
                }
                


                let tend = StreamEvent::TurnEnd(turn, resp.usage.clone(), ((resp.tool_calls.len() as i64) as u32));
                sink.send(tend);
                

            } else {
                

                result.output = resp.content.clone();
                

                self.memory.add("assistant", resp.content.as_str());
                




                let mut revived: bool = false;
                let mut pump: bool = true;
                while pump {
                    match pop_front(self.follow_ups.clone()) {
                        Some(msg) => {
                            self.memory.add("user", msg.as_str());
                            revived = true;
                        },
                        None => pump = false,
                    };
                }
                

                let fend = StreamEvent::TurnEnd(turn, resp.usage.clone(), 0);
                sink.send(fend);
                if revived {
                    

                } else {
                    let done = StreamEvent::Done(clone_result(result.clone()));
                    sink.send(done);
                    return Ok(result);
                }
            }

        }


        let err = StreamEvent::Error(format!("hard turn cap ({}) exceeded (soft limit was {})", hard_limit, soft_limit));
        sink.send(err);
        return Err(AgentError::MaxTurnsExceeded(hard_limit));
    }
    pub fn build_request(&self) -> CompletionRequest {
        let allowed = self.role.allowed_tools();
        let visible = self.tools.filter(allowed);
        let mut tool_defs: Vec<ToolDefinition> = vec![];
        for t in &visible {
            tool_defs.push(tool_to_definition(t.clone()));
        }



        let pinned = self.role.model();
        let model = build_model_id(pinned.as_str(), self.role.model_tier());

        let system_prompt = build_system_prompt(self.context_block.clone(), self.role.system_prompt().as_str(), self.skills_block.clone());

        return CompletionRequest { model: model, messages: self.memory.to_messages(), max_tokens: None, temperature: Some(self.role.temperature()), system_prompt: Some(system_prompt), tools: tool_defs, stream: false, preferred_provider: self.role.preferred_provider() };
    }
}

/// Bootstrap block listing available skills (injected into the system
/// prompt so the model knows what it can invoke). Set by
/// register_skill_tool.
/// Project context (e.g. contents of .musk.md / CLAUDE.md). Prepended to
/// the system prompt so the agent starts with project knowledge.
/// Steering queue (Plan 026): user messages injected mid-run, after the
/// previous tool batch lands in memory and before the next LLM call.
/// Shared handle so app layers (musk) can push while the run is in flight.
/// Follow-up queue (Plan 026): revives a run that was about to end
/// naturally (final answer, nothing pending).
/// Most recent assistant usage report (Plan 028: real token data for the
/// compaction estimator).
/// Compaction thresholds (Plan 028).
/// Kill switch for auto-compaction (on by default).
/// Plan 031: set_compaction_settings was called — the window no longer
/// follows response metadata (explicit settings win, so tests and special
/// scenarios can pin the thresholds).
/// Plan 031: the summary produced by the most recent compaction (seed for
/// the incremental UPDATE template on the next compaction).
/// Build a new agent from an already-shared Role + Client spec value, and
/// the Role's memory-limit preference. (Non-generic substitute for Rust's
/// `new<P: Role>(role P, client)`.)
/// Inject project context (e.g. the contents of .musk.md or CLAUDE.md) into
/// the system prompt. Prepended before the role's soul.
/// Register a tool the agent may call (takes a spec value).
/// Register a tool from a concrete spec value (mirrors rust-ref's
/// `register_tool<T: Tool + 'static>`). The caller passes a plain struct
/// value (`agent.register_tool(MyTool{})`) and the registry Arc-wraps it
/// internally. Call sites auto-box via a2r Plan 390 §11 Phase E
/// (`register_tool(Box::new(my_tool))`); no manual `Arc::new(Box::new(...))`.
/// Register a SkillTool AND cache its available-skills block so
/// build_system_prompt injects the skill directory into the system prompt.
/// Mirrors rust-ref's register_skill_tool (both register + cache); the
/// SkillTool also implements Tool, so register_tool handles Arc-wrapping.
/// (Plan 016 2.2 + Plan 022 Phase 3.1 — previously only cached the block,
/// leaving skill(...) tool calls as "tool not found".)
/// Snapshot of the current conversation memory (for session persistence).
/// Current conversation memory.
/// Run the ReAct loop against `task`, returning the agent's final answer.
/// Non-streaming, non-cancellable (delegates to run_inner with cancel=None
/// and a throwaway EventSink that consumes the events — nothing observable).
/// `mut fn`: the loop mutates self.memory/tools.
/// Queue a steering message (Plan 026): injected into the conversation
/// after the current tool batch completes, before the next LLM call —
/// never interrupts an in-flight tool. Safe to call mid-run.
/// Queue a follow-up message (Plan 026): revives the run when it was about
/// to end naturally (final answer, no pending tools); counted against the
/// turn limits (anti-runaway).
/// Shared handle to the steering queue (app-layer wiring, e.g. musk's
/// axum handlers pushing directly mid-run).
/// Shared handle to the follow-up queue.
/// Plan 026: cancel drops queued steering messages; report the loss so the
/// UI can tell the user their mid-run messages were discarded.
/// Like run, but honors a cancellation flag at the turn boundaries AND
/// streams every ReAct event to `sink` (Plan 021 缺口 1). The Rust original
/// takes an `Arc<dyn Fn(StreamEvent)>` callback; the Auto port takes a
/// `TaskRef<StreamEvent>` actor handle instead (auto-lang Plan 387 §16/17 —
/// the EventSink task is defined above). The caller spawns the sink with a
/// forwarding closure (Plan 390 §15.10 Box<dyn Fn>):
/// `Task.spawn("EventSink", 16, f"", Box((ev) => forward(ev, on_event)))`.
/// `mut fn`: run_inner mutates self.memory/tools.
/// Override the compaction settings (Plan 028). Plan 031: an explicit
/// override also pins context_window — later response metadata no longer
/// adjusts it.
/// The current compaction settings (Plan 031: the window may have been
/// refreshed from response metadata — tests assert on the live value).
/// Compact now and report via a Warning (Plan 031: shared by the pre-run
/// threshold check and the overflow-recovery path). Updates last_summary
/// so the next compaction can use the incremental UPDATE template.
/// Returns false when compaction failed (caller keeps the original memory).
/// Issue this turn's LLM request with overflow recovery (Plan 031): when
/// the call fails with a context-overflow error — either as a transport
/// error or in-band as resp.error — compact the memory and retry this
/// turn's request ONCE against the compacted history (bounded, no loop).
/// A second overflow propagates as an error.
/// Unified ReAct loop backing run + run_stream.
/// 
/// Each turn: build a request from memory + role, ask the model, execute
/// any tool calls, feed results back. Stops when the model replies with
/// plain text (no tool calls), a tool-call cycle is detected
/// (LOOP_DETECT_THRESHOLD), or the hard safety cap (max_turns * 5) is hit.
/// The Role's max_turns is a SOFT target — the agent may exceed it while
/// still making progress; the hard cap is 5x the soft target.
/// `mut fn`: mutates self.memory (add/add_message) + self.tools.
/// Build the completion request for the current turn: system prompt from
/// the Role, the role's tier/model, the full memory, and the tools the
/// Role allows.
/// True when the caller has requested cancellation (cancel flag set + true).
fn is_cancelled(cancel: Option<Arc<AtomicBool>>) -> bool {
    match cancel {
        None => return false,
        Some(c) => {
            

            let v = c.load(Ordering::SeqCst);
            return v;
        },
    }
}

/// Increment the recurrence count for a (tool, args) key, returning the new
/// count. Keeps the parallel `seen_names` key list in sync (Auto's VM Map has
/// no iteration API — plan 013 gotcha B5).
fn bump_seen(mut seen: std::collections::HashMap<String, u32>, mut seen_names: Vec<String>, key: &str) -> u32 {
    let mut prev: u32 = 0 as u32;


    match seen.get(key) {
        Some(n) => prev = n.clone(),
        None => seen_names.push(key.to_string()),
    };
    let next: u32 = prev + 1;
    seen.insert(key.to_string(), next);
    return next;
}

/// Compute the updated running token total after folding in a response's usage
/// (if any). Returned so the caller assigns it back — a2r clones struct args at
/// call sites, so mutating a `result` param in place wouldn't reach the caller,
/// and the param binding isn't `mut` by default (E0594).
fn record_usage(result: AgentResult, resp: CompletionResponse) -> u32 {
    match resp.usage {
        Some(u) => return result.total_tokens + u.total_tokens(),
        None => return result.total_tokens,
    }
}

/// A Cancelled event carrying a snapshot of the current result.
fn cancelled_event(mut result: AgentResult) -> StreamEvent {
    return StreamEvent::Cancelled(clone_result(result.clone()));
}

/// Forward one SSE event (from Client.complete_stream's callback) to the
/// EventSink. Reasoning-aware (Plan 026): a `{"type":"reasoning","text":…}`
/// chunk forwards as StreamEvent.Thinking, everything else with text as
/// StreamEvent.Delta — matching rust-ref agent.rs (the .at track previously
/// degraded all text to Delta; Plan 022 §6.1 conservative increment retired).
/// Extracted as a free fn so the run_inner closure stays a single-expression
/// arrow closure (a2r parses `(ev) => expr`, not block-body move closures).
/// `@TaskRef` (by ref): TaskRef is not Clone; send takes &self, so a borrow
/// suffices and avoids a2r's move-reuse clone inference (Plan 019 class D).
fn forward_sse_delta(mut ev: JsonValue, sink: &a2r_std::task::TaskRef<StreamEvent>) {
    let mut ty: String = "".to_string();
    match ev.get("type") {
        Some(t) => ty = t.as_str().unwrap_or_default().to_string(),
        None => {},
    };
    match ev.get("text") {
        Some(t) => {
            let text = t.as_str().unwrap_or_default();
            if text.is_empty() == false {
                if ty == "reasoning" {
                    sink.send(StreamEvent::Thinking(text.to_string()));
                } else {
                    sink.send(StreamEvent::Delta(text.to_string()));
                }
            }
        },
        None => {},
    };
}

/// Pop the front element of a shared string queue (Plan 026 steering /
/// follow-up), or None when empty. The guard is released when this fn returns,
/// so callers can safely mutate agent memory right after.
fn pop_front(q: Arc<Mutex<Vec<String>>>) -> Option<String> {
    let mut guard = q.lock();
    if (guard.len() as i64) > 0 {
        let msg = guard.remove(0);
        return Some(msg);
    }
    return None;
}

/// Copy an AgentResult (used for event payloads, so the returned result stays
/// independent of the running accumulator).
fn clone_result(result: AgentResult) -> AgentResult {
    return AgentResult { output: result.output.to_string(), turns: result.turns, tool_calls: result.tool_calls.clone(), total_tokens: result.total_tokens };
}

/// Build the model id: a pinned id if set, else a "tier:<tier>" token.
fn build_model_id(pinned: &str, mut tier: ModelTier) -> String {
    if pinned.is_empty() == false {
        return pinned.to_string();
    }
    return format!("tier:{}", tier.display_name());
}

/// Assemble the system prompt: optional project context + role soul + optional
/// skills directory block.
fn build_system_prompt(context_block: Option<String>, soul: &str, skills_block: Option<String>) -> String {
    let mut prompt: String = "".to_string();
    match context_block {
        Some(ctx) => {
            if ctx.trim().to_string().is_empty() == false {
                prompt = format!("{}{}", ctx, "\n\n---\n\n");
            }
        },
        None => {},
    };
    prompt = format!("{}{}", prompt, soul);
    match skills_block {
        Some(block) => prompt = format!("{}{}", prompt, block),
        None => {},
    };
    return prompt;
}
