// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

use crate::auto_ai_client::{ClientError, CompletionRequest, ContentBlock, Message, Usage};
use crate::error::{AgentError};
use crate::memory::{Memory};
use crate::agent::{Client};
/// Context compaction (Plan 028, pi parity): when a conversation nears the
/// context window, replace the oldest turns with a structured LLM summary
/// instead of dropping them (the ring-buffer trim loses them forever).
/// 
/// Auto port of rust-ref compaction.rs. Adaptations:
/// - CompactionSettings defaults via [default_compaction_settings] (Auto has
/// no Default trait / field defaults).
/// - `is`-pattern branches over ContentBlock follow the format.at precedent.
/// Compaction thresholds. Defaults follow pi's DEFAULT_COMPACTION_SETTINGS.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct CompactionSettings {
    pub context_window: u32,
    pub reserve_tokens: u32,
    pub keep_recent_tokens: u32,
}

pub fn default_compaction_settings() -> CompactionSettings {
    return CompactionSettings { context_window: 128000 as u32, reserve_tokens: 16384 as u32, keep_recent_tokens: 20000 as u32 };
}

pub fn should_compact(tokens: u32, s: CompactionSettings) -> bool {
    if tokens > s.context_window - s.reserve_tokens {
        return true;
    }
    return false;
}

pub fn is_context_overflow(message: &str) -> bool {
    let lower = message.to_lowercase();
    if lower.contains("rate limit") {
        return false;
    }
    if lower.contains("too many requests") {
        return false;
    }
    if lower.contains("throttling") {
        return false;
    }

    if lower.contains("prompt is too long") {
        return true;
    }
    if lower.contains("request_too_large") {
        return true;
    }

    if lower.contains("exceeds the context window") {
        return true;
    }
    if lower.contains("exceeds the model's maximum context length") {
        return true;
    }
    if lower.contains("exceeds model's maximum context length") {
        return true;
    }
    if lower.contains("maximum context length") {
        return true;
    }
    if lower.contains("context_length_exceeded") {
        return true;
    }

    if lower.contains("exceeds the available context size") {
        return true;
    }
    if lower.contains("exceeded max context length") {
        return true;
    }
    if lower.contains("exceeds the context length") {
        return true;
    }
    if lower.contains("greater than the context length") {
        return true;
    }
    return false;
}

pub fn estimate_tokens(messages: Vec<Message>, last_usage: Option<Usage>) -> u32 {
    let mut base: u32 = 0 as u32;
    match last_usage {
        Some(u) => base = u.total_tokens(),
        None => {},
    };
    let mut total: u32 = base;
    for m in &messages {
        total = total + message_cost(m.clone()) / 4;
    }
    return total;
}

/// The model's context window in tokens.
/// Keep this many tokens of headroom for the answer (pi: 16384).
/// Never compact away the most recent tokens (pi: 20000).
/// The default settings (pi parity: 128k window / 16384 reserve / 20000 keep).
/// True when the estimated context has crossed the compaction threshold.
/// True when an LLM error message indicates the request overflowed the
/// model's context window (Plan 031, pi's OVERFLOW_PATTERNS — cut down to
/// the three provider families we speak + generic error-code forms).
/// Deliberately conservative: an unknown error returns false (the run fails,
/// same as today); a false positive only costs one extra compaction attempt.
/// Rate limiting / throttling look-alikes never count (pi's NON_OVERFLOW).
/// Rough token count: the most recent assistant usage (real accounting, when
/// available) plus a chars/4 estimate of the message list (pi heuristic).
/// Rough char cost of one message (role + content blocks).
fn message_cost(m: Message) -> u32 {
    let mut chars: u32 = ((m.role.len() as i64) as u32);
    for block in &m.content {
        match block {
            ContentBlock::Text { text } => chars = chars + ((text.len() as i64) as u32),
            ContentBlock::ToolUse { id: name, name: _id, input } => {
                chars = chars + ((name.len() as i64) as u32);
                chars = chars + ((input.to_string().len() as i64) as u32);
            },
            ContentBlock::ToolResult { tool_use_id: _tool_use_id, content, is_error: _is_error } => chars = chars + ((content.len() as i64) as u32),
        };
    }
    return chars;
}

/// A human turn boundary: a user message whose first block is plain text
/// (ToolResult users belong to the previous assistant turn's unit).
fn is_turn_boundary(m: Message) -> bool {
    if m.role.to_string() != "user" {
        return false;
    }
    if m.content.is_empty() {
        return false;
    }
    let first = m.content[0].clone();
    match first {
        ContentBlock::Text { text: _t } => return true,
        _ => return false,
    }
}

pub fn find_cut_point(mut messages: Vec<Message>, keep_recent_tokens: u32) -> i64 {
    if (messages.len() as i64) < 2 {
        return -1;
    }

    let mut acc: u32 = 0 as u32;
    let mut start: i64 = ((messages.len() as i64) as i64) - 1;
    let mut settled: bool = false;
    while start >= 0 && settled == false {
        acc = acc + message_cost(messages[(start) as usize].clone()) / 4;
        if acc > keep_recent_tokens {
            start = start + 1;
            settled = true;
        } else {
            if start == 0 {
                return -1;
            }            start = start - 1;
        }

    }
    if settled == false {
        return -1;
    }

    let mut cut: i64 = start;
    while cut < ((messages.len() as i64) as i64) && is_turn_boundary(messages[(cut) as usize].clone()) == false {
        cut = cut + 1;
    }
    if cut >= ((messages.len() as i64) as i64) {
        


        cut = start;
        if cut >= ((messages.len() as i64) as i64) {
            cut = ((messages.len() as i64) as i64) - 1;
        }        while cut > 1 && is_turn_boundary(messages[(cut) as usize].clone()) == false {
            cut = cut - 1;
        }
    }
    if cut <= 1 || cut >= ((messages.len() as i64) as i64) {
        return -1;
    }
    return cut;
}

/// The index at which to cut so the kept tail fits keep_recent_tokens,
/// adjusted to the nearest human-turn boundary (never splits a
/// ToolUse/ToolResult pair). -1 when the memory is too short to compact.
/// File paths touched by the conversation (pi's FileOperations — mechanically
/// extracted from the wire's tool_use blocks, never from LLM output).
/// Auto has no Set, so each bucket is a dedup'd List<str>.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct FileOps {
    pub read: Vec<String>,
    pub written: Vec<String>,
    pub edited: Vec<String>,
}

/// Files read but not modified.
/// Files replaced by full writes.
/// Files modified by targeted edits.
/// True when the list already holds the path (manual dedup — Auto's List has
/// no contains).
fn list_has(list: &Vec<String>, item: &str) -> bool {
    for x in list {
        if x == item {
            return true;
        }
    }
    return false;
}

pub fn extract_file_ops(messages: Vec<Message>) -> FileOps {
    let mut ops = FileOps { read: vec![], written: vec![], edited: vec![] };
    for m in &messages {
        if m.role.to_string() == "assistant" {
            for block in &m.content {
                match block {
                    ContentBlock::ToolUse { id: name, name: _id, input } => {
                        let mut path = a2r_std::json::get_str(&input, "path");
                        if path.is_empty() {
                            path = a2r_std::json::get_str(&input, "file_path");
                        }
                        if path.is_empty() {
                            path = a2r_std::json::get_str(&input, "notebook_path");
                        }
                        if path.is_empty() == false {
                            let lower = name.to_lowercase();
                            if lower.contains("read") {
                                if list_has(&ops.read, path.as_str()) == false {
                                    ops.read.push(path.to_string());
                                }                            } else {
                                if lower.contains("edit") || lower.contains("patch") {
                                    if list_has(&ops.edited, path.as_str()) == false {
                                        ops.edited.push(path.to_string());
                                    }                                } else {
                                    if lower.contains("write") {
                                        if list_has(&ops.written, path.as_str()) == false {
                                            ops.written.push(path.to_string());
                                        }                                    }                                }
                            }
                        }
                    },
                    _ => {},
                };
            }
        }
    }

    let mut kept: Vec<String> = vec![];
    for f in &ops.read {
        let mut modified: bool = false;
        for m2 in &ops.edited {
            if m2 == f {
                modified = true;
            }
        }
        for m3 in &ops.written {
            if m3 == f {
                modified = true;
            }
        }
        if modified == false {
            kept.push(f.clone().clone());
        }
    }
    ops.read = kept.clone();
    return ops;
}

pub fn format_file_operations(ops: FileOps) -> String {
    let mut reads: Vec<String> = ops.read;
    reads.sort_by_key(|f| f.clone());
    let mut edited: Vec<String> = ops.edited;
    edited.sort_by_key(|f| f.clone());
    let mut written: Vec<String> = ops.written;
    written.sort_by_key(|f| f.clone());
    let mut modified: Vec<String> = vec![];
    for e in &edited {
        modified.push(e.clone().clone());
    }
    for w in &written {
        modified.push(w.clone().clone());
    }
    modified.sort_by_key(|f| f.clone());
    let mut sections: Vec<String> = vec![];
    if reads.is_empty() == false {
        let mut block: String = "<read-files>\n".to_string();
        for f in &reads {
            block = format!("{}{}", format!("{}{}", block, f), "\n");
        }
        sections.push(format!("{}{}", block, "</read-files>"));
    }
    if modified.is_empty() == false {
        let mut mblock: String = "<modified-files>\n".to_string();
        for f2 in &modified {
            mblock = format!("{}{}", format!("{}{}", mblock, f2), "\n");
        }
        sections.push(format!("{}{}", mblock, "</modified-files>"));
    }
    if sections.is_empty() {
        return "".to_string();
    }
    let mut out: String = "".to_string();
    let mut first: bool = true;
    for sec in &sections {
        if first {
            first = false;
        } else {
            out = format!("{}{}", out, "\n\n");
        }

        out = format!("{}{}", out, sec);
    }
    return out;
}

/// Extract file operations from wire messages by mechanically scanning
/// assistant tool_use blocks (pi's extractFileOpsFromMessage + computeFileLists).
/// Tool names match loosely ("read"/"write"/"edit"/"patch" substrings) and the
/// path comes from the path / file_path / notebook_path argument fields. A
/// file both read and modified counts as modified only.
/// Render the machine-extracted file manifest (pi's formatFileOperations):
/// read-files / modified-files blocks, empty string when nothing was touched.
/// This is spliced into the summary anchor verbatim — the LLM's own file list
/// is at best a paraphrase of this ground truth.
/// System prompt for the summarizer (pi's structured template).
fn summary_system_prompt() -> String {
    return "You compress a coding-agent conversation history. Produce a terse markdown summary with exactly these sections:\n## Goal\n## Progress\n## Key Decisions\n## Next Steps\nNever invent facts; omit sections with no content. Do not list files — the file manifest is appended mechanically.".to_string();
}

/// Incremental-update instructions (pi's UPDATE_SUMMARIZATION_PROMPT): used
/// when a previous summary exists. The previous summary is embedded in the
/// user message; the model rewrites Goal/Progress/Decisions in place.
fn update_system_prompt() -> String {
    return "You update an existing conversation summary with new messages. PRESERVE all still-relevant information from the previous summary; ADD new progress, decisions, and context; move finished items to done; drop what is no longer relevant. Keep the same sections:\n## Goal\n## Progress\n## Key Decisions\n## Next Steps\nNever invent facts; omit sections with no content. Do not list files — the file manifest is appended mechanically.".to_string();
}

pub async fn compact(mut memory: Memory, client: &Box<dyn Client>, model: &str, settings: CompactionSettings, previous_summary: Option<String>) -> Result<(Memory, String), AgentError> {
    let msgs = memory.messages();
    let cut = find_cut_point(msgs.clone(), settings.keep_recent_tokens);
    if cut < 1 {
        return Err(AgentError::Config("memory too short to compact".to_string()));
    }
    let mut transcript: String = "".to_string();
    let mut i: i64 = 0;
    while i < cut {
        let mut m = msgs[(i) as usize].clone();
        transcript = format!("{}{}", transcript, format!("[{}] ", m.role));
        for block in &m.content {
            match block {
                ContentBlock::Text { text } => transcript = format!("{}{}", format!("{}{}", transcript, text), "\n"),
                ContentBlock::ToolUse { id: name, name: _id, input } => transcript = format!("{}{}", transcript, format!("(tool_use {} {})
", name, input.to_string())),
                ContentBlock::ToolResult { tool_use_id: _tool_use_id, content, is_error: _is_error } => transcript = format!("{}{}", transcript, format!("(tool_result {})
", content)),
            };
        }
        i = i + 1;
    }



    let mut prefix: Vec<Message> = vec![];
    let mut pi: i64 = 0;
    while pi < cut {
        prefix.push(msgs[(pi) as usize].clone());
        pi = pi + 1;
    }
    let file_manifest = format_file_operations(extract_file_ops(prefix));


    let mut system = summary_system_prompt();
    let mut user_msg: String = format!("{}{}", "Summarize this conversation history for continuation:\n\n", transcript);
    match previous_summary {
        Some(prev) => {
            system = update_system_prompt();
            user_msg = format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", "Update the existing summary with this new conversation history.\n\n<previous-summary>\n", prev), "\n</previous-summary>\n\n<conversation>\n"), transcript), "\n</conversation>\n\nProduce the updated summary now.");
        },
        None => {},
    };

    let mut blocks: Vec<ContentBlock> = vec![];
    let tb = ContentBlock::Text { text: user_msg };
    blocks.push(tb.clone());
    let req = CompletionRequest { model: model.to_string(), messages: vec![Message { role: "user".to_string(), content: blocks }], max_tokens: None, temperature: Some(0.0), system_prompt: Some(system), tools: vec![], stream: false, preferred_provider: None };
    let resp = client.complete(req).await?;
    match resp.error {
        Some(err) => return Err(AgentError::Config(format!("compaction summary error: {}", err))),
        None => {},
    };



    let mut summary = resp.content.trim().to_string();
    if file_manifest.is_empty() == false {
        summary = format!("{}{}", format!("{}{}", summary, "\n\n"), file_manifest);
    }



    let mut mut_memory = Memory::new(memory.limit());
    let mut j: i64 = 0;
    while j < cut {
        let mut m = msgs[(j) as usize].clone();
        if m.role.to_string() == "system" {
            mut_memory.add_message(m);
        }
        j = j + 1;
    }
    mut_memory.add("user", format!("[Compacted conversation summary — older turns were summarized to save context]

{}", summary).as_str());
    let mut k: i64 = cut;
    while k < ((msgs.len() as i64) as i64) {
        mut_memory.add_message(msgs[(k) as usize].clone());
        k = k + 1;
    }
    return Ok((mut_memory, summary));
}
