// Auto-generated by a2r transpiler

use auto_atom::*;
use auto_val::*;
use serde::Deserialize;
use crate::error::{AgentError};
use crate::role_def::{Role};
use crate::builtin_roles::{load_builtin};
use crate::ai_config::{ModelTier};
/// Parsing + inherit/merge for `.at` Role config files.
/// 
/// Auto port of config/role_config.rs (auto-ai v0.4.0).
/// 
/// BRIDGE NOTE (plan 013): like loader.at, this bridges auto_atom/auto_val.
/// a2r-first — AutoVM can't resolve the bridged types; runs under cargo.
/// Deserialization view for `role { … }` blocks. Field names map 1:1 to `.at`
/// props; `#[serde(default)]` makes every field optional. `temperature` /
/// `tools` / `tools_append` / `allowed_tiers` / `skills` use `deserialize_with`
/// helpers from auto-val (lenient parsing). Tier-typed fields are deserialized
/// as raw strings and run through `parse_tier_field` after (ModelTier is
/// ai-config domain logic, not a serde helper). Mirrors rust-ref RoleDecl.
#[derive(Debug, Deserialize)]
struct RoleDecl {
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    pub description: Option<String>,
    #[serde(default)]
    pub model: Option<String>,
    #[serde(default)]
    pub model_tier: Option<String>,
    #[serde(default, deserialize_with = "auto_val::lenient_f64_opt")]
    pub temperature: Option<f64>,
    #[serde(default)]
    pub max_turns: Option<u32>,
    #[serde(default)]
    pub memory_limit: Option<u32>,
    #[serde(default)]
    pub system_prompt: Option<String>,
    #[serde(default)]
    pub system_prompt_append: Option<String>,
    #[serde(default)]
    pub inherit: Option<String>,
    #[serde(default, deserialize_with = "auto_val::string_or_list_opt")]
    pub tools: Option<Vec<String>>,
    #[serde(default, deserialize_with = "auto_val::string_or_list_opt")]
    pub tools_append: Option<Vec<String>>,
    #[serde(default, deserialize_with = "auto_val::string_or_list_opt")]
    pub allowed_tiers: Option<Vec<String>>,
    #[serde(default, deserialize_with = "auto_val::string_or_list_opt")]
    pub skills: Option<Vec<String>>,
    #[serde(default)]
    pub token_budget: Option<u32>,
    #[serde(default)]
    pub soul_file: Option<String>,
}

/// The parsed representation of a `role { … }` block. Every field is optional
/// so an `inherit`-based config only overrides what it sets.
#[derive(Clone, Debug, PartialEq)]
pub struct RoleConfig {
    pub name: Option<String>,
    pub description: Option<String>,
    pub model: Option<String>,
    pub model_tier: Option<ModelTier>,
    pub temperature: Option<f64>,
    pub max_turns: Option<u32>,
    pub system_prompt: Option<String>,
    pub system_prompt_append: Option<String>,
    pub tools: Option<Vec<String>>,
    pub tools_append: Option<Vec<String>>,
    pub inherit: Option<String>,
    pub memory_limit: Option<u32>,
    pub allowed_tiers: Option<Vec<ModelTier>>,
    pub skills: Option<Vec<String>>,
    pub token_budget: Option<u32>,
    pub soul_file: Option<String>,
}

impl RoleConfig {
    pub fn empty() -> RoleConfig {
        return RoleConfig { name: None, description: None, model: None, model_tier: None, temperature: None, max_turns: None, system_prompt: None, system_prompt_append: None, tools: None, tools_append: None, inherit: None, memory_limit: None, allowed_tiers: None, skills: None, token_budget: None, soul_file: None };
    }
    pub fn merge_over(&self, base: RoleConfig) -> RoleConfig {
        let mut r: RoleConfig = base.clone();

        match self.name.clone() {
            Some(v) => r.name = Some(v),
            None => {},
        };
        match self.description.clone() {
            Some(v) => r.description = Some(v),
            None => {},
        };
        match self.model.clone() {
            Some(v) => r.model = Some(v),
            None => {},
        };
        match self.model_tier.clone() {
            Some(v) => r.model_tier = Some(v),
            None => {},
        };
        match self.temperature.clone() {
            Some(v) => r.temperature = Some(v),
            None => {},
        };
        match self.max_turns.clone() {
            Some(v) => r.max_turns = Some(v),
            None => {},
        };
        match self.system_prompt.clone() {
            Some(v) => r.system_prompt = Some(v),
            None => {},
        };
        match self.memory_limit.clone() {
            Some(v) => r.memory_limit = Some(v),
            None => {},
        };
        match self.inherit.clone() {
            Some(v) => r.inherit = Some(v),
            None => {},
        };
        match self.allowed_tiers.clone() {
            Some(v) => r.allowed_tiers = Some(v),
            None => {},
        };
        match self.skills.clone() {
            Some(v) => r.skills = Some(v),
            None => {},
        };
        match self.token_budget.clone() {
            Some(v) => r.token_budget = Some(v),
            None => {},
        };
        match self.soul_file.clone() {
            Some(v) => r.soul_file = Some(v),
            None => {},
        };

        match base.system_prompt_append {
            Some(extra) => {
                match self.system_prompt_append.clone() {
                    Some(mine) => r.system_prompt_append = Some(format!("{}
{}", extra, mine)),
                    None => r.system_prompt_append = Some(extra),
                };
            },
            None => r.system_prompt_append = self.system_prompt_append.clone(),
        };

        match self.tools.clone() {
            Some(replace) => r.tools = Some(replace),
            None => {},
        };
        match self.tools_append.clone() {
            Some(extra) => {
                



                let mut combined: Vec<String> = vec![];
                match r.tools.clone() {
                    Some(existing) => combined = existing,
                    None => {},
                };
                for t in &extra {
                    combined.push(t.clone().clone());
                }
                r.tools = Some(combined);
            },
            None => {},
        };
        return r;
    }
}

/// Merge self over base, applying design-doc §4.4 rules:
/// - scalar fields override when Some;
/// - system_prompt_append accumulates;
/// - tools replaces; tools_append extends.
/// A Role whose behavior is driven by a parsed RoleConfig. When a field is
/// None, it falls back to the inherited base Role (if any).
#[allow(dead_code)]
pub struct ConfigRole {
    pub cfg: RoleConfig,
    pub base: Option<Box<dyn Role>>,
}

impl Role for ConfigRole {
    fn name(&self) -> String {
        return self.cfg.name.clone().unwrap_or(self.base_name());
    }
    fn system_prompt(&self) -> String {
        let mut prompt = self.base_prompt();
        match self.cfg.system_prompt.clone() {
            Some(p) => prompt = p,
            None => {},
        };
        match self.cfg.system_prompt_append.clone() {
            Some(extra) => return format!("{}
{}", prompt, extra),
            None => return prompt,
        }
    }
    fn model_tier(&self) -> ModelTier {
        return self.cfg.model_tier.clone().unwrap_or(self.base_tier());
    }
    fn model(&self) -> String {
        return self.cfg.model.clone().unwrap_or(self.base_model_str());
    }
    fn temperature(&self) -> f64 {
        return self.cfg.temperature.clone().unwrap_or(self.base_temp());
    }
    fn max_turns(&self) -> u32 {
        return self.cfg.max_turns.clone().unwrap_or(self.base_turns());
    }
    fn allowed_tools(&self) -> Vec<String> {
        return self.cfg.tools.clone().unwrap_or_default();
    }
    fn memory_limit(&self) -> Option<u32> {
        match self.cfg.memory_limit.clone() {
            Some(n) => return Some(n as u32),
            None => return Some(20),
        }
    }
    fn skills(&self) -> Vec<String> {
        return self.cfg.skills.clone().unwrap_or_default();
    }
}

impl ConfigRole {
    pub fn base_name(&self) -> String {
        return "unnamed".to_string();
    }
    pub fn base_prompt(&self) -> String {
        return "".to_string();
    }
    pub fn base_tier(&self) -> ModelTier {
        return ModelTier::Mid;
    }
    pub fn base_model_str(&self) -> String {
        return "".to_string();
    }
    pub fn base_temp(&self) -> f64 {
        return 0.3;
    }
    pub fn base_turns(&self) -> u32 {
        return 10;
    }
    pub fn base_mem(&self) -> Option<u32> {
        return Some(20);
    }
}

pub fn config_role_new(cfg: RoleConfig) -> ConfigRole {
    return ConfigRole { cfg: cfg, base: None };
}

pub fn config_role_with_base(cfg: RoleConfig, base: Box<dyn Role>) -> ConfigRole {
    return ConfigRole { cfg: cfg, base: Some(base) };
}

pub fn parse_at_role(content: &str) -> Result<RoleConfig, AgentError> {
    match auto_atom::AtomParser::parse(content) {
        Ok(atom) => {
            match atom {
                Atom::Node(node) => {
                    




                    match node.deserialize::<RoleDecl>() {
                        Ok(d) => {
                            

                            let mut cfg = RoleConfig::empty();
                            cfg.name = d.name;
                            cfg.description = d.description;
                            cfg.model = d.model;
                            match d.model_tier {
                                Some(s) => cfg.model_tier = parse_tier_field(s.as_str()),
                                None => {},
                            };
                            cfg.temperature = d.temperature;
                            cfg.max_turns = d.max_turns;
                            cfg.memory_limit = d.memory_limit;
                            cfg.system_prompt = d.system_prompt;
                            cfg.system_prompt_append = d.system_prompt_append;
                            cfg.tools = d.tools;
                            cfg.tools_append = d.tools_append;
                            cfg.inherit = d.inherit;
                            cfg.soul_file = d.soul_file;
                            cfg.token_budget = d.token_budget;
                            cfg.skills = d.skills;
                            match d.allowed_tiers {
                                Some(names) => {
                                    let mut tiers: Vec<ModelTier> = vec![];
                                    for nm in &names {
                                        match parse_tier_field(nm.as_str()) {
                                            Some(t) => tiers.push(t.clone().clone()),
                                            None => {},
                                        };
                                    }
                                    cfg.allowed_tiers = Some(tiers);
                                },
                                None => {},
                            };
                            return Ok(cfg);
                        },
                        Err(e) => return Err(AgentError::Config(format!("failed to deserialize role block: {}", e))),
                    };
                },
                _ => return Err(AgentError::Config("expected a 'role' node".to_string())),
            };
        },
        Err(e) => return Err(AgentError::Config(format!("failed to parse role .at: {}", e))),
    }
}

pub fn load_role(content: &str) -> Result<RoleConfig, AgentError> {
    match parse_at_role(content) {
        Ok(cfg) => {
            let mut result = cfg;
            





            match result.inherit.clone() {
                Some(name) => {
                    






                    match load_builtin(name.as_str()) {
                        Some(base_role) => {
                            




                        },
                        None => return Err(AgentError::Config(format!("inherit: unknown role '{}'", name))),
                    };
                },
                None => {},
            };
            return Ok(result);
        },
        Err(e) => return Err(e),
    }
}

pub fn parse_tier_field(s: &str) -> Option<ModelTier> {
    return ModelTier::parse_name(s);
}

pub fn serialize_at_role(cfg: RoleConfig) -> String {
    let mut lines: Vec<String> = vec!["role {".to_string()];
    match cfg.name {
        Some(v) => lines.push(format!("    name : \"{}\"", v)),
        None => {},
    };
    match cfg.model {
        Some(v) => lines.push(format!("    model : \"{}\"", v)),
        None => {},
    };
    match cfg.model_tier {
        Some(t) => lines.push(format!("    model_tier : {}", t.display_name())),
        None => {},
    };
    match cfg.temperature {
        Some(v) => lines.push(format!("    temperature : {}", v)),
        None => {},
    };
    match cfg.max_turns {
        Some(v) => lines.push(format!("    max_turns : {}", v)),
        None => {},
    };
    match cfg.system_prompt {
        Some(v) => lines.push(format!("    system_prompt : \"{}\"", v)),
        None => {},
    };
    match cfg.inherit {
        Some(v) => lines.push(format!("    inherit : \"{}\"", v)),
        None => {},
    };
    lines.push("}".to_string());
    return lines.join("\n");
}
