// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

use std::sync::Arc;
use std::pin::Pin;
use std::future::Future;
use async_trait;
use crate::wire::{ToolDefinition, JsonValue};
use crate::error::{ToolError};
/// The [Tool] spec and [ToolRegistry].
/// 
/// Apps register concrete tools (file IO, shell, search, ...) and the
/// [agent.Agent] exposes them to the model as callable functions. A
/// [role_def.Role] can restrict which tools are visible via allowed_tools().
/// 
/// Auto port of crates/auto-ai-agent/src/tool.rs (auto-ai v0.4.0).
/// 
/// Adaptations:
/// - `Arc<dyn Tool>` → `Arc(Tool)` (Auto `spec` is dynamically dispatched).
/// - `async fn execute` → `fn execute ~...` (plan 013 async decision).
/// - ToolRegistry stores a parallel `names List<str>` because Auto's VM Map
/// has no iteration API (plan 013 gotcha B5). Fields are `pub` (B12).
/// A tool's structured result: two channels so the model's context and the
/// UI's payload never fight over one string.
#[derive(Clone, Debug, PartialEq)]
pub struct ToolOutput {
    pub content: String,
    pub details: Option<JsonValue>,
}

impl ToolOutput {
    pub fn text(s: &str) -> ToolOutput {
        return ToolOutput { content: s.to_string(), details: None };
    }
}

#[async_trait::async_trait]
pub trait Tool: Send + Sync {
    fn name(&self) -> String;
    fn description(&self) -> String;
    fn parameters(&self) -> JsonValue{



        return a2r_std::json::parse("{\"type\":\"object\",\"properties\":{}}");
    }    async fn execute(&self, args: JsonValue) -> Result<ToolOutput, ToolError>;
}


pub fn tool_to_definition(tool: Arc<dyn Tool>) -> ToolDefinition {
    return ToolDefinition::new(tool.name(), tool.description(), tool.parameters());
}

/// The text fed back to the LLM (goes into the ToolResult content block).
/// Structured payload for UI / logs / approval flows. NEVER enters the LLM
/// context — the agent loop attaches it to StreamEvent.Tool only.
/// Shape is tool-specific and weakly typed (pi uses runtime-typed details
/// too); conventions: edit → {diff, patch, first_changed_line},
/// run_command → {truncation, full_output_path}, read → {truncation}.
/// Plain-text output with no details.
/// A callable tool the agent can hand to the LLM.
/// 
/// Implementors supply the metadata the model sees (name/description/
/// parameters) and an async execute.
/// Tool name (must be unique within a registry).
/// Human/LLM-facing description — the model uses this to decide whether to
/// call the tool.
/// JSON-Schema fragment describing the tool's `input` object.
/// Run the tool with the model-supplied arguments. content is fed back
/// to the model; details is a structured payload for the UI (dropped
/// before the LLM request is built).
/// Convert a [Tool] into the Layer-2 [ToolDefinition] the client sends.
/// Registry of tools keyed by name.
/// 
/// Stores tools as `Arc<Tool>` (Auto spec → a2r renders `Arc<Box<dyn Tool>>`).
/// The Arc matches the Rust original's `Arc<dyn Tool>` for shared ownership
/// across agents / workflow steps. Carries a parallel `names List<str>` for
/// iteration (Auto VM Map has no keys()/entries()).
#[derive(Clone)]
pub struct ToolRegistry {
    pub tools: std::collections::HashMap<String, Arc<dyn Tool>>,
    pub names: Vec<String>,
}

impl ToolRegistry {
    pub fn new() -> ToolRegistry {
        return ToolRegistry { tools: std::collections::HashMap::new(), names: vec![] };
    }
    pub fn register_shared(&mut self, tool: Arc<dyn Tool>) {
        let n = tool.name();
        if self.tools.contains_key(&n) == false {
            self.names.push(n.to_string());
        }
        self.tools.insert(n, tool);
    }
    pub fn register(&mut self, mut tool: Box<dyn Tool>) {
        let n = tool.name();
        if self.tools.contains_key(&n) == false {
            self.names.push(n.to_string());
        }


        self.tools.insert(n, Arc::from(tool));
    }
    pub fn get(&self, name: &str) -> Option<Arc<dyn Tool>> {



        match self.tools.get(name) {
            Some(t) => return Some(t.clone()),
            None => return None,
        }
    }
    pub fn names(&self) -> Vec<String> {
        return self.names.clone();
    }
    pub fn len(&self) -> u32 {
        return ((self.names.len() as i64) as u32);
    }
    pub fn is_empty(&self) -> bool {
        return (self.names.len() as i64) == 0;
    }
    pub fn filter(&self, mut filter: Vec<String>) -> Vec<Arc<dyn Tool>> {
        let mut out: Vec<Arc<dyn Tool>> = vec![];
        if (filter.len() as i64) == 0 {
            for n in self.names.clone() {
                match self.tools.get(n.as_str()) {
                    Some(t) => out.push(t.clone()),
                    None => {},
                };
            }
            return out;
        }
        for n in &filter {
            match self.tools.get(n.as_str()) {
                Some(t) => out.push(t.clone()),
                None => {},
            };
        }
        return out;
    }
    pub async fn execute(&self, name: &str, args: JsonValue) -> Result<ToolOutput, ToolError> {
        match self.get(name) {
            Some(tool) => return tool.execute(args).await,
            None => return Err(ToolError::Exec(format!("tool not found: {}", name))),
        }
    }
    pub async fn exec_or_msg(&self, name: &str, args: JsonValue) -> ToolOutput {
        match self.execute(name, args).await {
            Ok(out) => return out,
            Err(ToolError::SecurityDenied { kind, path, root, hint }) => return ToolOutput::text(format!("[security denied ({})] '{}' is outside the workspace root '{}'. {} (workspace 外的文件 AI 无法读取，请让用户提供内容或改用 API)", kind, path, root, hint).as_str()),
            Err(e) => return ToolOutput::text(format!("[tool error: {}]", e.message()).as_str()),
        }
    }
}
