// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

const DEFAULT_DAEMON_URL: &str = "http://127.0.0.1:17654";

pub fn default_daemon_url() -> String {
    return DEFAULT_DAEMON_URL.to_string();
}

pub fn daemon_url() -> String {
    let v = a2r_std::env::get("AAID_URL");
    if v.is_empty() {
        return DEFAULT_DAEMON_URL.to_string();
    }
    return v;
}

pub fn is_running() -> bool {
    let url: String = format!("{}/v1/status", daemon_url());

    let resp = a2r_std::http::request("GET", url.as_str()).timeout(500).send();
    return resp.status_code() >= 200 && resp.status_code() < 300;
}

pub fn is_running_async() -> bool {
    return is_running();
}

pub fn ensure_daemon() -> Option<String> {

    if is_running() {
        return Some(daemon_url());
    }


    match find_aaid_binary() {
        Some(aaid_path) => {
            

            if spawn_daemon(aaid_path.as_str()) == false {
                return None;
            }
            

            let deadline: i32 = a2r_std::time::now_ms() + 3000;
            while a2r_std::time::now_ms() < deadline {
                a2r_std::time::sleep_ms(100 as u64);
                if is_running() {
                    return Some(daemon_url());
                }
            }
            

            return None;
        },
        None => return None,
    }
}

pub fn ensure_daemon_async() -> Option<String> {
    if is_running_async() {
        return Some(daemon_url());
    }
    match find_aaid_binary() {
        Some(aaid_path) => {
            if spawn_daemon(aaid_path.as_str()) == false {
                return None;
            }
            let deadline: i32 = a2r_std::time::now_ms() + 10000;
            loop {
                if is_running_async() {
                    return Some(daemon_url());
                }
                if a2r_std::time::now_ms() >= deadline {
                    break;
                }
                a2r_std::time::sleep_ms(200 as u64);
            }
            return None;
        },
        None => return None,
    }
}

/// Daemon discovery + lazy start (ssh-agent model).
/// 
/// When any app creates an `AiClient` via `AiClient.new`, this module checks
/// if `aaid` is running. If not, it finds and spawns the daemon binary, then
/// waits for it to be ready. If the daemon can't be found or started, `new()`
/// returns `Err(DaemonUnavailable)` — callers then use `AiClient.with_url` to
/// point at a known daemon URL instead.
/// 
/// Auto port of crates/auto-ai-client/src/daemon.rs (auto-ai v0.4.0).
/// 
/// Note: the Rust original has both blocking and `async` variants of
/// `is_running` / `ensure_daemon` (the blocking ones panic inside a tokio
/// runtime — review-003 M6). Auto's `http.request` / `process.spawn` are not
/// bound to a reactor, so a single synchronous implementation suffices; the
/// `_async` variants simply alias to the sync ones for API parity.
/// Default daemon URL.
/// The default daemon URL (mirrors the Rust `pub const DEFAULT_DAEMON_URL`).
/// The daemon URL (overridable via `$AAID_URL`).
/// Check if the daemon is running by probing `/v1/status`.
/// Async version of [is_running] — kept for API parity with the Rust original.
/// (Auto's http client is not reactor-bound, so this is just an alias.)
/// Ensure the daemon is running. If not, try to start it.
/// Returns `Some(url)` if daemon is available, `None` if not (caller should
/// fall back to [AiClient.with_url] or surface an error).
/// Async version of [ensure_daemon] — kept for API parity. Uses a longer
/// (10s) ready-wait to match the Rust async variant (daemon loads config).
/// Find the `aaid` binary by searching:
/// 1. `$AAID_PATH` env var
/// 2. `PATH` lookup (`aaid` / `aaid.exe`)
/// 3. Dev relative paths (auto-ai repo target dir)
fn find_aaid_binary() -> Option<String> {

    let explicit = a2r_std::env::get("AAID_PATH");
    if explicit.is_empty() == false {
        if a2r_std::fs::exists(explicit.as_str()) {
            return Some(explicit);
        }    }


    let exe_name = if is_windows() {
        "aaid.exe".to_string()
    } else {
        "aaid".to_string()
    };
    match which(exe_name.as_str()) {
        Some(p) => return Some(p),
        None => {},
    };


    let rels: Vec<String> = vec!["../../auto-ai/target/debug/aaid".to_string(), "../../auto-ai/target/debug/aaid.exe".to_string(), "../auto-ai/target/debug/aaid".to_string(), "../../../auto-ai/target/debug/aaid".to_string(), "../../../auto-ai/target/debug/aaid.exe".to_string()];
    for rel in &rels {
        if a2r_std::fs::exists(rel.as_str()) {
            return Some(rel.clone());
        }
    }
    return None;
}

/// Whether the current platform is Windows.
/// 
/// Auto's VM has no `cfg!(windows)` compile-time check, so this inspects
/// several runtime signals (B9 robustness): the `OS` env var (Windows shells
/// set `OS=Windows_NT`), the `ComSpec`/`COMSPEC` env var (points at cmd.exe),
/// and the PATH separator convention. Any one of these suffices — the
/// multi-signal approach is robust to stripped environments where a single
/// signal (e.g. `OS`) may be unset.
fn is_windows() -> bool {
    if a2r_std::env::get("OS").contains("Windows") {
        return true;
    }
    let comspec = a2r_std::env::get("ComSpec");
    if comspec.is_empty() == false {
        if a2r_std::str_contains(comspec.as_str(), "cmd.exe") || a2r_std::str_contains(comspec.as_str(), "COMMAND.COM") {
            return true;
        }    }

    let path = a2r_std::env::get("PATH");
    if a2r_std::str_contains(path.as_str(), ";") && a2r_std::str_contains(path.as_str(), ":") == false {
        return true;
    }
    return false;
}

/// The PATH separator (`;` on Windows, `:` elsewhere).
fn path_sep() -> String {
    if is_windows() {
        return ";".to_string();
    }
    return ":".to_string();
}

/// Simple `which` implementation: search $PATH for `exe`.
fn which(exe: &str) -> Option<String> {
    let path = a2r_std::env::get("PATH");
    if path.is_empty() {
        return None;
    }
    let sep = path_sep();
    for dir in path.split(&sep).collect::<Vec<_>>() {
        if dir.is_empty() {
            

        } else {
            let candidate: String = format!("{}/{}", dir, exe);
            if a2r_std::fs::exists(candidate.as_str()) {
                

                if candidate.ends_with(".exe") == false && is_windows() {
                    let with_exe: String = format!("{}{}", candidate, ".exe");
                    if a2r_std::fs::exists(with_exe.as_str()) {
                        return Some(with_exe);
                    }                }                return Some(candidate);
            }        }

    }
    return None;
}

/// Spawn the daemon binary as a detached background process.
/// 
/// PLATFORM LIMIT (B10): Rust detaches the daemon's stdio via
/// `.stdin(Stdio::null()).stdout(Stdio::null()).stderr(Stdio::null())`
/// (daemon.rs:177-179). Auto's `process.spawn` takes only an arg list and
/// exposes no stdio redirection, so the daemon may inherit the parent's
/// stdout/stderr. The a2r→Rust path restores the null-stdio detachment; the
/// pure-VM path leaves this to Auto's process.spawn defaults.
fn spawn_daemon(aaid_path: &str) -> bool {


    let pid = a2r_std::process::spawn(vec![aaid_path.to_string()]);
    return pid > 0;
}
