// Auto-generated by a2r transpiler

/// Client errors.
/// 
/// The client is a thin daemon HTTP client, so its error surface is small:
/// the daemon isn't reachable, the HTTP call failed, or the daemon returned an
/// error response.
/// 
/// Auto port of crates/auto-ai-client/src/error.rs (auto-ai v0.4.0).
/// Unified error type for the (thin) daemon client.
/// The daemon could not be discovered or started.
/// The HTTP request to the daemon failed (network/transport).
/// The daemon returned a non-success response or the body failed to parse.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum ClientError {
    DaemonUnavailable,
    Http(String),
    Api(String),
}


impl ClientError {
    fn message(&self) -> String {
        match self {
            ClientError::DaemonUnavailable => return "daemon unavailable".to_string(),
            ClientError::Http(e) => return format!("HTTP error: {}", e),
            ClientError::Api(e) => return format!("API error: {}", e),
        }
    }
    fn from_http_error(msg: &str) -> ClientError {
        return ClientError::Http(msg.to_string());
    }
}
impl std::fmt::Display for ClientError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.message())
    }
}
impl std::error::Error for ClientError {}
