// Auto-generated by a2r transpiler
#![allow(dead_code, unreachable_code, unused_imports, unused_mut, unused_parens, unused_assignments, unused_variables)]

// ── extern-crate shims (a2r emits `use crate::<these>::...`) ────────────────
pub mod ai_config {
    pub use ::ai_config::*;
}
// JsonValue alias (a2r can't express `serde_json::Value as JsonValue`; the .at
// sources use the short name JsonValue which resolves here via ai_config).
pub type JsonValue = serde_json::Value;
pub mod daemon;
pub mod error;

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

pub use std::sync::Arc;
pub use crate::error::{ClientError};
pub use crate::ai_config::{CompletionRequest, CompletionResponse, ContentBlock, Message, ModelMeta, ToolCall, ToolDefinition, Usage};
/// AutoOS AI client — a thin daemon HTTP client.
/// 
/// This client sends **canonical** [CompletionRequest]s to the `aaid` daemon
/// and receives canonical [CompletionResponse]s back. It carries no provider
/// knowledge and has no "direct" (LLM-direct) mode — the daemon owns all LLM
/// communication and canonical↔provider translation. The client's only other
/// responsibility is auto-discovering (and lazy-starting) the daemon via
/// [daemon.ensure_daemon].
/// 
/// Canonical wire types (`Message`, `ContentBlock`, `CompletionRequest`, …)
/// are defined in the `ai-config` crate.
/// 
/// Two modes of constructing a client:
/// - [AiClient.new] — discover/start the daemon, error if unreachable.
/// - [AiClient.with_url] — talk to a daemon at an explicit URL (testing).
/// 
/// Auto port of crates/auto-ai-client/src/lib.rs (auto-ai v0.4.0).
/// 
/// a2r-FIRST NOTE: the Rust original relies on `reqwest` (async HTTP),
/// `serde_json` (wire serialization), and `futures::StreamExt` (SSE). Auto's VM
/// has `http.request`/`http.post_stream_with_headers` and a `json` module, but
/// the generic `json.encode[T]`/`json.decode[T]` and list-valued encoding do
/// not yet round-trip correctly in the pure VM interpreter. This file is
/// therefore written to be **correct as Auto source and to transpile cleanly to
/// Rust** (where serde_json + reqwest provide the real behavior). The pure-VM
/// path is exercised only for the non-IO pieces (SseBuffer, error formatting).
/// The daemon HTTP client. See the crate docs for the (canonical) wire format.
/// 
/// Unlike the Rust original (which holds a `reqwest::Client`), the Auto port
/// stores only the URL and issues each request via the global `http` module —
/// Auto's HTTP client is connection-pooled internally.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct AiClient {
    pub url: String,
}

impl AiClient {
    pub fn new() -> Result<AiClient, ClientError> {
        match daemon::ensure_daemon() {
            Some(url) => return Ok(AiClient { url: url.to_string() }),
            None => return Err(ClientError::DaemonUnavailable),
        }
    }
    pub fn with_url(url: &str) -> AiClient {
        return AiClient { url: url.to_string() };
    }
    pub fn default() -> AiClient {
        return AiClient::with_url(daemon::daemon_url().as_str());
    }
    pub fn url(&self) -> String {
        return self.url.clone();
    }
    pub fn is_daemon_mode(&self) -> bool {
        return true;
    }
    pub async fn complete(&self, req: CompletionRequest) -> Result<CompletionResponse, ClientError> {
        let endpoint: String = format!("{}/v1/chat/completions", self.url);
        let body = serde_json::to_string(&req).unwrap_or_default();
        let resp = a2r_std::http::request("POST", endpoint.as_str()).header("Content-Type", "application/json").header("X-App-Name", "auto-ai-client").body(body).send();

        let status = resp.status_code();


        if status < 200 || status >= 300 {
            if status == 0 {
                return Err(ClientError::Http(format!("request to {} failed", endpoint)));
            }            



            let text = bytes_to_str(resp.body_bytes());
            return Err(ClientError::Api(format!("daemon {}: {}", status, text)));
        }


        let text = bytes_to_str(resp.body_bytes());
        match serde_json::from_str::<CompletionResponse>(text.as_str()) {
            Ok(parsed) => return Ok(parsed),
            Err(e) => return Err(ClientError::Api(format!("parse response: {}", e))),
        }
    }
    pub async fn complete_stream(&self, mut req: CompletionRequest, on_event: Arc<dyn Fn(JsonValue) + Send + Sync>) -> Result<CompletionResponse, ClientError> {
        let mut sreq: CompletionRequest = req.clone();
        sreq.stream = true;

        let endpoint: String = format!("{}/v1/chat/completions", self.url);
        let body = serde_json::to_string(&sreq).unwrap_or_default();
        let mut stream = a2r_std::http::post_stream_with_headers(endpoint.as_str(), body.as_str(), "Content-Type: application/json\nX-App-Name: auto-ai-client");

        let mut sse = SseBuffer::new();
        let mut full: String = "".to_string();

        let mut tool_calls: Vec<ToolCall> = vec![];
        let mut stop_reason: Option<String> = None;
        let mut usage: Option<Usage> = None;
        let mut model: String = "".to_string();
        let mut model_meta: Option<ModelMeta> = None;
        let mut error_msg: Option<String> = None;




        while stream.is_done() == 0 {
            let chunk = stream.next();
            if chunk.is_empty() == false {
                for data_line in sse.push(chunk.as_str()) {
                    match a2r_std::json::parse_opt(data_line.as_str()) {
                        Some(value) => {
                            full = format!("{}{}", full, text_of(value.clone()));
                            let event_type = value.get("type").and_then(|v| v.as_str()).unwrap_or_default().to_string();
                            match event_type.as_str() {
                                "error" => error_msg = Some(value.get("message").and_then(|v| v.as_str()).unwrap_or_default().to_string()),
                                "done" => {
                                    tool_calls = parse_tool_calls(value.clone());
                                    stop_reason = opt_str_field(value.clone(), "stop_reason");
                                    model = value.get("model").and_then(|v| v.as_str()).unwrap_or_default().to_string();
                                    model_meta = parse_model_meta(value.clone());
                                    usage = parse_usage(value.clone());
                                },
                                _ => {},
                            };
                            on_event(value);
                        },
                        None => {},
                    };
                }
            }
        }

        for data_line in sse.finish() {
            match a2r_std::json::parse_opt(data_line.as_str()) {
                Some(value) => {
                    full = format!("{}{}", full, text_of(value.clone()));
                    match value.get("type").and_then(|v| v.as_str()).unwrap_or_default() {
                        "error" => error_msg = Some(value.get("message").and_then(|v| v.as_str()).unwrap_or_default().to_string()),
                        "done" => {
                            tool_calls = parse_tool_calls(value.clone());
                            stop_reason = opt_str_field(value.clone(), "stop_reason");
                            model = value.get("model").and_then(|v| v.as_str()).unwrap_or_default().to_string();
                            model_meta = parse_model_meta(value.clone());
                            usage = parse_usage(value.clone());
                        },
                        _ => {},
                    };
                    on_event(value);
                },
                None => {},
            };
        }

        return Ok(CompletionResponse { content: full, tool_calls: tool_calls, stop_reason: stop_reason, usage: usage, model: model, error: error_msg, model_meta: model_meta });
    }
}

/// Create a client. Auto-discovers the daemon (lazy-starting it if needed,
/// ssh-agent model). Errors if the daemon can't be reached.
/// Create a client pointed at an explicit daemon URL (for testing).
/// Default: honor `$AAID_URL` instead of hardcoding the default port, so
/// tests and callers that set the env var aren't surprised (plan 011 L6).
/// Mirrors Rust's `impl Default for AiClient` (lib.rs:210-216).
/// The daemon URL this client talks to.
/// Always true (the client is daemon-only).
/// Metadata passthrough note (Plan 031): unlike the rust-ref track, the
/// Auto track keeps no client-level last_model_meta cache — the agent
/// consumes CompletionResponse.model_meta directly on every turn, which
/// is the load-bearing path; the rust-ref cache is a convenience API.
/// Send a canonical completion request, receive a canonical response.
/// 
/// Async per the plan's `async fn → fn … ~T` mapping.
/// Send a **streaming** completion request. Sets `stream: true` and reads
/// the daemon's SSE response, invoking `on_event` for each parsed event.
/// 
/// Each event is the JSON object the daemon emitted as a `data:` line:
/// `{ "type": "delta", "text": "..." }`, `{ "type": "done", ... }`, or
/// `{ "type": "error", "message": "..." }`. The caller decides how to
/// handle each type.
/// 
/// Returns the accumulated full text (all deltas concatenated) on success.
/// Minimal SSE line buffer: accumulates bytes, yields complete `data:` payloads.
/// (The client's former `sse.rs` moved to the daemon; this is a small inline
/// reader for the daemon's `text/event-stream` response.)
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct SseBuffer {
    pub buf: String,
}

impl SseBuffer {
    fn new() -> SseBuffer {
        return SseBuffer { buf: "".to_string() };
    }
    fn push(&mut self, chunk: &str) -> Vec<String> {
        self.buf = format!("{}{}", self.buf, chunk);
        let mut out: Vec<String> = vec![];
        loop {
            let idx = a2r_std::str_find(&self.buf, "\n\n");
            if idx < 0 {
                break;
            }
            let block = self.buf[0..(idx + 2) as usize].to_string();
            self.buf = self.buf[(idx + 2) as usize..].to_string();
            for line in block.split("\n").collect::<Vec<_>>() {
                let data = strip_data_prefix(line);
                if data.is_empty() == false && data != "[DONE]" {
                    out.push(data.to_string());
                }
            }
        }
        return out;
    }
    fn finish(&mut self) -> Vec<String> {
        if self.buf.is_empty() {
            return vec![];
        }
        let block: String = self.buf.clone();
        self.buf = "".to_string();
        let mut out: Vec<String> = vec![];
        for line in block.split("\n").collect::<Vec<_>>() {
            let data = strip_data_prefix(line);
            if data.is_empty() == false && data != "[DONE]" {
                out.push(data.to_string());
            }
        }
        return out;
    }
}

/// Feed a chunk, returning any complete `data:` payloads found. A payload
/// is the text after `data: ` up to a blank line (`\n\n`).
/// Flush any trailing payload without a final `\n\n`.
/// Strip a leading `data: ` or `data:` prefix and trim; "" if absent.
fn strip_data_prefix(line: &str) -> String {
    let trimmed = line.trim().to_string();
    if trimmed.starts_with("data: ") {
        return trimmed[6..].to_string().trim().to_string();
    }
    if trimmed.starts_with("data:") {
        return trimmed[5..].to_string().trim().to_string();
    }
    return "".to_string();
}

/// The `text` field of a delta event, or "" if absent.
fn text_of(mut value: JsonValue) -> String {
    return value.get("text").and_then(|v| v.as_str()).unwrap_or_default().to_string();
}

/// An optional string field, or None if absent/empty.
fn opt_str_field(mut value: JsonValue, key: &str) -> Option<String> {
    let s = value.get(key).and_then(|v| v.as_str()).unwrap_or_default().to_string();
    if s.is_empty() {
        return None;
    }
    return Some(s);
}

/// Parse `tool_calls` array from a done event into typed ToolCall list.
fn parse_tool_calls(value: JsonValue) -> Vec<ToolCall> {
    let mut out: Vec<ToolCall> = vec![];
    let arr = a2r_std::json::get(&value, "tool_calls").as_array().cloned().unwrap_or_default();
    for tc in &arr {
        let id = a2r_std::json::get_str(tc, "id");
        let name = a2r_std::json::get_str(tc, "name");
        let input = a2r_std::json::get(tc, "input");
        out.push(ToolCall { id: id, name: name, input: input });
    }
    return out;
}

/// Parse `usage` object from a done event, or None if absent.
fn parse_usage(value: JsonValue) -> Option<Usage> {
    let u = a2r_std::json::get(&value, "usage");
    if u.is_null() {
        return None;
    }
    return Some(Usage { input_tokens: (a2r_std::json::as_int(&a2r_std::json::get(&u, "input_tokens")) as u32), output_tokens: (a2r_std::json::as_int(&a2r_std::json::get(&u, "output_tokens")) as u32), cache_read_tokens: (a2r_std::json::as_int(&a2r_std::json::get(&u, "cache_read_tokens")) as u32), cache_write_tokens: (a2r_std::json::as_int(&a2r_std::json::get(&u, "cache_write_tokens")) as u32) });
}

/// Parse `model_meta` object from a done event, or None if absent (Plan 031).
fn parse_model_meta(value: JsonValue) -> Option<ModelMeta> {
    let m = a2r_std::json::get(&value, "model_meta");
    if m.is_null() {
        return None;
    }
    let mut max_out: Option<u32> = None;
    let raw_max = a2r_std::json::get(&m, "max_output_tokens");
    if raw_max.is_null() == false {
        max_out = Some((a2r_std::json::as_int(&raw_max) as u32));
    }
    return Some(ModelMeta { id: a2r_std::json::get_str(&m, "id"), context_window: (a2r_std::json::as_int(&a2r_std::json::get(&m, "context_window")) as u32), max_output_tokens: max_out });
}

/// Decode a response body byte array to a string (UTF-8, lossy).
fn bytes_to_str(bytes: Vec<u8>) -> String {
    return a2r_std::str::from_bytes(bytes);
}
