// Auto-generated by a2r transpiler
#![allow(dead_code, unreachable_code, unused_imports, unused_mut, unused_parens, unused_assignments, unused_variables)]

pub mod loader;
pub mod provider;
pub mod tier;
pub mod validate;
pub mod wire;

pub use crate::tier::{ModelTier, ModelDefinition, all_tiers, resolve_model_id};
pub use crate::wire::{Message, ContentBlock, ToolDefinition, ToolCall, CompletionRequest, CompletionResponse, Usage};
pub use crate::provider::{ProviderConfig};
pub use crate::loader::{ClientConfig, DaemonConfig, ConfigError, parse_client_config, parse_daemon_config};
pub use crate::validate::{validate_model_exists};
