// Auto-generated by a2r transpiler

use std::collections::HashMap;
use auto_atom::*;
use auto_val::*;
use serde::Deserialize;
use crate::provider::{ProviderConfig};
use crate::tier::{ModelDefinition, ModelTier};
/// `.at` configuration loading for client and daemon, via the shared
/// `auto_atom` parser.
/// 
/// Auto port of crates/ai-config/src/loader.rs (auto-ai v0.4.0).
/// 
/// BRIDGE NOTE (plan 013): the Rust original depends on the `auto_atom` +
/// `auto_val` crates (Atom/Node/Kid/Value) to parse the `client { … }` /
/// `daemon { … }` config format. Auto's VM stdlib has no equivalent parser
/// yet, so this file bridges those Rust crates via `use.rust`. Consequences:
/// - `loader.at` is **a2r-first**: it runs when transpiled to Rust (cargo),
/// not in the pure AutoVM interpreter (the bridged types are unknown to the
/// VM). Behavior is verified via the a2r→Rust test path.
/// - When Auto achieves self-hosting and gains a native Atom parser, drop the
/// `use.rust` lines and swap the bridged calls for the Auto-native ones;
/// the public API (parse_client_config / parse_daemon_config / the *Config
/// types) stays unchanged.
/// 
/// Two file shapes, both single-root (auto-atom parses exactly one root
/// value, so the legacy flat format is wrapped in a root node):
/// 
/// `ai-client.at`:
/// ```text
/// client {
/// default_provider : zhipu
/// default_model : "glm-4.6"
/// zhipu {
/// kind : openai
/// base_url : "https://open.bigmodel.cn/api/paas/v4"
/// key_env : ZHIPU_API_KEY
/// models : [
/// { id : "glm-5.2", tier : max },
/// { id : "glm-4.6", tier : mid }
/// ]
/// }
/// }
/// ```
/// 
/// `ai-daemon.at` — same, rooted in `daemon { … }`, plus daemon-only fields
/// (`listen_addr`, `idle_timeout_min`, `log_level`, and `max_concurrency`
/// inside each provider block).
/// 
/// Plan 021 缺口 3 / Plan 381: scalar props are deserialized via the serde view
/// structs below (ClientScalars/DaemonScalars/ProviderScalars) instead of the
/// hand-written opt_* helpers. Complex structures (providers keyed by
/// child-node name, tier_routing nested block, models' 3 shapes) stay
/// hand-written. A provider whose scalars fail to deserialize is a **config
/// error**, not a silent skip (rust-ref Plan 381). `idle_timeout_min` keeps the
/// DaemonConfig default (10) when absent — deliberately NOT rust-ref's
/// `unwrap_or(0)` (rust-ref's `default()` says 10; its parse path's 0 is an
/// inconsistency we don't replicate — decision: 10).
/// Configuration error.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum ConfigError {
    Parse(String),
}


impl ConfigError {
    fn message(&self) -> String {
        match self {
            ConfigError::Parse(msg) => return format!("config parse error: {}", msg),
            _ => return "config parse error".to_string(),
        }
    }
}
impl std::fmt::Display for ConfigError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.message())
    }
}
impl std::error::Error for ConfigError {}


/// Client-side view: provider registry + defaults.
/// 
/// `provider_names` is an insertion-ordered list of keys kept in parallel
/// with `providers` because Auto's VM Map exposes no iteration API. Consumers
/// walk `provider_names` and reach each provider via `providers.get(name)`.
#[derive(Clone, Debug, PartialEq)]
pub struct ClientConfig {
    pub providers: std::collections::HashMap<String, ProviderConfig>,
    pub provider_names: Vec<String>,
    pub default_provider: String,
    pub default_model: String,
}

impl ClientConfig {
    pub fn empty() -> ClientConfig {
        return ClientConfig { providers: std::collections::HashMap::new(), provider_names: vec![], default_provider: "".to_string(), default_model: "".to_string() };
    }
}

/// Empty config (no providers).
/// Daemon-side view: client config + daemon-only operational fields.
#[derive(Clone, Debug, PartialEq)]
pub struct DaemonConfig {
    pub listen_addr: String,
    pub idle_timeout_min: u32,
    pub log_level: String,
    pub providers: std::collections::HashMap<String, ProviderConfig>,
    pub provider_names: Vec<String>,
    pub default_provider: String,
    pub default_model: String,
    pub tier_routing: TierRouting,
}

impl DaemonConfig {
    pub fn default() -> DaemonConfig {
        return DaemonConfig { listen_addr: "127.0.0.1:17654".to_string(), idle_timeout_min: 10, log_level: "info".to_string(), providers: std::collections::HashMap::new(), provider_names: vec![], default_provider: "".to_string(), default_model: "".to_string(), tier_routing: TierRouting::empty() };
    }
}

/// Explicit tier routing table. When non-empty, overrides auto-derivation.
/// A single tier routing candidate: provider + model.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct TierRouteCandidate {
    pub provider: String,
    pub model: String,
}

/// Tier routing table: tier name → ordered candidate list (primary first).
/// When present in the config, overrides auto-derivation.
/// 
/// `tier_names` parallels `entries` for the same reason ClientConfig carries
/// `provider_names`: Auto's VM Map has no iteration API.
/// 
/// Note: the field is named `entries`, not `routes` — `routes` is a reserved
/// keyword in Auto (routing/navigation) and cannot be used as a field name.
#[derive(Clone, Debug, PartialEq)]
pub struct TierRouting {
    pub entries: std::collections::HashMap<String, Vec<TierRouteCandidate>>,
    pub tier_names: Vec<String>,
}

impl TierRouting {
    pub fn empty() -> TierRouting {
        return TierRouting { entries: std::collections::HashMap::new(), tier_names: vec![] };
    }
    pub fn is_empty(&self) -> bool {
        return (self.tier_names.len() as i64) == 0;
    }
    pub fn candidates(&self, tier: &str) -> Option<Vec<TierRouteCandidate>> {
        if self.entries.contains_key(tier) {
            

            match self.entries.get(tier) {
                Some(list) => return Some(list.clone()),
                None => return None,
            };
        }
        return None;
    }
}

/// Ordered candidates for a tier, or None if the tier isn't routed.
#[derive(Debug, Deserialize)]
struct ClientScalars {
    #[serde(default)]
    pub default_provider: String,
    #[serde(default)]
    pub default_model: String,
}

#[derive(Debug, Default, Deserialize)]
struct DaemonScalars {
    #[serde(default)]
    pub listen_addr: Option<String>,
    #[serde(default)]
    pub idle_timeout_min: Option<u32>,
    #[serde(default)]
    pub log_level: Option<String>,
    #[serde(default)]
    pub default_provider: Option<String>,
    #[serde(default)]
    pub default_model: Option<String>,
}

#[derive(Debug, Default, Deserialize)]
struct ProviderScalars {
    #[serde(default)]
    pub kind: Option<String>,
    #[serde(default)]
    pub base_url: Option<String>,
    #[serde(default)]
    pub api_key: Option<String>,
    #[serde(default)]
    pub key_env: Option<String>,
    #[serde(default)]
    pub max_concurrency: Option<u32>,
    #[serde(default, deserialize_with = "auto_val::lenient_bool_opt")]
    pub auth_required: Option<bool>,
}

pub fn parse_client_config(content: &str) -> Result<ClientConfig, ConfigError> {
    match root_node(content, "client") {
        Ok(client_node) => {
            




            match client_node.deserialize::<ClientScalars>() {
                Ok(s) => {
                    match parse_provider_blocks(client_node.clone()) {
                        Ok(providers) => {
                            let names = provider_keys(client_node.clone());
                            

                            if (names.len() as i64) == 0 {
                                return Err(ConfigError::Parse("no providers configured in client { } block".to_string()));
                            }
                            let dp = if s.default_provider.is_empty() {
                                names[0].clone()
                            } else {
                                s.default_provider
                            };
                            return Ok(ClientConfig { providers: providers, provider_names: names, default_provider: dp.to_string(), default_model: s.default_model.to_string() });
                        },
                        Err(e) => return Err(e),
                    };
                },
                Err(e) => return Err(ConfigError::Parse(format!("client.at: {}", e))),
            };
        },
        Err(e) => return Err(e),
    }
}

pub fn parse_daemon_config(content: &str) -> Result<DaemonConfig, ConfigError> {
    match root_node(content, "daemon") {
        Ok(daemon_node) => {
            



            match daemon_node.deserialize::<DaemonScalars>() {
                Ok(s) => {
                    let mut cfg = DaemonConfig::default();
                    match s.listen_addr {
                        Some(v) => cfg.listen_addr = v,
                        None => {},
                    };
                    



                    match s.idle_timeout_min {
                        Some(n) => cfg.idle_timeout_min = n,
                        None => {},
                    };
                    match s.log_level {
                        Some(v) => cfg.log_level = v,
                        None => {},
                    };
                    match s.default_provider {
                        Some(v) => cfg.default_provider = v,
                        None => {},
                    };
                    match s.default_model {
                        Some(v) => cfg.default_model = v,
                        None => {},
                    };
                    match parse_provider_blocks(daemon_node.clone()) {
                        Ok(providers) => cfg.providers = providers,
                        Err(e) => return Err(e),
                    };
                    cfg.provider_names = provider_keys(daemon_node.clone());
                    cfg.tier_routing = parse_tier_routing(daemon_node.clone());
                    

                    if cfg.default_provider.is_empty() && (cfg.provider_names.len() as i64) > 0 {
                        cfg.default_provider = cfg.provider_names[0].clone();
                    }
                    if cfg.default_model.is_empty() {
                        if cfg.providers.contains_key(&cfg.default_provider) {
                            

                            match cfg.providers.get(&cfg.default_provider) {
                                Some(p) => {
                                    if (p.models.len() as i64) > 0 {
                                        cfg.default_model = p.models[0].clone().id.to_string();
                                    }
                                },
                                None => {},
                            };
                        }                    }
                    return Ok(cfg);
                },
                Err(e) => return Err(ConfigError::Parse(format!("daemon.at: {}", e))),
            };
        },
        Err(e) => return Err(e),
    }
}

/// auth_required accepts bool / 0,1 / "yes","on",… (old opt_bool).
/// Parse `ai-client.at` content (root must be `client { … }`).
/// Parse `daemon { … }` content (root must be `daemon { … }`).
/// Parse the single root node and assert its name is `expected`.
fn root_node(content: &str, expected: &str) -> Result<Node, ConfigError> {
    match auto_atom::AtomParser::parse(content) {
        Ok(atom) => {
            match atom {
                Atom::Node(n) => {
                    if n.name == expected {
                        return Ok(n);
                    }
                    return Err(ConfigError::Parse(format!("expected a '{}' root block, found '{}'", expected, n.name)));
                },
                _ => return Err(ConfigError::Parse(format!("expected a '{}' root node", expected))),
            };
        },
        Err(e) => return Err(ConfigError::Parse(format!("{}.at: {}", expected, e))),
    }
}

/// True when a `kind` prop value marks a non-provider child block: missing
/// (Nil/Null/Void) or an empty string. Mirrors rust-ref's kind check
/// (`matches!(kind_prop, Value::Nil | Value::Null | Value::Void)`) plus the old
/// opt_str "" behavior, so `provider_keys` and `parse_provider_blocks` agree on
/// what counts as a provider.
fn kind_prop_is_empty(v: Value) -> bool {
    match v {
        Value::Nil => return true,
        Value::Null => return true,
        Value::Void => return true,
        Value::Str(s) => return s.to_string().is_empty(),
        Value::String(s) => return s.to_string().is_empty(),
        _ => return false,
    }
}

/// Collect the names of each `name { … }` child block of `node` (in order).
fn provider_keys(node: Node) -> Vec<String> {
    let mut names: Vec<String> = vec![];
    for (_key, kid) in node.kids_iter() {
        match kid {
            Kid::Node(child) => {
                if kind_prop_is_empty(child.get_prop_of("kind")) == false {
                    names.push(child.name.to_string());
                }
            },
            _ => {},
        };
    }
    return names;
}

/// Walk a node's children, turning each `name { … }` block into a
/// ProviderConfig. Returns a Map keyed by block name, or a config error.
/// 
/// A child node is a provider iff it declares a `kind` prop (same convention as
/// the daemon's `enum_self_providers`). Other child nodes — e.g. the daemon's
/// `tier_routing { … }` block — are skipped without being deserialized. A
/// provider whose scalars fail to deserialize (a garbage-typed value such as
/// `auth_required : "maybe"`) is a **config error**, not a silent skip: a
/// provider must never quietly vanish from the registry (Plan 381).
fn parse_provider_blocks(node: Node) -> Result<std::collections::HashMap<String, ProviderConfig>, ConfigError> {
    let mut providers: std::collections::HashMap<String, ProviderConfig> = std::collections::HashMap::new();
    for (_key, kid) in node.kids_iter() {
        match kid {
            Kid::Node(provider_node) => {
                

                if kind_prop_is_empty(provider_node.get_prop_of("kind")) == false {
                    

                    match provider_node.deserialize::<ProviderScalars>() {
                        Ok(s) => {
                            let pc = ProviderConfig { kind: match s.kind { Some(v) => v, None => "".to_string(), }, base_url: match s.base_url { Some(v) => v, None => "".to_string(), }, api_key: s.api_key, key_env: s.key_env, models: opt_models(*(*provider_node).clone(), "models"), max_concurrency: s.max_concurrency, auth_required: match s.auth_required { Some(b) => b, None => true, } };
                            if pc.kind.is_empty() == false {
                                providers.insert(provider_node.name.to_string(), pc);
                            }
                        },
                        Err(e) => return Err(ConfigError::Parse(format!("provider '{}': {}", provider_node.name, e))),
                    };
                }
            },
            _ => {},
        };
    }
    return Ok(providers);
}

/// Parse the `tier_routing { … }` child block from a daemon config.
fn parse_tier_routing(node: Node) -> TierRouting {
    let mut routing = TierRouting::empty();
    for (_key, kid) in node.kids_iter() {
        match kid {
            Kid::Node(tr_node) => {
                if tr_node.name != "tier_routing" {
                    

                } else {
                    

                    for (tier_key, tier_val) in tr_node.props_iter() {
                        let tier_name = valuekey_to_str(tier_key.clone());
                        if tier_name.is_empty() {
                            

                        } else {
                            let cands = parse_candidates(tier_val.clone());
                            if (cands.len() as i64) > 0 {
                                


                                routing.entries.insert(tier_name.clone(), cands);
                                routing.tier_names.push(tier_name.clone());
                            }                        }

                    }
                }

            },
            _ => {},
        };
    }
    return routing;
}

/// Parse a Value::Array of `{ provider, model }` objects into candidates.
fn parse_candidates(val: Value) -> Vec<TierRouteCandidate> {
    let mut out: Vec<TierRouteCandidate> = vec![];
    match val {
        Value::Array(arr) => {
            for v in &arr.values {
                match v {
                    Value::Obj(o) => {
                        let provider = obj_get_str(o.clone(), "provider");
                        let model = obj_get_str(o.clone(), "model");
                        if provider.is_empty() == false && model.is_empty() == false {
                            out.push(TierRouteCandidate { provider: provider.to_string(), model: model.to_string() });
                        }
                    },
                    _ => {},
                };
            }
        },
        _ => {},
    };
    return out;
}

/// Read the `models` field as a list of [ModelDefinition]s (id + tier).
/// 
/// Accepted shapes (each element of the `models` array):
/// - `Obj { id, name?, tier }` — full, preferred.
/// - `Str "glm-5.2"` — bare model id, defaults to [ModelTier.Mid].
/// Legacy: a comma-separated bare string `glm-4.6,glm-flash` → all Mid.
fn opt_models(node: Node, key: &str) -> Vec<ModelDefinition> {
    let val = node.get_prop_of(key);
    let mut out: Vec<ModelDefinition> = vec![];
    match val {
        Value::Array(arr) => {
            for el in &arr.values {
                match el {
                    Value::Obj(o) => {
                        let id = obj_get_str(o.clone(), "id");
                        if id.is_empty() == false {
                            let name = obj_get_str(o.clone(), "name");
                            let tier = parse_tier(obj_get_str(o.clone(), "tier").as_str());
                            out.push(ModelDefinition { id: id, name: name, tier: tier, context_window: None, max_output_tokens: None, cost_per_mtok: None, capabilities: None });
                        }
                    },
                    Value::Str(s) => {
                        

                        out.push(ModelDefinition::new(s.as_str(), ModelTier::Mid));
                    },
                    _ => {},
                };
            }
        },
        Value::Str(s) => {
            

            let parts = s.split(",").collect::<Vec<_>>();
            for raw in &parts {
                let m = raw.trim().to_string();
                if m.is_empty() == false {
                    out.push(ModelDefinition::new(m.as_str(), ModelTier::Mid));
                }
            }
        },
        _ => {},
    };
    return out;
}

/// Parse a tier name → ModelTier. Accepts snake_case ("max", "mid"), display
/// ("Max", "Mid"), and auto-forge aliases ("large"=Pro, "heavy"=Max).
/// 
/// Unknown → Min. NOTE: loader.rs:315 comments "unknown names default to Mid"
/// but the code is `parse_name(s).unwrap_or_default()`, and ModelTier's
/// `#[default]` is Min (tier.rs:18) — so the actual Rust behavior is Min.
/// This port matches the **code** (Min), not the (self-contradictory) comment.
fn parse_tier(s: &str) -> ModelTier {
    match ModelTier::parse_name(s) {
        Some(t) => return t,
        None => return ModelTier::Min,
    }
}

/// Read a string field from an Obj, or "" if absent / not a string.
fn obj_get_str(o: Obj, key: &str) -> String {
    match o.get(key) {
        Some(v) => {
            match v {
                Value::Str(s) => return s.to_string(),
                Value::String(s) => return s.to_string(),
                _ => return "".to_string(),
            };
        },
        None => return "".to_string(),
    }
}

/// Extract the str payload from a ValueKey::Str, else "".
fn valuekey_to_str(k: ValueKey) -> String {
    match k {
        ValueKey::Str(s) => return s.to_string(),
        _ => return "".to_string(),
    }
}
