// Auto-generated by a2r transpiler

use std::collections::HashMap;
use auto_atom::*;
use auto_val::*;
use crate::provider::{ProviderConfig};
use crate::tier::{ModelDefinition, ModelTier};
/// `.at` configuration loading for client and daemon, via the shared
/// `auto_atom` parser.
/// 
/// Auto port of crates/ai-config/src/loader.rs (auto-ai v0.4.0).
/// 
/// BRIDGE NOTE (plan 013): the Rust original depends on the `auto_atom` +
/// `auto_val` crates (Atom/Node/Kid/Value) to parse the `client { … }` /
/// `daemon { … }` config format. Auto's VM stdlib has no equivalent parser
/// yet, so this file bridges those Rust crates via `use.rust`. Consequences:
/// - `loader.at` is **a2r-first**: it runs when transpiled to Rust (cargo),
/// not in the pure AutoVM interpreter (the bridged types are unknown to the
/// VM). Behavior is verified via the a2r→Rust test path.
/// - When Auto achieves self-hosting and gains a native Atom parser, drop the
/// `use.rust` lines and swap the bridged calls for the Auto-native ones;
/// the public API (parse_client_config / parse_daemon_config / the *Config
/// types) stays unchanged.
/// 
/// Two file shapes, both single-root (auto-atom parses exactly one root
/// value, so the legacy flat format is wrapped in a root node):
/// 
/// `ai-client.at`:
/// ```text
/// client {
/// default_provider : zhipu
/// default_model : "glm-4.6"
/// zhipu {
/// kind : openai
/// base_url : "https://open.bigmodel.cn/api/paas/v4"
/// key_env : ZHIPU_API_KEY
/// models : [
/// { id : "glm-5.2", tier : max },
/// { id : "glm-4.6", tier : mid }
/// ]
/// }
/// }
/// ```
/// 
/// `ai-daemon.at` — same, rooted in `daemon { … }`, plus daemon-only fields
/// (`listen_addr`, `idle_timeout_min`, `log_level`, and `max_concurrency`
/// inside each provider block).
/// Configuration error.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum ConfigError {
    Parse(String),
}


impl ConfigError {
    fn message(&self) -> String {
        match self {
            ConfigError::Parse(msg) => return format!("config parse error: {}", msg),
            _ => return "config parse error".to_string(),
        }
    }
}
impl std::fmt::Display for ConfigError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.message())
    }
}
impl std::error::Error for ConfigError {}


/// Client-side view: provider registry + defaults.
/// 
/// `provider_names` is an insertion-ordered list of keys kept in parallel
/// with `providers` because Auto's VM Map exposes no iteration API. Consumers
/// walk `provider_names` and reach each provider via `providers.get(name)`.
#[derive(Clone, Debug, PartialEq)]
pub struct ClientConfig {
    pub providers: std::collections::HashMap<String, ProviderConfig>,
    pub provider_names: Vec<String>,
    pub default_provider: String,
    pub default_model: String,
}

impl ClientConfig {
    pub fn empty() -> ClientConfig {
        return ClientConfig { providers: std::collections::HashMap::new(), provider_names: vec![], default_provider: "".to_string(), default_model: "".to_string() };
    }
}

/// Empty config (no providers).
/// Daemon-side view: client config + daemon-only operational fields.
#[derive(Clone, Debug, PartialEq)]
pub struct DaemonConfig {
    pub listen_addr: String,
    pub idle_timeout_min: u32,
    pub log_level: String,
    pub providers: std::collections::HashMap<String, ProviderConfig>,
    pub provider_names: Vec<String>,
    pub default_provider: String,
    pub default_model: String,
    pub tier_routing: TierRouting,
}

impl DaemonConfig {
    pub fn default() -> DaemonConfig {
        return DaemonConfig { listen_addr: "127.0.0.1:17654".to_string(), idle_timeout_min: 10, log_level: "info".to_string(), providers: std::collections::HashMap::new(), provider_names: vec![], default_provider: "".to_string(), default_model: "".to_string(), tier_routing: TierRouting::empty() };
    }
}

/// Explicit tier routing table. When non-empty, overrides auto-derivation.
/// A single tier routing candidate: provider + model.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct TierRouteCandidate {
    pub provider: String,
    pub model: String,
}

/// Tier routing table: tier name → ordered candidate list (primary first).
/// When present in the config, overrides auto-derivation.
/// 
/// `tier_names` parallels `entries` for the same reason ClientConfig carries
/// `provider_names`: Auto's VM Map has no iteration API.
/// 
/// Note: the field is named `entries`, not `routes` — `routes` is a reserved
/// keyword in Auto (routing/navigation) and cannot be used as a field name.
#[derive(Clone, Debug, PartialEq)]
pub struct TierRouting {
    pub entries: std::collections::HashMap<String, Vec<TierRouteCandidate>>,
    pub tier_names: Vec<String>,
}

impl TierRouting {
    pub fn empty() -> TierRouting {
        return TierRouting { entries: std::collections::HashMap::new(), tier_names: vec![] };
    }
    pub fn is_empty(&self) -> bool {
        return (self.tier_names.len() as i32) == 0;
    }
    pub fn candidates(&self, tier: &str) -> Option<Vec<TierRouteCandidate>> {
        if self.entries.contains_key(tier) {
            

            match self.entries.get(tier) {
                Some(list) => return Some(list.clone()),
                None => return None,
            };
        }
        return None;
    }
}

pub fn parse_client_config(content: &str) -> Result<ClientConfig, ConfigError> {
    match root_node(content, "client") {
        Ok(node) => {
            let default_provider = opt_str(node.clone(), "default_provider");
            let default_model = opt_str(node.clone(), "default_model");
            let providers = parse_provider_blocks(node.clone());
            let names = provider_keys(node.clone());
            

            if (names.len() as i32) == 0 {
                return Err(ConfigError::Parse("no providers configured in client { } block".to_string()));
            }
            let dp = if default_provider.is_empty() {
                names[0].clone()
            } else {
                default_provider
            };
            return Ok(ClientConfig { providers: providers, provider_names: names, default_provider: dp.to_string(), default_model: default_model.to_string() });
        },
        Err(e) => return Err(e),
    }
}

pub fn parse_daemon_config(content: &str) -> Result<DaemonConfig, ConfigError> {
    match root_node(content, "daemon") {
        Ok(node) => {
            let mut cfg = DaemonConfig::default();
            let la = opt_str(node.clone(), "listen_addr");
            if la.is_empty() == false {
                cfg.listen_addr = la
            }
            let itm = opt_uint(node.clone(), "idle_timeout_min");
            match itm {
                Some(n) => cfg.idle_timeout_min = n,
                None => {},
            };
            let ll = opt_str(node.clone(), "log_level");
            if ll.is_empty() == false {
                cfg.log_level = ll
            }
            cfg.default_provider = opt_str(node.clone(), "default_provider");
            cfg.default_model = opt_str(node.clone(), "default_model");
            cfg.providers = parse_provider_blocks(node.clone());
            cfg.provider_names = provider_keys(node.clone());
            cfg.tier_routing = parse_tier_routing(node.clone());
            

            if cfg.default_provider.is_empty() && (cfg.provider_names.len() as i32) > 0 {
                cfg.default_provider = cfg.provider_names[0].clone()
            }
            if cfg.default_model.is_empty() {
                if cfg.providers.contains_key(&cfg.default_provider) {
                    

                    match cfg.providers.get(&cfg.default_provider) {
                        Some(p) => {
                            if (p.models.len() as i32) > 0 {
                                cfg.default_model = p.models[0].clone().id.to_string()
                            }
                        },
                        None => {},
                    };
                }            }
            return Ok(cfg);
        },
        Err(e) => return Err(e),
    }
}

/// Ordered candidates for a tier, or None if the tier isn't routed.
/// Parse `ai-client.at` content (root must be `client { … }`).
/// Parse `daemon { … }` content (root must be `daemon { … }`).
/// Parse the single root node and assert its name is `expected`.
fn root_node(content: &str, expected: &str) -> Result<Node, ConfigError> {
    match auto_atom::AtomParser::parse(content) {
        Ok(atom) => {
            match atom {
                Atom::Node(n) => {
                    if n.name == expected {
                        return Ok(n);
                    }
                    return Err(ConfigError::Parse(format!("expected a '{}' root block, found '{}'", expected, n.name)));
                },
                _ => return Err(ConfigError::Parse(format!("expected a '{}' root node", expected))),
            };
        },
        Err(e) => return Err(ConfigError::Parse(format!("{}.at: {}", expected, e))),
    }
}

/// Collect the names of each `name { … }` child block of `node` (in order).
fn provider_keys(node: Node) -> Vec<String> {
    let mut names: Vec<String> = vec![];
    for (_key, kid) in node.kids_iter() {
        match kid {
            Kid::Node(child) => {
                let pc_kind = opt_str(*(*child).clone(), "kind");
                if pc_kind.is_empty() == false {
                    names.push(child.name.to_string());
                }
            },
            _ => {},
        };
    }
    return names;
}

/// Walk a node's children, turning each `name { … }` block into a
/// ProviderConfig. Returns a Map keyed by block name.
fn parse_provider_blocks(node: Node) -> std::collections::HashMap<String, ProviderConfig> {
    let mut providers: std::collections::HashMap<String, ProviderConfig> = std::collections::HashMap::new();
    for (_key, kid) in node.kids_iter() {
        match kid {
            Kid::Node(child) => {
                let kind = opt_str(*(*child).clone(), "kind");
                if kind.is_empty() == false {
                    




                    let auth = match opt_bool(*(*child).clone(), "auth_required") { Some(b) => b, None => true, };
                    let pc = ProviderConfig { kind: kind, base_url: opt_str(*(*child).clone(), "base_url"), api_key: opt_str_opt(*(*child).clone(), "api_key"), key_env: opt_str_opt(*(*child).clone(), "key_env"), models: opt_models(*(*child).clone(), "models"), max_concurrency: opt_uint_opt(*(*child).clone(), "max_concurrency"), auth_required: auth };
                    providers.insert(child.name.to_string(), pc);
                }
            },
            _ => {},
        };
    }
    return providers;
}

/// Parse the `tier_routing { … }` child block from a daemon config.
fn parse_tier_routing(node: Node) -> TierRouting {
    let mut routing = TierRouting::empty();
    for (_key, kid) in node.kids_iter() {
        match kid {
            Kid::Node(tr_node) => {
                if tr_node.name != "tier_routing" {
                    

                } else {
                    

                    for (tier_key, tier_val) in tr_node.props_iter() {
                        let tier_name = valuekey_to_str(tier_key.clone());
                        if tier_name.is_empty() {
                            

                        } else {
                            let cands = parse_candidates(tier_val.clone());
                            if (cands.len() as i32) > 0 {
                                


                                routing.entries.insert(tier_name.clone(), cands);
                                routing.tier_names.push(tier_name.clone());
                            }                        }

                    }
                }

            },
            _ => {},
        };
    }
    return routing;
}

/// Parse a Value::Array of `{ provider, model }` objects into candidates.
fn parse_candidates(val: Value) -> Vec<TierRouteCandidate> {
    let mut out: Vec<TierRouteCandidate> = vec![];
    match val {
        Value::Array(arr) => {
            for v in &arr.values {
                match v {
                    Value::Obj(o) => {
                        let provider = obj_get_str(o.clone(), "provider");
                        let model = obj_get_str(o.clone(), "model");
                        if provider.is_empty() == false && model.is_empty() == false {
                            out.push(TierRouteCandidate { provider: provider.to_string(), model: model.to_string() });
                        }
                    },
                    _ => {},
                };
            }
        },
        _ => {},
    };
    return out;
}

/// Read a string prop; "" when missing or nil.
fn opt_str(node: Node, key: &str) -> String {
    let val = node.get_prop_of(key);
    match val {
        Value::Str(s) => return s.to_string(),
        Value::String(s) => return s.to_string(),
        _ => return val.to_astr().to_string(),
    }
}

/// Read an optional string prop: None when missing/nil.
fn opt_str_opt(node: Node, key: &str) -> Option<String> {
    let val = node.get_prop_of(key);
    match val {
        Value::Str(s) => return Some(s.to_string()),
        Value::String(s) => return Some(s.to_string()),
        _ => {
            let s = val.to_astr().to_string();
            if s.is_empty() {
                return None;
            }
            return Some(s);
        },
    }
}

/// Read a non-negative integer prop; None when missing.
fn opt_uint_opt(node: Node, key: &str) -> Option<u32> {
    let val = node.get_prop_of(key);
    match val {
        Value::Uint(u) => return Some(u as u32),
        Value::Int(i) => {
            if i >= 0 {
                return Some(i as u32);
            }
            return None;
        },
        _ => return None,
    }
}

/// Read an optional uint prop (kept for parity with opt_uint in the original).
fn opt_uint(node: Node, key: &str) -> Option<u32> {
    return opt_uint_opt(node.clone(), key);
}

/// Read a boolean prop: true/false/1/0/yes/no. None if absent/unrecognized.
fn opt_bool(node: Node, key: &str) -> Option<bool> {
    let val = node.get_prop_of(key);
    match val {
        Value::Bool(b) => return Some(b),
        Value::Uint(u) => return Some(u != 0),
        Value::Int(i) => return Some(i != 0),
        Value::Str(s) => {
            let lower = s.to_ascii_lowercase();
            match lower.as_str() {
                "true" => return Some(true),
                "yes" => return Some(true),
                "1" => return Some(true),
                "on" => return Some(true),
                "false" => return Some(false),
                "no" => return Some(false),
                "0" => return Some(false),
                "off" => return Some(false),
                _ => return None,
            };
        },
        _ => return None,
    }
}

/// Read the `models` field as a list of [ModelDefinition]s (id + tier).
/// 
/// Accepted shapes (each element of the `models` array):
/// - `Obj { id, name?, tier }` — full, preferred.
/// - `Str "glm-5.2"` — bare model id, defaults to [ModelTier.Mid].
/// Legacy: a comma-separated bare string `glm-4.6,glm-flash` → all Mid.
fn opt_models(node: Node, key: &str) -> Vec<ModelDefinition> {
    let val = node.get_prop_of(key);
    let mut out: Vec<ModelDefinition> = vec![];
    match val {
        Value::Array(arr) => {
            for el in &arr.values {
                match el {
                    Value::Obj(o) => {
                        let id = obj_get_str(o.clone(), "id");
                        if id.is_empty() == false {
                            let name = obj_get_str(o.clone(), "name");
                            let tier = parse_tier(obj_get_str(o.clone(), "tier").as_str());
                            out.push(ModelDefinition { id: id, name: name, tier: tier });
                        }
                    },
                    Value::Str(s) => {
                        

                        out.push(ModelDefinition::new(s.as_str(), ModelTier::Mid));
                    },
                    _ => {},
                };
            }
        },
        Value::Str(s) => {
            

            let parts = s.split(",").collect::<Vec<_>>();
            for raw in &parts {
                let m = raw.trim().to_string();
                if m.is_empty() == false {
                    out.push(ModelDefinition::new(m.as_str(), ModelTier::Mid));
                }
            }
        },
        _ => {},
    };
    return out;
}

/// Parse a tier name → ModelTier. Accepts snake_case ("max", "mid"), display
/// ("Max", "Mid"), and auto-forge aliases ("large"=Pro, "heavy"=Max).
/// 
/// Unknown → Min. NOTE: loader.rs:315 comments "unknown names default to Mid"
/// but the code is `parse_name(s).unwrap_or_default()`, and ModelTier's
/// `#[default]` is Min (tier.rs:18) — so the actual Rust behavior is Min.
/// This port matches the **code** (Min), not the (self-contradictory) comment.
fn parse_tier(s: &str) -> ModelTier {
    match ModelTier::parse_name(s) {
        Some(t) => return t,
        None => return ModelTier::Min,
    }
}

/// Read a string field from an Obj, or "" if absent / not a string.
fn obj_get_str(o: Obj, key: &str) -> String {
    match o.get(key) {
        Some(v) => {
            match v {
                Value::Str(s) => return s.to_string(),
                Value::String(s) => return s.to_string(),
                _ => return "".to_string(),
            };
        },
        None => return "".to_string(),
    }
}

/// Extract the str payload from a ValueKey::Str, else "".
fn valuekey_to_str(k: ValueKey) -> String {
    match k {
        ValueKey::Str(s) => return s.to_string(),
        _ => return "".to_string(),
    }
}
