// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

use a2r_std::env;
use crate::tier::{ModelDefinition};
/// Unified provider configuration (shared by client and daemon).
/// 
/// Replaces the two near-identical structs that previously lived separately
/// in `auto-ai-client::config::ProviderConfig` and
/// `auto-ai-daemon::config::ProviderEntry`. The only field unique to the
/// daemon is `max_concurrency`, modelled as `?uint` so the client (which
/// doesn't care about it) simply leaves it `None`.
/// 
/// Auto port of crates/ai-config/src/provider.rs (auto-ai v0.4.0).
/// One LLM provider's configuration.
/// 
/// `models` are [ModelDefinition]s (each tagged with a [tier.ModelTier]),
/// not bare strings — so a profession's tier can be resolved to a concrete
/// model at request time. `max_concurrency` is only meaningful to the daemon.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct ProviderConfig {
    pub kind: String,
    pub base_url: String,
    pub api_key: Option<String>,
    pub key_env: Option<String>,
    pub models: Vec<ModelDefinition>,
    pub max_concurrency: Option<u32>,
    pub auth_required: bool,
}

impl ProviderConfig {
    pub fn resolve_key(&self) -> Option<String> {

        match self.api_key.clone() {
            Some(key) => {
                if key.is_empty() {
                    

                    if self.auth_required == false {
                        return Some("no-key-needed".to_string());
                    }                    return None;
                }
                return Some(key);
            },
            None => {},
        };

        match self.key_env.clone() {
            Some(env_name) => {
                let val = a2r_std::env::get(env_name.as_str());
                if val.is_empty() == false {
                    return Some(val);
                }
                

                if self.auth_required {
                    return None;
                }
                return Some("no-key-needed".to_string());
            },
            None => {},
        };

        if self.auth_required {
            return None;
        }
        return Some("no-key-needed".to_string());
    }
}
