// Auto-generated by a2r transpiler

/// Model tier abstraction — decouples "what capability does a profession need"
/// (a [ModelTier]) from "which concrete model serves that tier" (a
/// [ModelDefinition] in a provider's config).
/// 
/// Five tiers, weakest→strongest: Min < Lite < Mid < Pro < Max.
/// 
/// Auto port of crates/ai-config/src/tier.rs (auto-ai v0.4.0).
/// Cost/performance tier for model selection.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum ModelTier {
    Min = 0,
    Lite = 1,
    Mid = 2,
    Pro = 3,
    Max = 4,
}

impl std::fmt::Display for ModelTier {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            ModelTier::Min => write!(f, "Min"),
            ModelTier::Lite => write!(f, "Lite"),
            ModelTier::Mid => write!(f, "Mid"),
            ModelTier::Pro => write!(f, "Pro"),
            ModelTier::Max => write!(f, "Max"),
        }
    }
}
impl ModelTier {
    pub fn from_id(id: &str) -> Self {
        match id {
            "Min" | "min" => ModelTier::Min,
            "Lite" | "lite" => ModelTier::Lite,
            "Mid" | "mid" => ModelTier::Mid,
            "Pro" | "pro" => ModelTier::Pro,
            "Max" | "max" => ModelTier::Max,
            _ => ModelTier::Min
        }
    }
}

impl ModelTier {
    fn display_name(&self) -> String {
        match self {
            ModelTier::Min => return "Min".to_string(),
            ModelTier::Lite => return "Lite".to_string(),
            ModelTier::Mid => return "Mid".to_string(),
            ModelTier::Pro => return "Pro".to_string(),
            ModelTier::Max => return "Max".to_string(),
        }
    }
    fn description(&self) -> String {
        match self {
            ModelTier::Min => return "Ultra-cheap: high-volume, low-complexity tasks".to_string(),
            ModelTier::Lite => return "Cheap: routing, chat, simple coding".to_string(),
            ModelTier::Mid => return "Balanced: planning, coding, most tasks".to_string(),
            ModelTier::Pro => return "Strong: architecture, review, complex tasks".to_string(),
            ModelTier::Max => return "Ultra-strong: deepest reasoning, research".to_string(),
        }
    }
    fn order(&self) -> i64 {
        match self {
            ModelTier::Min => return 0,
            ModelTier::Lite => return 1,
            ModelTier::Mid => return 2,
            ModelTier::Pro => return 3,
            ModelTier::Max => return 4,
        }
    }
    pub fn parse_name(s: &str) -> Option<ModelTier> {
        let lower = s.trim().to_string().to_ascii_lowercase();
        match lower.as_str() {
            "min" => Some(ModelTier::Min),
            "lite" => Some(ModelTier::Lite),
            "light" => Some(ModelTier::Lite),
            "mid" => Some(ModelTier::Mid),
            "pro" => Some(ModelTier::Pro),
            "large" => Some(ModelTier::Pro),
            "max" => Some(ModelTier::Max),
            "heavy" => Some(ModelTier::Max),
            _ => None,
        }
    }
}

/// Human-readable name for display (e.g. "Min", "Mid").
/// Short description of the tier's intended use case.
/// Weakest→strongest ordering: Min=0 … Max=4.
/// Returns `int` (not `byte`): the gap arithmetic in resolve_model_id
/// subtracts orders, and Auto/Rust don't auto-widen byte(u8) to int(i32)
/// in a typed `let`. Using int keeps both the VM and the a2r→Rust path
/// clean without explicit casts. (Plan 013 B13.)
/// Parse a tier name (case-insensitive, trims whitespace) into a
/// [ModelTier]. Returns None for unrecognized names.
/// 
/// This is the **single source of truth** for tier-name parsing — every
/// call site (daemon router, agent config, .at loader) should call this
/// instead of maintaining its own match table (review-003 M8).
/// Accepted aliases (beyond the snake_case enum names):
/// "light" → Lite, "large" → Pro, "heavy" → Max.
/// A concrete model entry in a provider's config, tagged with its tier.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct ModelDefinition {
    pub id: String,
    pub name: String,
    pub tier: ModelTier,
}

impl ModelDefinition {
    pub fn new(id: &str, tier: ModelTier) -> ModelDefinition {
        return ModelDefinition { id: id.to_string(), name: "".to_string(), tier: tier };
    }
    pub fn display_name(&self) -> String {
        if self.name.is_empty() {
            return self.id.clone();
        }
        return self.name.clone();
    }
}

pub fn all_tiers() -> Vec<ModelTier> {
    return vec![ModelTier::Min, ModelTier::Lite, ModelTier::Mid, ModelTier::Pro, ModelTier::Max];
}

pub fn resolve_model_id(desired: ModelTier, models: Vec<ModelDefinition>) -> Option<String> {
    if (models.len() as i64) == 0 {
        return None;
    }




    let mut best: Option<ModelDefinition> = None;
    let mut best_key: i64 = 0;
    let mut first: bool = true;
    let desired_order = desired.order();
    for m in &models {
        
        if m.tier.order() == desired_order {
            return Some(m.id.clone());
        }
        
        let m_order = m.tier.order();
        let gap = m_order - desired_order;
        
        let key: i64 = if gap >= 0 {
            gap
        } else {
            1000 + 0 - gap
        };
        if first || key < best_key {
            best = Some(m.clone());
            best_key = key;
            first = false;
        }
    }
    match best {
        Some(m) => return Some(m.id),
        None => return None,
    }
}
