// Auto-generated by a2r transpiler

use crate::loader::{ClientConfig};
pub fn validate_model_exists(config: ClientConfig, model: &str) -> Result<(), String> {



    let mut available: Vec<String> = vec![];
    for name in &config.provider_names {
        match config.providers.get(name.as_str()) {
            Some(p) => {
                for m in p.models.clone() {
                    if m.id == model {
                        return Ok(());
                    }
                    available.push(m.id);
                }
            },
            None => {},
        };
    }
    return Err(format!("model '{}' not found in any configured provider; available: {}", model, available.join(", ")).into());
}
