// Auto-generated by a2r transpiler
use serde_json::Value as JsonValue;

/// Canonical wire types for the AutoOS AI stack.
/// 
/// These are the provider-agnostic, neutral-format types exchanged between
/// `auto-ai-client` (which sends canonical [CompletionRequest]s) and
/// `auto-ai-daemon` (which receives them and translates to a concrete
/// provider's format). Defining them once here means the client, daemon, and
/// agent crates all share one source of truth — no provider-specific shapes
/// leak across the client↔daemon boundary.
/// 
/// Messages carry an ordered list of [ContentBlock]s so the same type can
/// represent plain text, assistant tool-use requests, and user tool results.
/// This is what makes the native tool-calling ReAct loop in `auto-ai-agent`
/// possible without a separate protocol.
/// 
/// Auto port of crates/ai-config/src/wire.rs (auto-ai v0.4.0).
/// 
/// Note on ContentBlock: the Rust original uses struct-style enum variants
/// (`Text { text }`, `ToolUse { id, name, input }`). Auto's AutoVM does not
/// yet implement destructuring of struct-style variants (codegen panic), so
/// the Auto port models them as **tuple variants** with positional fields.
/// Field order mirrors the struct field order; access is via positional
/// destructuring in `is` patterns.
/// One block within a message's content.
/// 
/// Mirrors the Anthropic content-block model, which the OpenAI provider
/// translates to/from its `tool_calls` array.
/// 
/// Field order (positional, matching the Rust struct fields):
/// - `Text(text)`
/// - `ToolUse(id, name, input)`
/// - `ToolResult(tool_use_id, content, is_error)`
#[derive(Clone, Debug, PartialEq)]
pub enum ContentBlock {
    Text(String),
    ToolUse(String, String, JsonValue),
    ToolResult(String, String, bool),
}


impl ContentBlock {
    fn text(t: &str) -> ContentBlock {
        return ContentBlock::Text(t.to_string());
    }
}

/// Wrap a plain-text span in a Text block.
/// A single message in a conversation.
/// 
/// `content` is a list of [ContentBlock]s rather than a flat string so the
/// same message can carry text, tool-use requests (assistant), and tool
/// results (user). The convenience constructors [user], [assistant], [system]
/// wrap a single Text block; use [tool_result] when feeding a tool's output
/// back to the model.
#[derive(Clone, Debug, PartialEq)]
pub struct Message {
    pub role: String,
    pub content: Vec<ContentBlock>,
}

impl Message {
    pub fn user(text: &str) -> Message {
        return Message { role: "user".to_string(), content: vec![ContentBlock::text(text)] };
    }
    pub fn assistant(text: &str) -> Message {
        return Message { role: "assistant".to_string(), content: vec![ContentBlock::text(text)] };
    }
    pub fn system(text: &str) -> Message {
        return Message { role: "system".to_string(), content: vec![ContentBlock::text(text)] };
    }
    pub fn tool_result(tool_use_id: &str, content: &str) -> Message {
        return Message { role: "user".to_string(), content: vec![ContentBlock::ToolResult(tool_use_id.to_string(), content.to_string(), false)] };
    }
    pub fn tool_error(tool_use_id: &str, content: &str) -> Message {
        return Message { role: "user".to_string(), content: vec![ContentBlock::ToolResult(tool_use_id.to_string(), content.to_string(), true)] };
    }
    pub fn text(&self) -> String {
        let mut parts: Vec<String> = vec![];
        for b in &self.content {
            match b {
                ContentBlock::Text(t) => parts.push(t.clone()),
                _ => {},
            };
        }
        return parts.join("");
    }
}

/// A user-role message carrying a single Text block.
/// An assistant-role message carrying a single Text block.
/// A system-role message carrying a single Text block.
/// A user-role message that returns the result of a tool call. The model
/// matches it to the prior assistant ToolUse block via `tool_use_id`.
/// Like [tool_result] but flagged as an error.
/// Convenience: the concatenated text of all Text blocks in this message
/// (ignoring tool-use / tool-result blocks). Handy for logging & tests.
/// A tool the model is allowed to call.
/// 
/// `parameters` is a JSON-schema fragment (the `parameters` field of an
/// OpenAI function definition, or the `input_schema` of an Anthropic tool).
#[derive(Clone, Debug, PartialEq)]
pub struct ToolDefinition {
    pub name: String,
    pub description: String,
    pub parameters: JsonValue,
}

impl ToolDefinition {
    pub fn new(name: &str, description: &str, parameters: JsonValue) -> ToolDefinition {
        return ToolDefinition { name: name.to_string(), description: description.to_string(), parameters: parameters };
    }
}

/// A tool invocation the model emitted in its response.
#[derive(Clone, Debug, PartialEq)]
pub struct ToolCall {
    pub id: String,
    pub name: String,
    pub input: JsonValue,
}

/// Token usage statistics.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct Usage {
    pub input_tokens: u32,
    pub output_tokens: u32,
}

impl Usage {
    pub fn total_tokens(&self) -> u32 {
        return self.input_tokens + self.output_tokens;
    }
}

/// Sum of input + output tokens.
/// A completion request (provider-agnostic).
#[derive(Clone, Debug, PartialEq)]
pub struct CompletionRequest {
    pub model: String,
    pub messages: Vec<Message>,
    pub max_tokens: Option<u32>,
    pub temperature: Option<f64>,
    pub system_prompt: Option<String>,
    pub tools: Vec<ToolDefinition>,
    pub stream: bool,
}

impl CompletionRequest {
    pub fn single(model: &str, prompt: &str) -> CompletionRequest {
        return CompletionRequest { model: model.to_string(), messages: vec![Message::user(prompt)], max_tokens: None, temperature: None, system_prompt: None, tools: vec![], stream: false };
    }
    pub fn with_system(mut self, system: &str) -> CompletionRequest {
        self.system_prompt = Some(system.to_string());
        return self;
    }
    pub fn with_max_tokens(mut self, n: u32) -> CompletionRequest {
        self.max_tokens = Some(n);
        return self;
    }
    pub fn with_temperature(mut self, t: f64) -> CompletionRequest {
        self.temperature = Some(t);
        return self;
    }
    pub fn with_tools(mut self, mut tools: Vec<ToolDefinition>) -> CompletionRequest {
        self.tools = tools;
        return self;
    }
}

/// Tools the model may call. Empty by default.
/// If true, the daemon streams SSE deltas back instead of a single
/// response. (Non-streaming callers leave this false.)
/// Simple single-turn request: one user message.
/// With a system prompt.
/// With max output tokens.
/// With temperature.
/// With a set of callable tools.
/// A completion response.
#[derive(Clone, Debug, PartialEq)]
pub struct CompletionResponse {
    pub content: String,
    pub tool_calls: Vec<ToolCall>,
    pub stop_reason: Option<String>,
    pub usage: Option<Usage>,
    pub model: String,
    pub error: Option<String>,
}

impl CompletionResponse {
    pub fn is_ok(&self) -> bool {
        return self.error.is_none();
    }
    pub fn wants_tool(&self) -> bool {
        return (self.tool_calls.len() as i32) > 0;
    }
}
